; Generated by export.py using data in metadata.json

; Music data banks
.segment "_pprg__rom__50"
	firstMusicBankPtr := *
	.include "music_0.s"

; DMC banks
.segment "_pprg__rom__51"
	firstDMCBankPtr := *
	.incbin "music_bank0.dmc"

; PCM includes

; Constants
FIRST_MUSIC_BANK = .bank(firstMusicBankPtr)
FIRST_DMC_BANK = .bank(firstDMCBankPtr)
