; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for PVZ Deplanted music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_pvz_deplanted_music3:=music_data_pvz_deplanted_music3

music_data_pvz_deplanted_music3:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : crazy dave
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 374,312
; 01 : moongrains
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 245,204
; 02 : dpcm
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	;
	.word 307,256

.export music_data_pvz_deplanted_music3
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env13,@env11,@env12,@env0 ; 00 : blank

@instruments_exp:
	.word @env9, @env11, @env0 ; 00 : 1. Piano (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env9, @env11, @env0 ; 01 : 5. strings (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env9, @env11, @env19 ; 02 : 22. Tuba (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env9, @env11, @env0 ; 03 : 28. organ (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env7, @env11, @env0 ; 04 : blank: epsm edition
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env5, @env11, @env25 ; 05 : 7. Harp (PSG)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env9, @env11, @env0 ; 06 : 2. pizzicato (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env9, @env11, @env0 ; 07 : 8. Acoustic Bass (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env9, @env11, @env0 ; 08 : 27. sinewave (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env9, @env11, @env0 ; 09 : 40. resobass (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env9, @env11, @env0 ; 0a : 54. vox (FM)
	.word @env18, @env11
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10

@instrument_epsm_extra_patch0:
	.byte $3a,$c0,$01,$1f,$18,$04,$34,$00,$33,$1f,$00,$00,$f4,$00,$32,$1f,$04,$00,$b1,$00,$01,$1d,$0c,$00,$f7,$00,$1b,$25,$2c,$11,$00
@instrument_epsm_extra_patch1:
	.byte $24,$c0,$31,$13,$00,$04,$13,$00,$21,$10,$01,$04,$16,$00,$73,$14,$00,$04,$13,$00,$61,$0e,$00,$04,$26,$00,$21,$1c,$1d,$1b,$00
@instrument_epsm_extra_patch2:
	.byte $34,$c0,$00,$1f,$00,$00,$05,$00,$00,$19,$00,$06,$08,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$1a,$12,$7f,$7f,$00
@instrument_epsm_extra_patch3:
	.byte $07,$c0,$46,$1f,$10,$0c,$6a,$00,$73,$1f,$00,$04,$09,$00,$62,$1f,$00,$05,$0b,$00,$20,$1f,$04,$00,$f9,$00,$13,$1d,$16,$16,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch6:
	.byte $13,$c0,$72,$1f,$1b,$0a,$78,$00,$31,$1f,$1f,$06,$06,$00,$24,$1f,$15,$10,$78,$00,$11,$1f,$10,$0e,$38,$00,$25,$22,$15,$10,$00
@instrument_epsm_extra_patch7:
	.byte $1c,$c0,$00,$1f,$0f,$00,$27,$00,$01,$1f,$00,$00,$09,$00,$03,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$0a,$00,$15,$13,$37,$13,$00
@instrument_epsm_extra_patch8:
	.byte $3e,$c0,$02,$1f,$00,$09,$0b,$00,$01,$1f,$00,$02,$0b,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$7f,$0e,$7f,$7f,$00
@instrument_epsm_extra_patch9:
	.byte $1a,$c0,$00,$1f,$14,$00,$90,$00,$00,$1f,$00,$08,$02,$00,$01,$1f,$00,$09,$07,$00,$00,$1f,$00,$0c,$07,$00,$00,$07,$28,$10,$00
@instrument_epsm_extra_patch10:
	.byte $2e,$c0,$71,$1f,$00,$00,$05,$00,$71,$0d,$00,$00,$05,$00,$00,$1f,$00,$00,$05,$00,$31,$0a,$00,$00,$05,$00,$24,$1a,$7f,$1d,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c5,$00,$01
@env2:
	.byte $c2,$c5,$00,$01
@env3:
	.byte $00,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env4:
	.byte $c6,$7f,$00,$00
@env5:
	.byte $1b,$cf,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$02,$c5,$03,$c4,$03,$c3,$04,$c2,$c2,$c2,$00,$18,$c2,$02,$c1,$05,$c0,$08,$c0,$00,$21
@env6:
	.byte $b8,$be,$00,$01
@env7:
	.byte $04,$cf,$00,$01,$ca,$c5,$c0,$00,$06
@env8:
	.byte $00,$cf,$c6,$c2,$c0,$00,$04
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $ca,$7f,$00,$00
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $04,$cf,$00,$01,$c0,$00,$04
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $c0,$c5,$00,$01
@env16:
	.byte $00,$cf,$c8,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env17:
	.byte $00,$cf,$cc,$c9,$c6,$c5,$c3,$c1,$c0,$00,$08
@env18:
	.byte $c8,$7f,$00,$00
@env19:
	.byte $00,$c0,$c3,$c7,$b8,$bc,$bf,$c0,$00,$07
@env20:
	.byte $c9,$d1,$00,$01
@env21:
	.byte $00,$cf,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env22:
	.byte $00,$c4,$c3,$c2,$c1,$c1,$c0,$00,$06
@env23:
	.byte $00,$cb,$c6,$c3,$c2,$c1,$c0,$00,$06
@env24:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env25:
	.byte $00,$bf,$c0,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0f,$40,$08 ; 00 B3 - industrial bass (Pitch:15)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$11,$0f,$40,$07 ; 01 bongos - C5 (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0f,$40,$07 ; 02 bongos - D5 (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$1b,$0f,$40,$07 ; 03 bongos - Db5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3d,$0f,$40,$07 ; 04 bongos - E5 (Pitch:15)
	.byte $16+.lobyte(FAMISTUDIO_DPCM_PTR),$23,$0f,$40,$07 ; 05 bongos - Eb5 (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$40,$08 ; 06 C3 - smash bass drum (Pitch:15)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$08,$0f,$40,$08 ; 07 C6 - plink (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$2e,$0f,$40,$08 ; 08 D4 - metal light (Pitch:15)
	.byte $6c+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40,$08 ; 09 Db6 - bonk3 (Pitch:15)
	.byte $2b+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0f,$40,$07 ; 0a dice (Pitch:15)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$07 ; 0b dice2 (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$0f,$40,$07 ; 0c E4 - metal loud (Pitch:15)
	.byte $71+.lobyte(FAMISTUDIO_DPCM_PTR),$16,$0f,$40,$08 ; 0d E6 - bonk4 (Pitch:15)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0e,$40,$08 ; 0e Eb6 - bonk (Pitch:14)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0f,$40,$08 ; 0f Eb6 - bonk (Pitch:15)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$04 ; 10 evillaugh0 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 11 evillaugh1 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 12 evillaugh2 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 13 evillaugh3 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 14 evillaugh4 (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$9e,$0f,$40,$08 ; 15 F4 - oil drum snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$3e,$02 ; 16 finalfanfare0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$38,$02 ; 17 finalfanfare1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$58,$03 ; 18 finalfanfare2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 19 finalfanfare3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e9,$0f,$4c,$04 ; 1a finalfanfare4 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$50,$0f,$40,$01 ; 1b industrial snare (Pitch:15)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40,$09 ; 1c laser dabs (Pitch:15)
	.byte $27+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 1d lightfill1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1e lightfill2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1f lightfill3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0b ; 20 lightfill4 (Pitch:15)
	.byte $19+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$09 ; 21 scratch standard (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0f,$40,$09 ; 22 snarish drum (Pitch:15)
	.byte $42+.lobyte(FAMISTUDIO_DPCM_PTR),$88,$0d,$40,$07 ; 23 sunflower (Pitch:13)
	.byte $3f+.lobyte(FAMISTUDIO_DPCM_PTR),$0a,$0f,$40,$07 ; 24 tennis (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 25 winmusic0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 26 winmusic1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 27 winmusic2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$97,$0f,$40,$01 ; 28 winmusic3 (Pitch:15)

@song0ch0:
	.byte $46, $05
@song0ch0loop:
@song0ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch7:
@song0ch3:
@song0ch1:
@song0ch1loop:
	.byte $41, $14
	.word @song0ref4
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $80
@song0ref49:
	.byte $2c, $85, $00, $85, $27, $85, $00, $85, $23, $85, $00, $85, $20, $85, $2a, $99, $00, $81, $28, $99, $00, $89, $27, $85
	.byte $00, $85, $22, $85, $00, $85, $1f, $85, $00, $85, $22, $85, $28, $99, $00, $81, $27, $99, $00, $89
	.byte $41, $16
	.word @song0ref49
@song0ref96:
	.byte $26, $85, $27, $85, $26, $85, $27, $85, $26, $85, $25, $85, $23, $85, $1f, $85, $20, $9d, $1b, $85, $1f, $85, $22, $85
	.byte $27, $85
	.byte $41, $2c
	.word @song0ref49
	.byte $41, $16
	.word @song0ref49
	.byte $41, $12
	.word @song0ref96
	.byte $20, $85, $22, $85, $23
@song0ref136:
	.byte $85, $27, $85, $28, $a1, $00, $99, $25, $81, $00, $81, $28, $81, $00, $81, $2c, $81, $00, $81, $2f, $81, $00, $81, $31
	.byte $81, $00, $81, $33, $81, $00, $81, $2e, $81, $00, $81, $2a, $81, $00, $81, $27, $a1, $00, $9f, $47, $01, $31, $33, $85
	.byte $31, $85, $2f, $85, $31, $85, $2f, $85, $2a
	.byte $41, $16
	.word @song0ref136
	.byte $87, $47, $01, $2f, $31, $81, $00, $89, $2f, $81, $00, $81, $33, $85, $2f, $85, $2c, $85, $31, $8d, $2e, $85, $2a, $85
	.byte $2c, $c1, $00, $81, $42
	.word @song0ch2loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff
@song0ref230:
	.byte $0b, $85, $0c, $85, $0c, $85, $25, $85, $0c, $85, $25, $85, $25, $85, $0c, $85, $00, $bd
	.byte $41, $12
	.word @song0ref230
	.byte $41, $12
	.word @song0ref230
	.byte $41, $11
	.word @song0ref230
	.byte $ff, $ff, $bd
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
@song0ref269:
	.byte $0b, $85, $0c, $85, $0c, $85, $25, $85, $0c, $85, $0c, $85, $0c, $85, $0c, $85
	.byte $41, $10
	.word @song0ref230
	.byte $41, $12
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref269
	.byte $41, $10
	.word @song0ref230
	.byte $41, $12
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref230
	.byte $41, $10
	.word @song0ref269
	.byte $41, $10
	.word @song0ref269
	.byte $41, $10
	.word @song0ref230
	.byte $41, $11
	.word @song0ref230
	.byte $fd, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $7f, $8a
@song0ref340:
	.byte $32, $8d, $32, $8d, $2f, $8d, $7a, $2c, $8d, $7d, $2f, $8d, $7a, $2c, $8d, $7d, $33, $8d, $7a, $2c, $8d, $7f
	.byte $41, $10
	.word @song0ref340
	.byte $7f
	.byte $41, $10
	.word @song0ref340
@song0ref369:
	.byte $7d, $2e, $8d, $2e, $8d, $2c, $8d, $25, $8d, $26, $8d, $2c, $8d, $32, $8d, $38, $8d, $7f
	.byte $41, $10
	.word @song0ref340
	.byte $41, $10
	.word @song0ref369
	.byte $7f
	.byte $41, $10
	.word @song0ref340
	.byte $7f
	.byte $41, $10
	.word @song0ref340
	.byte $7d
@song0ref402:
	.byte $38, $8d, $33, $8d, $2c, $8d, $2c, $8d, $7a, $2f, $8d, $7d, $2c, $8d, $7a, $33, $8d, $7d, $2c, $8d, $7a, $2f, $8d, $7d
	.byte $2c, $8d, $7a, $33, $8d, $7d, $2c, $8d, $7a, $2f, $8d, $7d, $2e, $8d, $31, $8d, $36, $8d
	.byte $41, $18
	.word @song0ref402
	.byte $00, $bd
	.byte $41, $20
	.word @song0ref402
	.byte $41, $18
	.word @song0ref402
	.byte $00, $bd, $ff, $ff, $ff, $ff, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $7f, $87, $8a
@song0ref468:
	.byte $33, $8d, $33, $8d, $2c, $8d, $7a, $2c, $8d, $7d, $2c, $8d, $7a, $2c, $8d, $7d, $2c, $8d, $7a, $2c, $8d, $7f
	.byte $41, $10
	.word @song0ref468
	.byte $7f
	.byte $41, $10
	.word @song0ref468
@song0ref497:
	.byte $7d, $2f, $8d, $2f, $8d, $27, $9d, $27, $8d, $2f, $8d, $33, $8d, $3b, $85, $87, $7f
	.byte $41, $10
	.word @song0ref468
	.byte $41, $0d
	.word @song0ref497
	.byte $8d, $7f
	.byte $41, $0f
	.word @song0ref468
	.byte $8b, $7f, $81
	.byte $41, $0f
	.word @song0ref468
	.byte $85, $7d
@song0ref533:
	.byte $87, $37, $8d, $2f, $8d, $27, $8d, $2f, $8d, $78, $2f, $8d, $7d, $33, $8d, $78, $33, $8d, $7d, $2f, $8d, $78, $2f, $8d
	.byte $7d, $33, $8d, $78, $33, $8d, $7d, $2f, $8d, $2c, $8d, $2f, $8d, $33, $8d, $37, $85
	.byte $41, $19
	.word @song0ref533
	.byte $00, $b5
	.byte $41, $21
	.word @song0ref533
	.byte $41, $19
	.word @song0ref533
	.byte $00, $b5, $ff, $ff, $ff, $ff, $42
	.word @song0ch6loop
@song0ch8:
@song0ch8loop:
	.byte $79, $87
@song0ref597:
	.byte $90
@song0ref598:
	.byte $20, $85, $27, $85, $26, $85, $27, $85, $2a, $85, $27, $85, $5c, $cd
	.byte $41, $0e
	.word @song0ref598
	.byte $41, $0d
	.word @song0ref598
@song0ref618:
	.byte $b5, $27, $85, $25, $85, $23, $85, $26, $9d, $5c, $8d, $25, $85, $23, $85, $5c, $b5, $87
	.byte $41, $0d
	.word @song0ref598
	.byte $41, $10
	.word @song0ref618
	.byte $bd
	.byte $41, $0e
	.word @song0ref598
	.byte $41, $0d
	.word @song0ref598
	.byte $c5, $7b, $86
@song0ref652:
	.byte $2c
@song0ref653:
	.byte $81, $5c, $89, $2c, $81, $5c, $89, $2c, $81, $5c, $89
@song0ref664:
	.byte $2c, $81, $5c, $89, $28, $81, $5c, $89, $28, $81, $5c, $89, $28, $81, $5c, $89, $28, $81, $5c, $89, $27, $81, $5c, $89
	.byte $2b, $81, $5c, $89, $2b, $81, $5c, $89, $2b
	.byte $41, $0f
	.word @song0ref653
	.byte $41, $10
	.word @song0ref652
	.byte $41, $13
	.word @song0ref664
	.byte $91
@song0ref707:
	.byte $7c, $80, $33, $85, $5c, $85, $33, $85, $5c, $85, $31, $85, $5c, $85, $2b, $85, $5c, $a5, $2b, $85, $5c, $85, $33, $85
	.byte $7b, $86
@song0ref733:
	.byte $23, $81, $5c, $89, $2a, $81, $5c, $89, $2a, $81, $5c, $89, $2a, $81, $5c, $81, $2c, $ad, $2f, $85, $2e, $85, $2c, $85
	.byte $25, $95, $27, $9d, $5c, $85, $1b, $bd
	.byte $41, $18
	.word @song0ref733
	.byte $00, $85
	.byte $41, $10
	.word @song0ref707
	.byte $2e, $85, $5c, $85, $33, $85, $5c, $85, $7b, $86, $2a, $81, $2a, $81, $2a, $81, $2c, $81, $5c, $85, $2a, $81, $2a, $81
	.byte $2a, $81, $2c, $81, $5c, $81, $31, $81, $5c, $81, $2c, $81, $19, $81, $1c, $81, $1e, $81, $20, $81, $23, $81, $25, $81
	.byte $27, $81, $2c, $81, $2a, $81, $27, $81, $25, $81, $23, $81, $25, $81, $1e, $81, $1b, $81, $1e, $81, $5c, $85, $25, $81
	.byte $25, $81, $25, $81, $27, $81, $5c, $85, $22, $81, $22, $81, $25, $81, $23, $81, $5c, $95, $22, $81, $22, $81, $22, $81
	.byte $2a, $81, $5c, $81, $27, $81, $5c, $81, $20, $81, $5c, $81, $25, $81, $20, $81, $22, $81, $23, $81, $23, $81, $5c, $85
	.byte $19, $81, $1c, $81, $20, $81, $23, $81, $27, $81, $23, $81, $2a, $81, $27, $81, $2e, $81, $2a, $81, $27, $81, $23, $81
	.byte $22, $81, $1e, $81, $1c, $81, $5c, $89, $20, $81, $5c, $89, $20, $81, $5c, $89, $20, $81, $5c, $89, $27, $95, $1b, $95
	.byte $5c, $85, $27, $bd, $5c, $85, $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $7c, $8c
@song0ref953:
	.byte $2f, $85, $5c, $85, $2c, $85, $5c, $85, $00, $dd, $2f, $85, $5c, $85, $2c, $85, $5c, $85, $00, $dd
@song0ref973:
	.byte $2f, $85, $5c, $85, $2c, $85, $5c, $85, $32, $85, $33, $85, $3b, $85, $38, $85, $5c, $85, $00, $b5
	.byte $41, $13
	.word @song0ref973
	.byte $95, $2f, $85, $2c, $85, $33, $85, $2c, $85
	.byte $41, $14
	.word @song0ref973
	.byte $41, $13
	.word @song0ref973
	.byte $95, $2f, $85, $2c, $85, $33, $85, $2c, $85
	.byte $41, $13
	.word @song0ref953
	.byte $bd, $38, $81, $5c, $89, $2f, $81, $5c, $89, $7b, $86
@song0ref1034:
	.byte $27
@song0ref1035:
	.byte $81, $5c, $89, $27, $81, $5c, $89, $27
@song0ref1043:
	.byte $81, $5c, $89, $27, $81, $5c, $89, $23, $81, $5c, $89, $23, $81, $5c, $89, $23, $81, $5c, $89, $23, $81, $5c, $89, $2b
	.byte $41, $0f
	.word @song0ref1035
	.byte $41, $10
	.word @song0ref1034
	.byte $41, $20
	.word @song0ref1034
	.byte $00, $fd
@song0ref1078:
	.byte $27, $81, $5c, $89
@song0ref1082:
	.byte $23, $81, $5c, $89, $27, $81, $5c, $89, $23, $81, $5c, $a1, $28, $9d, $5c, $85, $22, $bd, $20, $bd
	.byte $41, $14
	.word @song0ref1078
	.byte $00, $fd, $87, $2e, $81, $2e, $81, $2e, $81, $2f, $81, $5c, $85, $2e, $81, $2e, $81, $2e, $81, $2f, $81, $5c, $d5, $22
	.byte $81, $22, $81, $22, $81, $23, $81, $5c, $85, $25, $81, $25, $81, $22, $81, $27, $81, $5c, $95, $25, $81, $25, $81, $25
	.byte $81, $2e, $81, $5c, $81, $2c, $81, $5c, $81, $27, $81, $5c, $85, $23, $81, $25, $81, $27, $81, $2a, $81, $5c, $cd
	.byte $41, $0b
	.word @song0ref1082
	.byte $89, $23, $95, $1e, $95, $5c, $85, $25, $9d, $24, $9d, $5c, $85, $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $ff, $ff, $92
@song0ref1199:
	.byte $14, $85, $5c, $85, $17, $85, $5c, $85, $1b, $9d, $5c, $9d, $00, $9d, $1c, $85, $5c, $85, $20, $85, $5c, $85, $23, $9d
	.byte $5c, $9d, $00, $9d
	.byte $41, $1b
	.word @song0ref1199
	.byte $ff, $ff, $85, $8c, $33, $81, $5c, $89, $2e, $81, $5c, $81, $92
@song0ref1243:
	.byte $14, $85, $14, $85, $17, $85, $14, $85, $19, $85, $14, $85, $1a, $85, $1b, $85, $19, $85, $19, $85, $1c, $85, $19, $85
	.byte $1c, $85, $19, $85, $1f, $85, $20, $85, $1b, $85, $1b, $85, $1f, $85, $1b, $85, $22, $85, $1b, $85, $25, $85, $22, $85
	.byte $41, $10
	.word @song0ref1243
	.byte $41, $24
	.word @song0ref1243
@song0ref1297:
	.byte $19, $85, $19, $85, $17, $85, $17, $85, $16, $85, $16, $85, $14, $85, $14, $85, $14, $85, $14, $85, $1b, $9d
	.byte $41, $30
	.word @song0ref1243
	.byte $41, $10
	.word @song0ref1243
	.byte $41, $24
	.word @song0ref1243
	.byte $41, $14
	.word @song0ref1297
	.byte $5c, $9d
@song0ref1333:
	.byte $19, $85, $19, $85, $1c, $85, $19, $85, $1e, $85, $19, $85, $1f, $85, $20, $85
	.byte $41, $10
	.word @song0ref1333
	.byte $41, $10
	.word @song0ref1243
	.byte $41, $18
	.word @song0ref1243
	.byte $1e, $85, $19, $85, $1f, $85, $20, $85
	.byte $41, $10
	.word @song0ref1333
	.byte $1c, $85, $5c, $8d, $1b, $85, $5c, $95, $14, $85, $14, $8d, $14, $8d, $14, $8d, $14, $8d, $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $7c, $ff, $dd, $47, $01, $94, $26, $87, $5c, $83, $47, $01, $2c, $87, $5c, $85
@song0ref1407:
	.byte $33, $bd, $5c, $9d, $33, $9d, $5c, $9d, $00, $9d, $2c, $bd
	.byte $41, $0c
	.word @song0ref1407
	.byte $5c, $bb, $00, $ff, $9d, $26, $87, $5c, $83, $2c, $87, $5c, $85, $80
@song0ref1436:
	.byte $38, $85, $5c, $85, $33, $85, $5c, $85, $2f, $85, $5c, $85, $2c, $85, $36, $95, $5c, $85, $34, $95, $5c, $8d, $33, $85
	.byte $5c, $85, $2e, $85, $5c, $85, $2b, $85, $5c, $85, $2e, $85, $34, $95, $5c, $85, $33, $95, $5c, $8d
	.byte $41, $16
	.word @song0ref1436
@song0ref1483:
	.byte $32, $85, $5c, $85, $32, $85, $5c, $85, $32, $85, $5c, $85, $2f, $85, $5c, $85, $2c, $9d, $27, $85, $5c, $85, $2e, $85
	.byte $5c, $85
	.byte $41, $2c
	.word @song0ref1436
	.byte $41, $16
	.word @song0ref1436
	.byte $41, $12
	.word @song0ref1483
	.byte $2c, $85, $5c, $85, $2f, $85, $5c
@song0ref1525:
	.byte $85, $34, $9d, $5c, $9d, $31, $81, $5c, $89, $38, $81, $5c, $89, $3d, $81, $5c, $89, $3a, $81, $5c, $89, $33, $9d, $5c
	.byte $a5, $3f, $85, $5c, $85, $3b, $85, $5c, $85, $3b, $85, $5c, $85, $33
	.byte $41, $0c
	.word @song0ref1525
	.byte $91, $3d, $81, $5c, $91, $3f, $85, $3b, $85, $38, $85, $3d, $8d, $3a, $85, $5c, $85, $38, $bd, $5c, $85, $42
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $7c, $ff, $e5, $47, $01, $94, $27, $87, $5c, $83, $47, $01, $2f, $87, $5c, $8d, $00, $ad, $32, $9d, $5c, $9d, $2f, $bd
	.byte $5c, $bd, $bf, $32, $9d, $5c, $9d, $2f, $bd, $5c, $bd, $00, $ff, $e3, $27, $87, $5c, $83, $2f, $87
@song0ref1635:
	.byte $38, $bd, $36, $9d, $34, $9d, $33, $bd, $31, $9d, $2f, $9d, $38, $bd, $36, $9d, $34, $9d, $33, $bd, $5c, $bd
	.byte $41, $16
	.word @song0ref1635
	.byte $c7, $80, $34, $81, $5c, $89, $3b, $81, $5c, $89, $3f, $81, $5c, $89, $36, $81, $5c, $c7, $47, $01, $3d, $5c, $85, $3d
	.byte $85, $5c, $85, $3d, $85, $5c, $85, $36, $85, $5c, $c5, $00, $85, $34, $81, $5c, $89, $3b, $81, $5c, $87, $47, $01, $3b
	.byte $5c, $8d, $3b, $81, $5c, $81, $7b, $86, $20, $95, $22, $95, $80, $36, $85, $5c, $c5, $42
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
	.byte $41, $0e
	.word @song0ref597
	.byte $41, $0e
	.word @song0ref598
	.byte $41, $0d
	.word @song0ref598
	.byte $41, $10
	.word @song0ref618
	.byte $bd
	.byte $41, $0d
	.word @song0ref598
	.byte $41, $10
	.word @song0ref618
	.byte $bd
	.byte $41, $0e
	.word @song0ref598
	.byte $41, $0e
	.word @song0ref598
	.byte $00, $ff, $ff, $ff, $fd, $7b, $86, $2a
	.byte $41, $0b
	.word @song0ref1043
	.byte $27, $81, $5c, $c9, $1f, $bd, $25, $95, $23, $9d, $5c, $85, $2a
	.byte $41, $0b
	.word @song0ref1043
	.byte $27, $81, $5c, $cd, $00, $f9, $ff, $ff, $ff, $1c, $95, $25, $95, $5c, $85, $20, $bd, $5c, $85, $42
	.word @song0ch13loop
@song0ch14:
@song0ch14loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7d, $88
@song0ref1815:
	.byte $19, $00, $9b, $19, $00, $83, $19, $00, $93, $19, $00, $9b, $19, $00, $83, $19, $00, $93
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $12
	.word @song0ref1815
@song0ref1839:
	.byte $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $b5
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $0f
	.word @song0ref1839
	.byte $c5
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $12
	.word @song0ref1815
	.byte $41, $11
	.word @song0ref1815
	.byte $ff, $93, $42
	.word @song0ch14loop
@song0ch15:
@song0ch15loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7e, $8f, $88
@song0ref1898:
	.byte $19, $85, $00, $95, $19, $85, $00, $95, $19, $85, $00, $95
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0b
	.word @song0ref1898
	.byte $d5, $19, $85, $00, $95, $19, $85, $00, $85, $8f
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0b
	.word @song0ref1898
	.byte $f5, $19, $85, $00, $85, $8f
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0c
	.word @song0ref1898
	.byte $41, $0b
	.word @song0ref1898
	.byte $ff, $85, $42
	.word @song0ch15loop
@song0ch19:
@song0ch19loop:
	.byte $41, $13
	.word @song0ref4
	.byte $7a, $88
@song0ref1970:
	.byte $19, $85, $00, $85, $7f, $19, $85, $00, $85, $7a, $19, $85, $00, $85, $7f, $19, $85, $00, $85, $7a
	.byte $41, $10
	.word @song0ref1970
	.byte $42
	.word @song0ch19loop
@song1ch0:
	.byte $46, $03
@song1ref3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song1ch0loop:
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch4:
@song1ch3:
@song1ch2:
@song1ch1:
	.byte $41, $0c
	.word @song1ref3
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song1ch1loop:
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $42
	.word @song1ch1loop
@song1ch5:
	.byte $7e
@song1ref61:
	.byte $8a
@song1ref62:
	.byte $31, $8d, $2e, $8d, $00, $8d, $30, $8d, $2e, $8d, $29, $8d, $00, $8d, $2a, $8d, $29, $8d, $2e, $9d, $2d, $8d, $2e, $8d
	.byte $77, $2e, $9d, $00, $8d, $7e
	.byte $41, $1c
	.word @song1ref62
	.byte $7e
@song1ref96:
	.byte $29, $8d, $2e, $8d, $2d, $8d, $30, $8d, $2e, $8d, $35, $8d, $33, $8d, $36, $8d
@song1ref112:
	.byte $31, $8d, $35, $8d, $2d, $8d, $30, $8d, $31, $8d, $2e, $8d, $00, $9d
	.byte $41, $1c
	.word @song1ref96
	.byte $29, $8d, $25, $8d
	.byte $41, $1c
	.word @song1ref62
	.byte $7e
	.byte $41, $1c
	.word @song1ref62
	.byte $7e
	.byte $41, $0c
	.word @song1ref62
@song1ref144:
	.byte $25, $8d, $29
@song1ref147:
	.byte $8d
@song1ref148:
	.byte $27, $8d, $2a, $8d, $2e, $8d, $2a, $8d, $29, $8d, $24, $8d, $29, $8d, $25, $8d
	.byte $41, $0c
	.word @song1ref62
@song1ref167:
	.byte $27, $8d, $2a, $8d
@song1ref171:
	.byte $25, $8d, $29, $8d, $2e, $8d, $2a, $8d, $2e, $8d, $29, $8d, $22, $8d, $77, $22, $8d, $7e
	.byte $41, $0c
	.word @song1ref62
	.byte $41, $14
	.word @song1ref144
	.byte $41, $0c
	.word @song1ref62
	.byte $41, $12
	.word @song1ref167
	.byte $77, $25, $8d, $7e
	.byte $41, $0e
	.word @song1ref148
	.byte $24
	.byte $41, $0f
	.word @song1ref147
	.byte $2d
	.byte $41, $0f
	.word @song1ref147
	.byte $24
	.byte $41, $0f
	.word @song1ref147
	.byte $24, $8d
@song1ref222:
	.byte $2a, $8d, $29, $8d, $79, $29, $8d, $74, $29, $8d, $7e, $28, $8d, $29, $8d, $79, $29, $8d, $74, $29, $8d, $7e, $2a, $8d
	.byte $29, $8d, $28, $8d, $29, $8d, $7b, $29, $8d, $78, $29, $8d, $75, $29, $8d, $73, $29, $8d, $7e
	.byte $41, $14
	.word @song1ref222
	.byte $2d, $8d, $30, $8d, $35, $8d, $79, $35, $8d, $74, $35, $8d, $72, $35, $8d, $00, $fd, $ff
@song1ch5loop:
	.byte $7e
	.byte $41, $1c
	.word @song1ref62
	.byte $7e
	.byte $41, $1c
	.word @song1ref62
	.byte $ff, $ff, $ff, $ff, $7e, $3a, $8d, $35, $8d, $35, $8d, $7a, $35, $8d, $7e, $33, $8d, $36, $8d, $35, $8d, $7a, $35, $8d
	.byte $7e, $36, $8d, $31, $8d, $2e, $8d, $7a, $2e, $8d, $7e, $36, $8d, $31, $8d, $2e, $8d, $7a, $2e, $8d, $00, $fd, $ff, $ff
	.byte $ff, $42
	.word @song1ch5loop
@song1ch6:
	.byte $87, $7a
	.byte $41, $0f
	.word @song1ref61
@song1ref352:
	.byte $85, $87, $29, $8d, $2e, $9d, $2d, $8d, $2e, $8d, $75, $2e, $9d, $00, $85, $87, $7a
	.byte $41, $0f
	.word @song1ref62
	.byte $41, $0f
	.word @song1ref352
	.byte $7a
	.byte $41, $0f
	.word @song1ref96
	.byte $85, $87
	.byte $41, $0d
	.word @song1ref112
	.byte $95, $87
	.byte $41, $0f
	.word @song1ref96
	.byte $85, $87
	.byte $41, $0c
	.word @song1ref112
	.byte $29, $8d, $25, $85, $87
	.byte $41, $0f
	.word @song1ref62
	.byte $41, $0f
	.word @song1ref352
	.byte $7a
	.byte $41, $0f
	.word @song1ref62
	.byte $41, $0f
	.word @song1ref352
	.byte $7a
	.byte $41, $0c
	.word @song1ref62
	.byte $25, $8d, $29, $85, $87
	.byte $41, $0f
	.word @song1ref148
	.byte $85, $87
	.byte $41, $0c
	.word @song1ref62
	.byte $27, $8d, $2a, $85, $87
	.byte $41, $0e
	.word @song1ref171
	.byte $75, $22, $85, $87, $7a
	.byte $41, $0c
	.word @song1ref62
	.byte $25, $8d, $29, $85, $87
	.byte $41, $0f
	.word @song1ref148
	.byte $85, $87
	.byte $41, $0c
	.word @song1ref62
	.byte $27, $8d, $2a, $85, $87
	.byte $41, $0e
	.word @song1ref171
	.byte $75, $25, $85, $87, $7a
	.byte $41, $0e
	.word @song1ref148
	.byte $24, $85, $87
	.byte $41, $0e
	.word @song1ref148
	.byte $2d, $85, $87
	.byte $41, $0e
	.word @song1ref148
	.byte $24, $85, $87
	.byte $41, $0e
	.word @song1ref148
	.byte $24, $85, $87, $00, $85
@song1ref497:
	.byte $2a, $8d, $29, $8d, $75, $29, $8d, $72, $29, $8d, $7a, $28, $8d, $29, $8d, $75, $29, $8d, $29, $8d, $7a, $2a, $8d, $29
	.byte $8d, $28, $8d, $29, $8d, $75, $29, $8d, $72, $29, $8d, $71, $29, $8d, $00, $8d, $7a
	.byte $41, $14
	.word @song1ref497
	.byte $2d, $8d, $30, $8d, $35, $8d, $75, $35, $8d, $72, $35, $8d, $00, $fd, $ff
@song1ch6loop:
	.byte $87, $7a
	.byte $41, $0f
	.word @song1ref62
	.byte $41, $0f
	.word @song1ref352
	.byte $7a
	.byte $41, $0f
	.word @song1ref62
	.byte $41, $0e
	.word @song1ref352
	.byte $ff, $ff, $ff, $ff, $7e, $87, $36, $8d, $33, $8d, $7c, $35, $8d, $78, $35, $8d, $7e, $35, $8d, $33, $8d, $7c, $35, $8d
	.byte $78, $35, $85, $7e, $87, $33, $8d, $30, $8d, $7c, $2e, $8d, $78, $2e, $85, $7e, $87, $33, $8d, $30, $8d, $7c, $2e, $8d
	.byte $78, $2e, $85, $87, $00, $f5, $ff, $ff, $ff, $42
	.word @song1ch6loop
@song1ch7:
	.byte $8f, $77
	.byte $41, $16
	.word @song1ref61
	.byte $00, $ad, $8f
	.byte $41, $16
	.word @song1ref62
	.byte $00, $ad, $ff, $ff, $ff, $ff, $8f
	.byte $41, $16
	.word @song1ref62
	.byte $00, $ad, $8f
	.byte $41, $16
	.word @song1ref62
	.byte $00, $ad
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song1ch7loop:
	.byte $8f, $77
	.byte $41, $16
	.word @song1ref62
	.byte $00, $ad, $8f
	.byte $41, $16
	.word @song1ref62
	.byte $00, $ad, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch7loop
@song1ch8:
@song1ref697:
	.byte $7c
@song1ref698:
	.byte $8c
@song1ref699:
	.byte $2e, $8d, $35, $8d, $00, $8d, $35, $8d, $31, $8d, $2e, $8d, $2a, $8d, $2d, $8d, $2e, $8d, $31, $8d, $28, $85, $29, $85
	.byte $30, $8d, $00, $bd
	.byte $41, $1c
	.word @song1ref699
@song1ref730:
	.byte $78, $2e, $8d, $7c, $35, $8d, $78, $30, $8d, $7c, $35, $8d, $78, $31, $8d, $3a, $8d, $7c, $33, $8d, $36, $8d
@song1ref752:
	.byte $2e, $8d, $35, $8d, $29, $8d, $35, $8d, $2e, $8d, $35, $8d, $28, $85, $29, $85, $2a, $85, $29, $85
	.byte $41, $15
	.word @song1ref730
@song1ref775:
	.byte $85, $2b, $85, $2c, $85, $2d, $85, $2e, $8d, $35, $8d, $2e, $8d, $00, $8d
	.byte $41, $1c
	.word @song1ref699
	.byte $41, $1c
	.word @song1ref699
	.byte $7b
	.byte $41, $0c
	.word @song1ref699
@song1ref800:
	.byte $29, $8d, $2e
@song1ref803:
	.byte $8d
@song1ref804:
	.byte $33, $8d, $2e, $8d, $00, $8d, $33, $8d, $30, $8d, $29, $8d, $29, $85, $2a, $85, $28, $85, $24, $85
	.byte $41, $0e
	.word @song1ref699
@song1ref827:
	.byte $2e, $8d
@song1ref829:
	.byte $35, $8d, $2e, $8d, $00, $8d, $30, $8d, $2e, $8d, $29, $8d, $22, $8d, $00, $8d
	.byte $41, $0c
	.word @song1ref699
	.byte $41, $18
	.word @song1ref800
	.byte $41, $0e
	.word @song1ref699
	.byte $41, $10
	.word @song1ref827
	.byte $25
	.byte $41, $0e
	.word @song1ref803
	.byte $8d, $24
	.byte $41, $0e
	.word @song1ref803
	.byte $8d, $24
	.byte $41, $0e
	.word @song1ref803
	.byte $8d, $24
	.byte $41, $0e
	.word @song1ref803
	.byte $8d, $24, $8d, $00, $fd, $ff, $ff, $ff, $ff, $ff
@song1ch8loop:
	.byte $41, $1c
	.word @song1ref697
	.byte $41, $1c
	.word @song1ref699
@song1ref893:
	.byte $83, $47, $01, $2e, $81, $35, $89, $47, $01, $2e, $81, $35, $89, $35, $81, $33, $81, $31, $81, $2e, $85, $00, $85, $2a
	.byte $85, $2c, $85, $2e, $85, $2e, $83, $2d, $87, $00, $95
	.byte $41, $12
	.word @song1ref893
	.byte $8d, $2a, $85, $2c, $85, $2e, $83, $2d, $87, $00, $95
	.byte $41, $1f
	.word @song1ref893
	.byte $41, $12
	.word @song1ref893
	.byte $8d, $2a, $85, $2c, $85, $2e, $83, $2d, $87, $00, $95, $7d, $80, $2a, $81, $5c, $81, $2a, $81, $5c, $81, $2c
@song1ref970:
	.byte $81, $5c, $81, $2a, $81, $47, $01, $29, $81, $5c, $89, $47, $01, $1d, $81, $5c, $85, $1d, $81, $5c, $81, $2a, $81, $5c
	.byte $81, $2a, $81, $5c, $81, $2e
	.byte $41, $11
	.word @song1ref970
@song1ref1003:
	.byte $27, $81, $5c, $81, $27, $81, $5c, $81, $25, $81, $5c, $81, $24, $81, $47, $01, $22, $81, $5c, $9d
	.byte $41, $12
	.word @song1ref1003
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch8loop
@song1ch9:
	.byte $87, $75
	.byte $41, $0f
	.word @song1ref698
@song1ref1039:
	.byte $85, $87, $2e, $8d, $31, $8d, $28, $85, $29, $85, $30, $8d, $00, $b5, $87
	.byte $41, $0f
	.word @song1ref699
	.byte $41, $0e
	.word @song1ref1039
	.byte $29, $85
@song1ref1062:
	.byte $2e, $8d, $35, $8d, $30, $8d, $35, $8d, $31, $8d, $3a, $8d, $33, $8d, $36, $85, $87
	.byte $41, $14
	.word @song1ref752
	.byte $41, $11
	.word @song1ref1062
	.byte $2e, $8d, $35, $8d, $29
	.byte $41, $0e
	.word @song1ref775
	.byte $85, $87
	.byte $41, $0f
	.word @song1ref699
	.byte $41, $0f
	.word @song1ref1039
	.byte $41, $0f
	.word @song1ref699
	.byte $41, $0f
	.word @song1ref1039
	.byte $41, $0c
	.word @song1ref699
	.byte $29, $8d, $2e, $85, $87
	.byte $41, $14
	.word @song1ref804
	.byte $41, $0e
	.word @song1ref699
	.byte $2e, $85, $87
	.byte $41, $0f
	.word @song1ref829
	.byte $85, $87
	.byte $41, $0c
	.word @song1ref699
	.byte $29, $8d, $2e, $85, $87
	.byte $41, $14
	.word @song1ref804
	.byte $41, $0e
	.word @song1ref699
	.byte $2e, $85, $87
	.byte $41, $0e
	.word @song1ref829
	.byte $25, $85, $87
	.byte $41, $0d
	.word @song1ref804
	.byte $8d, $24, $85, $87
	.byte $41, $0d
	.word @song1ref804
	.byte $8d, $24, $85, $87, $00, $8d, $7f, $82
@song1ref1170:
	.byte $29, $85, $5c, $85, $00, $95, $11, $85, $5c, $85, $75, $00, $ad, $87, $00, $8d, $7f
	.byte $41, $0c
	.word @song1ref1170
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song1ch9loop:
	.byte $87, $75
	.byte $41, $0f
	.word @song1ref698
	.byte $41, $0f
	.word @song1ref1039
	.byte $41, $0f
	.word @song1ref699
	.byte $41, $0e
	.word @song1ref1039
	.byte $7f, $84
@song1ref1213:
	.byte $22, $85, $5c, $85, $21, $85, $5c, $85, $20, $85, $5c, $81, $1f, $85, $5c, $85, $00, $81, $1e, $85, $5c, $85, $00, $8d
	.byte $1d, $85, $5c, $85, $00, $8d
	.byte $41, $1e
	.word @song1ref1213
	.byte $41, $1e
	.word @song1ref1213
	.byte $41, $1e
	.word @song1ref1213
	.byte $7c, $80
@song1ref1254:
	.byte $22, $81, $5c, $81, $22, $81, $5c, $8d, $47, $01, $21, $81, $5c, $89, $47, $01, $21, $81, $5c, $85, $21, $81, $5c, $81
	.byte $41, $14
	.word @song1ref1254
@song1ref1281:
	.byte $1e, $81, $5c, $81, $1e, $81, $5c, $8d, $47, $01, $19, $81, $5c, $9d
	.byte $41, $0c
	.word @song1ref1281
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch9loop
@song1ch10:
	.byte $ff, $ff, $ff, $ff, $7b, $82
@song1ref1312:
	.byte $2e, $85, $5c, $95, $35, $85, $5c, $93, $35, $85, $5c, $87, $35, $85, $5c, $85, $33, $8d, $5c, $8d, $2e, $85, $5c, $85
	.byte $31, $85, $5c, $85, $28
@song1ref1341:
	.byte $85, $5c, $85, $31, $85, $5c, $85, $2e, $85, $5c, $85, $00, $ad
	.byte $41, $14
	.word @song1ref1312
	.byte $87, $29, $85, $5c, $85, $31, $85, $5c, $85, $35, $85, $5c, $85, $30, $85, $5c, $85, $00, $b5, $ff, $ff, $ff, $ff, $ff
	.byte $ff, $ff, $ff, $2e, $85, $5c, $95, $35, $85, $5c, $95, $35, $85, $5c, $85, $35, $85, $5c, $85, $31, $8d, $5c, $8d, $2a
	.byte $85, $5c, $95, $27, $85, $5c, $95, $29, $85, $5c, $85, $29, $85, $5c, $85, $29, $85, $5c, $85, $25, $85, $5c, $85
	.byte $41, $14
	.word @song1ref1312
	.byte $35, $85, $5c, $8d, $2e, $85, $5c, $8d, $30, $8d, $22, $9d, $5c, $9d, $00, $fd, $ff
@song1ref1448:
	.byte $8f, $27, $85, $5c, $85, $2a, $85, $5c, $85, $2e, $85, $5c, $85, $78, $2d, $9d, $7b, $29, $85, $5c, $85, $00, $8d
	.byte $41, $0d
	.word @song1ref1448
	.byte $78, $30, $9d, $7b, $2d, $85, $5c, $85, $00, $8d, $ff, $ff, $ff, $ff, $ff, $ff
@song1ch10loop:
	.byte $ff, $ff, $ff, $f3, $7c, $80, $34, $81, $35, $85
@song1ref1501:
	.byte $3a, $81, $5c, $89, $35, $81, $5c, $89, $33, $81, $5c, $85, $47, $00, $31, $81, $5c, $89, $47, $00, $30, $81, $5c, $85
	.byte $31, $81, $5c, $89, $31
@song1ref1530:
	.byte $81, $5c, $85, $47, $01, $1d, $5c, $87, $21, $5c, $85, $24, $5c, $81
	.byte $41, $14
	.word @song1ref1501
	.byte $33, $81, $5c, $89, $36
	.byte $41, $0c
	.word @song1ref1530
@song1ref1555:
	.byte $3a, $81, $5c, $81, $3a, $81, $5c, $81, $35, $81, $5c, $47, $01, $31, $81, $5c, $83, $33, $81, $47, $01, $35, $81, $5c
	.byte $81, $47, $00, $31, $81, $5c, $83, $2e, $81, $5c, $47, $00, $30, $81, $31, $81, $5c, $81, $31, $81, $5c, $81, $33, $81
	.byte $5c, $81, $31, $81, $47, $01, $30
@song1ref1610:
	.byte $81, $5c, $81, $47, $01, $1d, $5c, $81, $47, $00, $1f, $5c, $81, $21, $5c, $47, $01, $22, $5c, $81, $24, $5c, $81
	.byte $41, $22
	.word @song1ref1555
	.byte $33, $81, $5c, $81, $35, $81, $5c, $81, $36, $81, $47, $01, $35
	.byte $41, $11
	.word @song1ref1610
	.byte $78, $51, $02, $c0, $82, $25, $97, $81, $7f, $51, $fc, $00, $21, $81, $5c, $9b, $81, $78, $51, $02, $c0, $25, $97, $81
	.byte $7f, $51, $fc, $00, $21, $81, $5c, $9b, $81, $78, $51, $02, $c0, $22, $93, $81, $7f, $51, $fc, $00, $22, $81, $5c, $9f
	.byte $81, $78, $51, $02, $c0, $22, $93, $81, $7f, $51, $fc, $00, $22, $81, $5c, $9f, $81, $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch10loop
@song1ch11:
	.byte $ff, $ff, $ff, $ff, $7b, $82
@song1ref1731:
	.byte $35, $85, $5c, $95, $30, $85, $5c, $93, $3a, $87, $5c, $85, $3a, $85, $5c, $85, $38, $8d, $5c, $8d, $35, $85, $5c, $85
	.byte $00, $85, $2e, $85, $5c, $85, $29, $85, $5c, $85, $30, $85, $5c, $85, $00, $b5
	.byte $41, $14
	.word @song1ref1731
	.byte $28, $85, $5c, $85, $2e, $85, $5c, $85, $34
	.byte $41, $0d
	.word @song1ref1341
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $35, $85, $5c, $95, $30, $85, $5c, $95, $3a, $85, $5c, $85, $3a, $85, $5c, $a5
	.byte $2e, $85, $5c, $95, $2a, $85, $5c, $9d, $2a, $85, $5c, $85, $2a, $85, $5c, $85, $27, $85, $5c, $85, $24, $81, $5c, $81
	.byte $41, $14
	.word @song1ref1731
	.byte $8f, $31, $85, $5c, $85, $31, $8d, $5c, $8d, $29, $9d, $5c, $9d, $00, $fd, $ff, $9f, $22, $85, $5c, $85, $27, $85, $5c
	.byte $85, $78, $24, $9d, $7b, $21, $85, $5c, $85, $00, $8d, $9f, $22, $85, $5c, $85, $27, $85, $5c, $85, $78, $29, $9d, $7b
	.byte $24, $85, $5c, $85, $00, $8d, $ff, $ff, $ff, $ff, $ff, $ff
@song1ch11loop:
	.byte $ff, $ff, $ff, $ff, $7c, $87, $80
@song1ref1905:
	.byte $3a, $81, $5c, $87, $47, $01, $31, $81, $5c, $87, $47, $01, $35, $81, $5c, $89, $00, $2e, $81, $5c, $83, $31, $81, $5c
	.byte $89, $33, $81, $5c, $85, $47, $01, $30, $81, $5c, $87, $47, $00, $1f, $5c, $85, $47, $01, $22, $5c, $87, $83, $00, $81
	.byte $41, $15
	.word @song1ref1905
	.byte $35, $81, $5c, $85, $47, $01, $35, $81, $5c, $87, $47, $00, $1f, $5c, $85, $47, $01, $22, $5c, $87, $79, $82, $3a, $dd
	.byte $39, $9d, $3a, $dd, $39, $9d, $78, $51, $02, $c0, $22, $97, $81, $7f, $51, $fc, $00, $24, $81, $5c, $9b, $81, $78, $51
	.byte $02, $c0, $22, $97, $81, $7f, $51, $fc, $00, $24, $81, $5c, $9b, $81, $78, $51, $02, $c0, $27, $95, $51, $fd, $00, $5c
	.byte $a3, $81, $78, $51, $02, $c0, $27, $95, $51, $fd, $00, $5c, $a3, $81, $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch11loop
@song1ch12:
	.byte $ff, $ff, $ff, $ff, $7b, $82
@song1ref2056:
	.byte $3a, $85, $5c, $95, $39, $85, $5c, $9d, $39, $85, $5c, $85, $35, $85, $5c, $8d, $36, $8d, $5c, $95, $77, $31, $85, $2e
	.byte $85, $28, $85, $29, $85, $31, $85, $30, $85, $2e, $85, $5c, $85, $00, $a3, $7f, $81, $7b
	.byte $41, $13
	.word @song1ref2056
	.byte $85, $77, $28, $85, $29, $85, $2e, $85, $31, $85, $34, $85, $35, $85, $31, $85, $30, $85, $2e, $85, $5c, $85, $00, $a5
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7b
	.byte $41, $10
	.word @song1ref2056
	.byte $35, $8d, $33, $85, $5c, $95, $2e, $85, $5c, $d5
	.byte $41, $13
	.word @song1ref2056
	.byte $bd, $2e, $9d, $5c, $9d, $00, $85, $78
@song1ref2158:
	.byte $80
@song1ref2159:
	.byte $3f, $a5, $3d, $85, $3c, $85, $3a, $85, $39, $8d, $3c, $8d, $40, $4d, $8d, $3c, $85, $87
	.byte $41, $0e
	.word @song1ref2159
	.byte $00, $85, $9f, $7b, $82, $27, $85, $5c, $85, $2a, $85, $5c, $85, $78, $29, $9d, $7b, $24, $85, $5c, $85, $00, $8d, $9f
	.byte $27, $85, $5c, $85, $2a, $85, $5c, $85, $78, $2d, $9d, $7b, $29, $85, $5c, $85, $00, $8d, $00, $9d, $80, $40, $4d, $8d
	.byte $39, $8d, $00, $9d, $35, $8d, $30, $8d, $00, $dd, $3c, $8d, $40, $4d, $8d, $00, $9d, $40, $4d, $8d, $39, $8d, $00, $9d
	.byte $35, $8d, $30, $8d, $00, $fd, $ff, $8f, $70, $51, $01, $c0, $82
@song1ref2265:
	.byte $11, $81, $12, $81, $11, $81, $12, $81, $11, $81, $12, $81
	.byte $41, $0c
	.word @song1ref2265
	.byte $41, $0c
	.word @song1ref2265
	.byte $41, $0c
	.word @song1ref2265
	.byte $11, $81, $12, $81, $11, $81, $7f, $12, $81
@song1ch12loop:
	.byte $00, $fd, $ff, $ff, $ff, $7a, $80
@song1ref2303:
	.byte $29, $81, $5c, $89, $29, $81, $5c, $89, $29, $81, $5c, $8d, $27, $89, $25, $81, $5c, $99, $24, $81, $5c, $99
	.byte $41, $16
	.word @song1ref2303
	.byte $41, $16
	.word @song1ref2303
	.byte $41, $16
	.word @song1ref2303
	.byte $78, $51, $02, $c0, $82, $2a, $97, $81, $7f, $51, $fc, $00, $29, $81, $5c, $9b, $81, $78, $51, $02, $c0, $2a, $97, $81
	.byte $7f, $51, $fc, $00, $29, $81, $5c, $9b, $81, $7c, $80
@song1ref2369:
	.byte $1b, $81, $5c, $81, $1b, $81, $5c, $8d, $47, $01, $16, $81, $5c, $9d
	.byte $41, $0c
	.word @song1ref2369
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch12loop
@song1ch13:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ef, $84
@song1ref2407:
	.byte $1d, $85, $5c, $85, $22, $95, $5c, $85, $21, $85, $22, $85, $24, $8d, $22, $85, $5c, $85, $25, $85, $5c, $85, $29, $8d
	.byte $28, $85, $29, $85, $2a, $85, $5c, $85, $27, $85, $5c, $85, $27, $85, $5c, $85, $22, $85, $5c, $85, $24, $ad
	.byte $41, $10
	.word @song1ref2407
@song1ref2456:
	.byte $2e, $85, $2d, $85, $2e, $85, $2a, $8d, $29, $85, $27, $85, $28, $85, $29, $85, $25, $85, $22, $85, $25, $85, $5c, $85
	.byte $24, $85, $5c, $85, $22, $a5, $5c, $85
	.byte $41, $2e
	.word @song1ref2407
	.byte $41, $10
	.word @song1ref2407
	.byte $41, $20
	.word @song1ref2456
	.byte $00, $8d
	.byte $41, $0f
	.word @song1ref2158
	.byte $8d
	.byte $41, $0e
	.word @song1ref2159
	.byte $00, $8d, $82, $0f, $bd, $5c, $8d, $00, $ad, $0f, $bd, $5c, $8d, $00, $ad, $84
@song1ref2522:
	.byte $1e, $8d, $1d, $8d, $5c, $85, $7b, $80, $3c, $8d, $35, $85, $7f, $84, $1c, $8d, $1d, $8d, $5c, $85, $7b, $80, $36, $8d
	.byte $35, $85, $7f, $84, $1e, $8d, $1d, $8d, $1c, $8d, $1d, $8d, $5c, $8d, $00, $ad
	.byte $41, $18
	.word @song1ref2522
	.byte $21, $8d, $24, $8d, $5c, $8d, $00, $ad, $ff, $bf, $8e, $11, $81, $5c, $81, $00, $81, $15, $81, $5c, $81, $00, $81, $18
	.byte $81, $5c, $81, $00, $85, $1d, $81, $5c, $81, $00, $8d
@song1ch13loop:
@song1ref2601:
	.byte $00, $85, $16, $81, $5c, $81
@song1ref2607:
	.byte $00, $81, $47, $01, $11, $81, $5c, $81, $00, $81, $16, $81, $5c, $81, $00, $81, $47, $01, $10, $89, $11, $81, $5c, $81
	.byte $00, $85, $16, $81, $5c, $81, $16, $81, $47, $01, $11, $81, $5c, $81, $00, $81, $18, $81, $5c, $81, $00, $81, $47, $01
	.byte $12, $89, $10, $81, $5c, $81, $11, $81, $5c, $81, $11, $85, $5c, $81, $47, $01, $15, $81, $5c, $81, $00, $81, $18, $81
	.byte $5c, $81, $00, $81, $47, $01, $1d, $89, $11, $81, $5c, $81
	.byte $41, $20
	.word @song1ref2601
	.byte $41, $48
	.word @song1ref2607
	.byte $41, $11
	.word @song1ref2601
	.byte $10, $81, $5c, $11, $81, $5c, $0a, $81, $5c, $00, $85, $80
@song1ref2712:
	.byte $22, $81, $5c, $89, $21, $81, $5c, $89, $20, $81, $5c, $89, $00, $81, $1f, $89, $1e, $81, $5c, $89, $00, $8d, $1d, $81
	.byte $5c, $89, $00, $8d
	.byte $41, $1c
	.word @song1ref2712
	.byte $41, $1c
	.word @song1ref2712
	.byte $41, $1c
	.word @song1ref2712
	.byte $7e, $8e
@song1ref2751:
	.byte $12, $85, $12, $85, $5c, $89, $47, $01, $11, $85, $5c, $85, $47, $01, $11, $81, $5c, $85, $11, $81, $5c, $81
	.byte $41, $12
	.word @song1ref2751
	.byte $0f, $85, $1b, $85, $5c, $89, $47, $01, $16, $85, $5c, $99, $0f, $85, $1b, $85, $5c, $89, $47, $01, $16, $85, $5c, $99
	.byte $41, $4e
	.word @song1ref2601
	.byte $41, $20
	.word @song1ref2601
	.byte $41, $48
	.word @song1ref2607
	.byte $41, $1a
	.word @song1ref2601
	.byte $42
	.word @song1ch13loop
@song1ch14:
	.byte $41, $0c
	.word @song1ref3
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $88, $25, $85, $00, $8d, $25, $85, $00, $9d, $25, $85, $00, $8d, $25, $85, $00, $9d, $25, $85, $00
	.byte $8d, $25, $85, $00, $9d, $25, $85, $25, $85, $25, $81, $25, $89, $25, $8d, $00, $8d
@song1ch14loop:
@song1ref2863:
	.byte $25, $85, $25, $85, $00, $81, $25, $85, $00, $81, $25, $85, $00, $81, $25, $85, $00, $81, $25, $85
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $25, $85, $25, $85, $00, $81, $25, $85, $00, $81, $25, $00, $81, $25, $00, $81, $25, $00, $81, $25, $8b
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $14
	.word @song1ref2863
	.byte $41, $0d
	.word @song1ref2863
	.byte $95, $ff, $ff, $ff, $ff, $42
	.word @song1ch14loop
@song1ch15:
	.byte $41, $0c
	.word @song1ref3
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $87, $88
@song1ref2978:
	.byte $25, $25, $25, $25, $25, $85, $00, $85, $25, $25, $25, $25, $25, $85, $25, $85, $00, $8d, $25, $25, $25, $25, $25, $83
	.byte $00, $87, $25, $25, $25, $85, $25, $25, $25, $85, $25, $85, $00, $85
	.byte $41, $0f
	.word @song1ref2978
	.byte $8d, $00, $ad, $25, $25, $25, $25, $25, $25, $25, $25
@song1ch15loop:
	.byte $00, $fd, $ff, $ff, $ff, $87, $8e
@song1ref3038:
	.byte $25, $85, $00, $85, $25, $85, $00, $85, $25, $85, $00, $85
	.byte $41, $0c
	.word @song1ref3038
	.byte $25, $85, $00, $85, $25, $81, $47, $01, $25, $81, $00, $85
	.byte $41, $0c
	.word @song1ref3038
	.byte $41, $0c
	.word @song1ref3038
	.byte $25, $85, $00, $85, $25, $47, $00, $25, $47, $01, $25, $81
@song1ref3083:
	.byte $00, $81, $47, $01, $25, $81, $25, $85, $00, $85, $25, $85, $00, $85, $25, $85
	.byte $41, $0e
	.word @song1ref3083
	.byte $00, $85
	.byte $41, $0c
	.word @song1ref3038
	.byte $41, $0c
	.word @song1ref3038
	.byte $41, $0c
	.word @song1ref3038
	.byte $25, $47, $00, $25, $47, $01, $25, $81, $00, $fd, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch15loop
@song1ch16:
	.byte $41, $0c
	.word @song1ref3
	.byte $41, $0c
	.word @song1ref3
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song1ch16loop:
	.byte $88
@song1ref3145:
	.byte $25, $85, $7a, $25, $85
@song1ref3150:
	.byte $25, $85
@song1ref3152:
	.byte $25, $81, $47, $01, $25, $81
@song1ref3158:
	.byte $25, $85, $25, $85, $25, $85, $25, $81, $47, $01, $25, $81, $25, $85, $25
@song1ref3173:
	.byte $85, $25, $85, $25, $81, $47, $01, $25, $81, $25, $85, $25, $81, $47, $01, $25, $81
	.byte $41, $1d
	.word @song1ref3150
	.byte $41, $0d
	.word @song1ref3173
	.byte $25, $81, $47, $01, $25, $81
	.byte $41, $1b
	.word @song1ref3152
	.byte $41, $0d
	.word @song1ref3173
	.byte $41, $1d
	.word @song1ref3150
	.byte $85, $25, $85, $25, $85, $25, $83, $25, $83, $25, $81, $7f, $81, $25, $83, $00, $85
	.byte $41, $24
	.word @song1ref3145
	.byte $41, $1d
	.word @song1ref3150
	.byte $41, $0d
	.word @song1ref3173
	.byte $25, $81, $47, $01, $25, $81, $25, $81, $47, $01, $25, $7f, $81, $7a, $25, $85, $7f, $25, $85, $7a, $25, $85, $7f, $25
	.byte $81, $47, $01, $7c, $25, $81, $7a
	.byte $41, $1a
	.word @song1ref3158
	.byte $41, $1d
	.word @song1ref3150
	.byte $41, $0d
	.word @song1ref3173
	.byte $25, $81, $47, $01, $25, $81, $25, $81, $47, $01, $25, $7f, $81
	.byte $41, $24
	.word @song1ref3145
	.byte $41, $1d
	.word @song1ref3150
	.byte $41, $0d
	.word @song1ref3173
	.byte $25, $81, $47, $01, $25, $81, $25, $81, $47, $01, $25, $7f, $81, $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch16loop
@song2ch0:
	.byte $46, $0a
@song2ch0loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch0loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $26, $27, $28, $29, $17, $18, $19, $1a, $1b, $11, $12, $13, $14, $15, $00, $1e, $1f, $20, $21, $00, $8f, $1c, $00, $83
	.byte $0b, $0c, $25, $05, $03, $06, $02, $04, $07, $16, $01, $0d, $09, $00, $83, $24, $00, $83, $10, $0f, $0a, $0e, $08, $00
	.byte $83, $23, $1d, $00, $81, $22, $00, $ff, $ff, $fb, $42
	.word @song2ch4loop
