; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : dpcm
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 307,256
; 01 : Stay Inside Me EPSM
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 262,218

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env1,@env6,@env0 ; 00 : SIM Drums (DPCM)

@instruments_exp:
	.word @env2, @env3, @env0 ; 00 : SIM practice thingy (FM)
	.word @env8, @env3
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env4, @env3, @env0 ; 01 : epsm hihat (PSG)
	.word @env7, @env3
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env2, @env3, @env0 ; 02 : epsm noise (PSG)
	.word @env7, @env3
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env2, @env3, @env0 ; 03 : SIM Bass (FM)
	.word @env8, @env3
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4

@instrument_epsm_extra_patch0:
	.byte $2c,$c0,$08,$1f,$11,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$2c,$0d,$7f,$7f,$00
@instrument_epsm_extra_patch2:
	.byte $04,$80,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch3:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch4:
	.byte $3a,$c0,$00,$1f,$0d,$00,$30,$00,$01,$1f,$00,$00,$07,$00,$04,$1f,$00,$00,$07,$00,$01,$13,$00,$00,$07,$00,$1d,$7f,$39,$0d,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $b8,$be,$00,$01
@env2:
	.byte $00,$cf,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$cf,$ce,$cc,$c0,$00,$04
@env5:
	.byte $00,$cb,$c5,$c2,$c0,$00,$04
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $c1,$7f,$00,$00
@env8:
	.byte $c8,$7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0f,$40,$00 ; 00 practice kick (Pitch:15)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0e,$00,$00 ; 01 VEH2_Fill_Ins_-_ (Pitch:14)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0f,$00,$00 ; 02 VEH2_Fill_Ins_-_ (Pitch:15)

@song0ch0:
	.byte $46, $0a
@song0ch0loop:
	.byte $9f, $42
	.word @song0ch0loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch3:
@song0ch2:
@song0ch1:
@song0ch1loop:
	.byte $9f, $42
	.word @song0ch1loop
@song0ch4:
@song0ch4loop:
	.byte $01, $03, $02, $99, $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $03
@song1ch0loop:
@song1ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0d
	.word @song1ref4
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch6:
@song1ch5:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch1loop
@song1ch3:
@song1ch3loop:
	.byte $80
@song1ref58:
	.byte $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d
	.byte $41, $0e
	.word @song1ref58
	.byte $41, $0e
	.word @song1ref58
	.byte $41, $0e
	.word @song1ref58
	.byte $25, $bd, $00, $ff, $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref96:
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d
	.byte $41, $0e
	.word @song1ref96
	.byte $41, $0e
	.word @song1ref96
	.byte $41, $0e
	.word @song1ref96
	.byte $01, $9d, $03, $85, $02, $85, $03, $81, $03, $81, $02, $81, $03, $81, $00, $ff, $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch4loop
@song1ch7:
@song1ch7loop:
	.byte $83, $79, $82
@song1ref149:
	.byte $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $10
	.word @song1ref149
	.byte $41, $0e
	.word @song1ref149
	.byte $71, $51, $02, $d0, $84, $25, $8d, $25, $ad, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch7loop
@song1ch8:
@song1ch8loop:
	.byte $78, $86
@song1ref239:
	.byte $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78, $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78
	.byte $41, $10
	.word @song1ref239
	.byte $78
	.byte $41, $10
	.word @song1ref239
	.byte $78
	.byte $41, $10
	.word @song1ref239
@song1ref270:
	.byte $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81, $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81
	.byte $41, $10
	.word @song1ref270
@song1ref293:
	.byte $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $12, $81, $7f
	.byte $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78
	.byte $41, $10
	.word @song1ref239
	.byte $78
	.byte $41, $10
	.word @song1ref239
	.byte $78
	.byte $41, $10
	.word @song1ref239
	.byte $78
	.byte $41, $10
	.word @song1ref239
@song1ref349:
	.byte $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81, $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81
	.byte $41, $10
	.word @song1ref349
	.byte $41, $20
	.word @song1ref293
	.byte $00, $ff, $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch8loop
@song1ch9:
@song1ch9loop:
@song1ref388:
	.byte $80
@song1ref389:
	.byte $23
@song1ref390:
	.byte $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85
	.byte $41, $0e
	.word @song1ref389
	.byte $21
	.byte $41, $0d
	.word @song1ref390
@song1ref410:
	.byte $1f, $8d, $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26, $85, $23, $8d, $2f, $85, $2d, $81, $2f, $85, $2a, $89
	.byte $28, $85, $2a, $85, $23, $8d, $32, $85, $31, $81, $32, $85, $2f, $89, $2d, $85, $2f, $85, $26, $8d, $32, $85, $31, $81
	.byte $2d, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81, $2b, $85, $2a, $89, $28, $85, $2a, $85, $00, $ff
	.byte $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch9loop
@song1ch10:
@song1ch10loop:
	.byte $7c, $8f, $80, $23, $85, $21, $81, $23, $85, $1e, $89, $1c, $85, $1e, $95, $26, $85, $25, $81, $26, $85, $23, $89, $21
	.byte $85, $23, $95, $26, $85, $25, $81, $21, $85, $1a, $89, $19, $85, $1a, $95, $1f, $85, $1e, $81, $1f, $85, $1e, $89, $1c
	.byte $85, $1e, $85, $8f, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $26, $89
	.byte $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $23, $89, $21, $85, $23, $95, $28, $85, $26, $81, $28, $85, $26, $89
	.byte $25, $85, $26, $85, $00, $ff, $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch10loop
@song1ch11:
@song1ch11loop:
	.byte $78, $8f
	.byte $41, $0e
	.word @song1ref388
	.byte $41, $0e
	.word @song1ref389
	.byte $21
	.byte $41, $0d
	.word @song1ref390
	.byte $41, $42
	.word @song1ref410
	.byte $00, $ff, $fd
	.byte $41, $0d
	.word @song1ref4
	.byte $41, $0d
	.word @song1ref4
	.byte $42
	.word @song1ch11loop
