; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash EPSM:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_epsm:=music_data_famidash_epsm

music_data_famidash_epsm:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Stay Inside Me EPSM
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 262,218
; 01 : dpcm
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 307,256

.export music_data_famidash_epsm
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env11,@env2,@env7,@env0 ; 00 : SIM Kick (DMC)
	.word @env8,@env2,@env7,@env0 ; 01 : VEH2 Houseloops - 060 (DMC)
	.word @env3,@env1,@env7,@env0 ; 02 : SIM VEH2_Fill_Ins_-_34 (DMC)

@instruments_exp:
	.word @env4, @env5, @env0 ; 00 : SIM practice thingy (FM)
	.word @env10, @env5
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env4, @env5, @env0 ; 01 : epsm noise (PSG)
	.word @env9, @env5
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env6, @env5, @env0 ; 02 : epsm hihat (PSG)
	.word @env9, @env5
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env4, @env5, @env0 ; 03 : SIM Bass (FM)
	.word @env10, @env5
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6

@instrument_epsm_extra_patch3:
	.byte $2c,$c0,$08,$1f,$11,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$2c,$0d,$7f,$7f,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $04,$80,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch6:
	.byte $3a,$c0,$00,$1f,$0d,$00,$30,$00,$01,$1f,$00,$00,$07,$00,$04,$1f,$00,$00,$07,$00,$01,$13,$00,$00,$07,$00,$1d,$7f,$39,$0d,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $b7,$bd,$00,$01
@env2:
	.byte $b8,$be,$00,$01
@env3:
	.byte $00,$c5,$c2,$c0,$00,$03
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $00,$cf,$ce,$cc,$c0,$00,$04
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $00,$c8,$c2,$c1,$c0,$00,$04
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $c8,$7f,$00,$00
@env11:
	.byte $00,$c9,$c4,$c1,$c0,$00,$04

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0f,$40,$00 ; 00 practice kick (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$40,$00 ; 01 VEH2 Houseloops  (Pitch:15)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0e,$00,$00 ; 02 VEH2_Fill_Ins_-_ (Pitch:14)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0f,$00,$00 ; 03 VEH2_Fill_Ins_-_ (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
@song0ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $ff, $ff, $42
	.word @song0ch0loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch5:
@song0ch2:
@song0ch1:
@song0ch1loop:
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $ff, $ff, $42
	.word @song0ch1loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref52:
	.byte $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d
	.byte $41, $0a
	.word @song0ref52
	.byte $41, $0a
	.word @song0ref52
	.byte $41, $0a
	.word @song0ref52
	.byte $41, $0a
	.word @song0ref52
	.byte $25, $8d, $25, $8d, $25, $8d, $25, $9d, $84, $25, $85, $24, $85, $25, $81, $25, $81, $24, $81, $25, $81
@song0ref95:
	.byte $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $8d, $82, $25, $8d, $80, $25, $8d, $82, $25, $89, $84, $25, $81
	.byte $80, $25, $81, $84, $25, $89, $82, $25, $8d
	.byte $41, $16
	.word @song0ref95
	.byte $41, $16
	.word @song0ref95
	.byte $41, $16
	.word @song0ref95
	.byte $41, $16
	.word @song0ref95
	.byte $41, $16
	.word @song0ref95
	.byte $00, $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref156:
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $8d, $01, $8d
	.byte $41, $0a
	.word @song0ref156
	.byte $41, $0a
	.word @song0ref156
	.byte $41, $0a
	.word @song0ref156
	.byte $41, $0a
	.word @song0ref156
	.byte $01, $8d, $01, $8d, $01, $8d, $01, $9d, $04, $85, $03, $85, $04, $81, $04, $81, $03, $81, $04, $81
@song0ref198:
	.byte $01, $8d, $02, $89, $04, $81, $01, $8d, $02, $8d, $01, $8d, $02, $89, $04, $81, $01, $81, $04, $89, $02, $8d
	.byte $41, $16
	.word @song0ref198
	.byte $41, $16
	.word @song0ref198
	.byte $41, $16
	.word @song0ref198
	.byte $41, $16
	.word @song0ref198
	.byte $41, $16
	.word @song0ref198
	.byte $00, $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch4loop
@song0ch6:
@song0ch6loop:
	.byte $ff, $ff, $ff, $bf, $71, $51, $02, $d0, $82, $25, $8d, $25, $ad, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd, $ff
	.byte $ff, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $ff, $ff, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $00, $81, $79, $84
@song0ref299:
	.byte $25, $81, $7c, $25, $81, $79, $25, $81
@song0ref307:
	.byte $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $0f
	.word @song0ref299
	.byte $bd
	.byte $41, $0a
	.word @song0ref307
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $41, $10
	.word @song0ref299
	.byte $25, $81, $7c, $25, $81, $79, $25, $81, $00, $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch7loop
@song0ch8:
@song0ch8loop:
	.byte $78, $86
@song0ref454:
	.byte $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78, $17, $81, $7f, $17, $81, $17, $81, $17, $81, $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
@song0ref485:
	.byte $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81, $78, $15, $81, $7f, $15, $81, $15, $81, $15, $81
	.byte $41, $10
	.word @song0ref485
@song0ref508:
	.byte $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81, $78, $13, $81, $7f, $13, $81, $13, $81, $13, $81
@song0ref528:
	.byte $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78, $12, $81, $7f, $12, $81, $12, $81, $12, $81, $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
@song0ref564:
	.byte $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81, $78, $1a, $81, $7f, $1a, $81, $1a, $81, $1a, $81
	.byte $41, $10
	.word @song0ref564
	.byte $41, $20
	.word @song0ref508
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref528
	.byte $41, $10
	.word @song0ref528
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref528
	.byte $41, $10
	.word @song0ref528
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $78
	.byte $41, $10
	.word @song0ref454
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref508
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref485
	.byte $41, $10
	.word @song0ref528
	.byte $41, $10
	.word @song0ref528
	.byte $00, $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
@song0ref681:
	.byte $80
@song0ref682:
	.byte $23
@song0ref683:
	.byte $8d
@song0ref684:
	.byte $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85
	.byte $41, $0e
	.word @song0ref682
	.byte $21
	.byte $41, $0d
	.word @song0ref683
@song0ref703:
	.byte $1f
@song0ref704:
	.byte $8d
@song0ref705:
	.byte $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26, $85
@song0ref717:
	.byte $23, $8d, $2f, $85, $2d, $81, $2f, $85, $2a, $89, $28, $85, $2a, $85, $23, $8d, $32, $85, $31, $81, $32, $85, $2f, $89
	.byte $2d, $85, $2f, $85, $26, $8d, $32, $85, $31, $81, $2d, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81
	.byte $2b, $85, $2a, $89, $28, $85, $2a, $85
	.byte $41, $0e
	.word @song0ref682
@song0ref776:
	.byte $1f, $8d, $2b, $85, $2a, $81, $2b, $85, $26, $89, $25, $85, $26, $85, $21, $8d, $28, $85, $26, $81, $28, $85, $25, $89
	.byte $23, $85, $25, $85, $1e
	.byte $41, $35
	.word @song0ref704
@song0ref808:
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85
	.byte $41, $0e
	.word @song0ref682
	.byte $41, $1d
	.word @song0ref776
	.byte $41, $0d
	.word @song0ref704
	.byte $00, $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $7c, $8f, $80
@song0ref849:
	.byte $23, $85, $21, $81, $23, $85, $1e, $89, $1c, $85, $1e, $95, $26, $85, $25, $81, $26, $85, $23, $89, $21, $85, $23, $95
	.byte $26, $85, $25, $81, $21, $85, $1a, $89, $19, $85, $1a, $95, $1f, $85, $1e, $81, $1f, $85, $1e, $89, $1c, $85, $1e, $85
	.byte $8f
	.byte $41, $0b
	.word @song0ref684
	.byte $95
	.byte $41, $0b
	.word @song0ref684
	.byte $95, $2a, $85, $28, $81, $2a, $85, $23, $89, $21, $85, $23, $95
	.byte $41, $0c
	.word @song0ref705
	.byte $00, $8d
	.byte $41, $1e
	.word @song0ref849
@song0ref926:
	.byte $1e, $89, $1c, $85, $1e, $95, $1f, $85, $1e, $81, $1f, $89, $1e, $85, $1c, $85, $1e, $85, $00
	.byte $41, $0c
	.word @song0ref683
	.byte $95
	.byte $41, $0b
	.word @song0ref684
	.byte $95, $2a, $85, $28, $81, $26, $85, $21, $89, $1f, $85, $1c, $95, $26, $85, $25, $81, $28, $85, $26, $89, $25, $85, $26
	.byte $85, $00, $8d
	.byte $41, $1e
	.word @song0ref849
	.byte $41, $13
	.word @song0ref926
	.byte $ff, $fd
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $78, $8f
	.byte $41, $0e
	.word @song0ref681
	.byte $41, $0e
	.word @song0ref682
	.byte $21
	.byte $41, $0d
	.word @song0ref683
	.byte $41, $42
	.word @song0ref703
	.byte $00, $8d
	.byte $41, $0e
	.word @song0ref682
	.byte $41, $1d
	.word @song0ref776
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref717
	.byte $41, $0d
	.word @song0ref808
	.byte $81, $8f
	.byte $41, $0e
	.word @song0ref682
	.byte $41, $1d
	.word @song0ref776
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8f, $00, $ff, $ed
	.byte $41, $0a
	.word @song0ref4
	.byte $41, $0a
	.word @song0ref4
	.byte $42
	.word @song0ch11loop
@song1ch0:
	.byte $46, $0a
@song1ch0loop:
	.byte $9f, $9f, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $9f, $9f, $42
	.word @song1ch1loop
@song1ch4:
@song1ch4loop:
	.byte $01, $04, $00, $99, $9f, $42
	.word @song1ch4loop
