; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music0:=music_data_famidash_music0

music_data_famidash_music0:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Stay Inside Me
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 262,218
; 01 : dpcm
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.word 307,256

.export music_data_famidash_music0
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env24,@env2,@env18,@env0 ; 00 : SIM Kick (DMC)
	.word @env20,@env3,@env18,@env0 ; 01 : VEH2 Houseloops - 060 (DMC)
	.word @env4,@env29,@env18,@env0 ; 02 : VEH2_Fill_Ins_-_34 (DMC)

@instruments_exp:
	.word @env14, @env10, @env0 ; 00 : EPSM Hi-hat
	.word @env21, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env27, @env10, @env0 ; 01 : epsm open ding (PSG)
	.word @env21, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env6, @env10, @env0 ; 02 : Blank: EPSM Edition: Noise Edition
	.word @env21, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env6, @env10, @env0 ; 03 : SIM ding 2 (FM)
	.word @env22, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env6, @env10, @env0 ; 04 : SIM Synth (FM)
	.word @env22, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env6, @env10, @env0 ; 05 : SIM practice thingy (FM)
	.word @env22, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env6, @env10, @env0 ; 06 : SIM Bass (FM)
	.word @env22, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9

@instrument_epsm_extra_patch0:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch1:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch6:
	.byte $33,$c0,$04,$1f,$11,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$02,$1f,$11,$0d,$27,$00,$1e,$20,$7f,$00,$00
@instrument_epsm_extra_patch7:
	.byte $3a,$c0,$02,$1f,$00,$0b,$07,$00,$02,$1f,$10,$00,$47,$00,$02,$1f,$00,$00,$07,$00,$02,$1f,$0e,$11,$37,$00,$1c,$13,$2e,$00,$00
@instrument_epsm_extra_patch8:
	.byte $2c,$c0,$08,$1f,$18,$00,$ff,$00,$02,$1f,$0f,$00,$86,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$2c,$00,$7f,$7f,$00
@instrument_epsm_extra_patch9:
	.byte $3a,$c0,$00,$1f,$0d,$00,$30,$00,$01,$1f,$00,$00,$07,$00,$04,$1f,$00,$00,$07,$00,$01,$13,$00,$00,$07,$00,$1d,$7f,$39,$00,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c7,$cc,$00,$01
@env2:
	.byte $b8,$be,$00,$01
@env3:
	.byte $b8,$bd,$00,$01
@env4:
	.byte $00,$c5,$c2,$c0,$00,$03
@env5:
	.byte $00,$ca,$c5,$c3,$c2,$c1,$c1,$c0,$00,$07
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $00,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env8:
	.byte $00,$cb,$c8,$c2,$c0,$00,$04
@env9:
	.byte $00,$cb,$c7,$c5,$c3,$c2,$02,$c1,$05,$c0,$00,$09
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$c9,$c6,$c4,$c2,$c1,$c0,$00,$06
@env12:
	.byte $00,$c3,$c1,$c1,$c0,$00,$04
@env13:
	.byte $c5,$c9,$00,$01
@env14:
	.byte $00,$ce,$cd,$cb,$c0,$00,$04
@env15:
	.byte $c6,$cb,$00,$01
@env16:
	.byte $00,$c6,$c3,$c2,$c1,$c1,$c0,$00,$06
@env17:
	.byte $c6,$cd,$00,$01
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $b6,$ba,$00,$01
@env20:
	.byte $00,$c8,$c2,$c1,$c0,$00,$04
@env21:
	.byte $c1,$7f,$00,$00
@env22:
	.byte $c8,$7f,$00,$00
@env23:
	.byte $00,$ca,$c7,$c5,$c3,$c2,$c1,$c1,$c0,$00,$08
@env24:
	.byte $00,$c7,$c4,$c1,$c0,$00,$04
@env25:
	.byte $be,$c1,$c0,$00,$02
@env26:
	.byte $ca,$c4,$00,$01
@env27:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cc,$cb,$ca,$c9,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$11
@env28:
	.byte $00,$cb,$c0,$c5,$c4,$c3,$02,$c2,$c0,$00,$08
@env29:
	.byte $b9,$bd,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$42,$0f,$00,$02 ; 00 023 SEUT - Kick (Pitch:15)
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$24,$0f,$40,$00 ; 01 Drums (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0f,$40,$01 ; 02 every end clap (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40,$00 ; 03 gdmt kick (Pitch:15)
	.byte $1d+.lobyte(FAMISTUDIO_DPCM_PTR),$23,$0f,$40,$02 ; 04 gdmt snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0f,$40,$01 ; 05 practice kick (Pitch:15)
	.byte $28+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 06 slhsmp1 (Pitch:15)
	.byte $26+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$02 ; 07 slhsmp2 (Pitch:15)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 08 slhsmp3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 09 slhsmp4 (Pitch:15)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$00 ; 0a snaredrum78 (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$30,$0f,$00,$02 ; 0b stereo madness snare (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$1f,$0f,$40,$02 ; 0c VEC2 Snares 038 (Pitch:15)
	.byte $5f+.lobyte(FAMISTUDIO_DPCM_PTR),$3a,$0f,$40,$00 ; 0d VEH1 Hard Kick (Pitch:15)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$0f,$40,$00 ; 0e VEH1 House Loop - 166 snippet 1 (Pitch:15)
	.byte $1d+.lobyte(FAMISTUDIO_DPCM_PTR),$2c,$0f,$40,$01 ; 0f VEH1 Snares & Claps (Pitch:15)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$7e,$01 ; 10 VEH2 Houseloops  (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0e,$00,$00 ; 11 VEH2_Fill_Ins_-_ (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$1a,$0f,$00,$00 ; 12 VEH2_Fill_Ins_-_ (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
@song0ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $ff, $ff, $ff, $ff, $83, $42
	.word @song0ch0loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch2:
@song0ch1:
@song0ch1loop:
	.byte $41, $1d
	.word @song0ref4
	.byte $42
	.word @song0ch1loop
@song0ch3:
@song0ch3loop:
	.byte $80, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
	.byte $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
	.byte $8d, $25, $8d, $25, $8d, $25, $8d, $25, $8d, $25
@song0ref109:
	.byte $9d, $84, $25, $85, $24, $85, $25, $81, $25, $81, $24, $81, $25, $81
@song0ref123:
	.byte $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $8d, $82, $25, $8d, $80, $25, $8d, $82, $25, $89, $84, $25, $81
	.byte $80, $25, $81, $84, $25, $89, $82, $25, $8d, $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $8d, $82, $25, $8d
	.byte $80, $25, $8d, $82, $25, $89, $84, $25, $81, $80, $25, $81, $84, $25, $89, $82, $25, $8d
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $21
	.word @song0ref123
	.byte $41, $39
	.word @song0ref109
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $21
	.word @song0ref123
	.byte $41, $39
	.word @song0ref109
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $2c
	.word @song0ref123
	.byte $41, $21
	.word @song0ref123
	.byte $9d, $84, $25, $85, $24, $85, $25, $81, $25, $81, $24, $81, $25, $81, $00, $81, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d
	.byte $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06, $8d
	.byte $06, $8d, $06, $8d, $06, $8d, $06, $8d, $06
@song0ref299:
	.byte $9d, $13, $85, $12, $85, $13, $81, $13, $81, $12, $81, $13, $81
@song0ref312:
	.byte $06, $8d, $11, $89, $13, $81, $06, $8d, $11, $8d, $06, $8d, $11, $89, $13, $81, $06, $81, $13, $89, $11, $8d, $06, $8d
	.byte $11, $89, $13, $81, $06, $8d, $11, $8d, $06, $8d, $11, $89, $13, $81, $06, $81, $13, $89, $11, $8d
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $21
	.word @song0ref312
	.byte $41, $39
	.word @song0ref299
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $21
	.word @song0ref312
	.byte $41, $39
	.word @song0ref299
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $2c
	.word @song0ref312
	.byte $41, $21
	.word @song0ref312
	.byte $9d, $13, $85, $12, $85, $13, $81, $13, $81, $12, $81, $13, $81, $00, $81, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $ff, $ff, $ff, $ff, $78, $80
@song0ref414:
	.byte $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a, $81, $7c, $82, $40, $5a, $81, $7a, $80
	.byte $40, $5a, $81, $78, $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a, $81, $7c, $82, $40
	.byte $5a, $81, $7a, $80, $40, $5a, $81, $78, $40, $5a, $81, $7a, $40, $5a, $81, $7c, $82, $40, $5a, $89, $7a, $80, $40, $5a
	.byte $81, $7c, $82, $40, $5a, $81, $7a, $80, $40, $5a, $81, $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $23
	.word @song0ref414
	.byte $c1, $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $23
	.word @song0ref414
	.byte $c1, $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $24
	.word @song0ref414
	.byte $78
	.byte $41, $23
	.word @song0ref414
	.byte $c1, $00, $81, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $00, $ff, $fd, $ff, $ff, $7e, $51, $fe, $10, $84, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd, $7f, $00, $ff, $bd, $ff, $ff, $7e, $51, $fe, $10, $25, $bd
	.byte $7f, $00, $ff, $bd, $ff, $ff, $00, $81, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
@song0ref706:
	.byte $00, $81, $79, $80
@song0ref710:
	.byte $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25
	.byte $81, $79, $25, $81, $00, $81, $25, $81, $7c, $25, $81, $79, $25, $81, $00, $81
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $1e
	.word @song0ref710
	.byte $71, $51, $02, $d0, $84, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song0ref706
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $1e
	.word @song0ref710
	.byte $71, $51, $02, $d0, $84, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song0ref706
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $1e
	.word @song0ref710
	.byte $71, $51, $02, $d0, $84, $25, $8d, $25, $ab, $81
	.byte $41, $22
	.word @song0ref706
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $20
	.word @song0ref710
	.byte $41, $1e
	.word @song0ref710
	.byte $71, $51, $02, $d0, $84, $25, $8d, $25, $ab, $81, $00, $81, $42
	.word @song0ch7loop
@song0ch8:
@song0ch8loop:
	.byte $75, $8c
@song0ref951:
	.byte $17, $81, $78, $17, $81, $17, $81, $17, $81, $75, $17, $81, $78, $17, $81, $17, $81, $17, $81, $75, $17, $81, $78, $17
	.byte $81, $17, $81, $17, $81, $75, $17, $81, $78, $17, $81, $17, $81, $17, $81, $75
	.byte $41, $20
	.word @song0ref951
@song0ref994:
	.byte $75, $15, $81, $78, $15, $81, $15, $81, $15, $81, $75, $15, $81, $78, $15, $81, $15, $81, $15, $81, $75, $15, $81, $78
	.byte $15, $81, $15, $81, $15, $81, $75, $15, $81, $78, $15, $81, $15, $81, $15
@song0ref1033:
	.byte $81, $75, $13, $81, $78, $13, $81, $13, $81, $13, $81, $75, $13, $81, $78, $13, $81, $13, $81, $13, $81, $75, $12, $81
	.byte $78, $12, $81, $12, $81, $12, $81, $75, $12, $81, $78, $12, $81, $12, $81, $12, $81, $75
	.byte $41, $20
	.word @song0ref951
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $75, $1a, $81, $78, $1a, $81, $1a, $81, $1a, $81, $75, $1a, $81, $78, $1a, $81, $1a, $81, $1a, $81, $75, $1a, $81, $78
	.byte $1a, $81, $1a, $81, $1a, $81, $75, $1a, $81, $78, $1a, $81, $1a, $81, $1a
	.byte $41, $21
	.word @song0ref1033
	.byte $75
	.byte $41, $20
	.word @song0ref951
@song0ref1128:
	.byte $75, $13, $81, $78, $13, $81, $13, $81, $13, $81, $75, $13, $81, $78, $13, $81, $13, $81, $13, $81, $75, $13, $81, $78
	.byte $13, $81, $13, $81, $13, $81, $75, $13, $81, $78, $13, $81, $13, $81, $13, $81
	.byte $41, $20
	.word @song0ref994
@song0ref1171:
	.byte $75, $12, $81, $78, $12, $81, $12, $81, $12, $81, $75, $12, $81, $78, $12, $81, $12, $81, $12, $81, $75, $12, $81, $78
	.byte $12, $81, $12, $81, $12, $81, $75, $12, $81, $78, $12, $81, $12, $81, $12, $81, $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $75
	.byte $41, $20
	.word @song0ref951
	.byte $41, $20
	.word @song0ref1128
	.byte $41, $20
	.word @song0ref994
	.byte $41, $20
	.word @song0ref1171
	.byte $00, $81, $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $79
@song0ref1361:
	.byte $8a, $23, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $23, $8d, $2a, $85, $28, $81, $2a, $85, $26
	.byte $89, $25, $85, $26, $85, $21, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $1f
@song0ref1405:
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26, $85
@song0ref1418:
	.byte $23, $8d, $2f, $85, $2d, $81, $2f, $85, $2a, $89, $28, $85, $2a, $85, $23, $8d, $32, $85, $31, $81, $32, $85, $2f, $89
	.byte $2d, $85, $2f, $85, $26, $8d, $32, $85, $31, $81, $2d, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81
	.byte $2b
@song0ref1467:
	.byte $85, $2a, $89, $28, $85, $2a, $85
@song0ref1474:
	.byte $23, $8d, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $85, $1f, $8d, $2b, $85, $2a, $81, $2b, $85, $26, $89
	.byte $25, $85, $26, $85, $21, $8d, $28, $85, $26, $81, $28, $85, $25, $89, $23, $85, $25, $85, $1e
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song0ref1467
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song0ref1467
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song0ref1467
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song0ref1467
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e
	.byte $41, $32
	.word @song0ref1467
	.byte $41, $35
	.word @song0ref1405
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $00, $81, $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $78, $00, $8d, $8a
@song0ref1621:
	.byte $23, $85, $21, $81, $23, $85, $1e, $89, $1c, $85, $1e, $95, $26, $85, $25, $81, $26, $85, $23, $89, $21, $85, $23, $95
	.byte $26, $85, $25, $81, $21, $85, $1a, $89, $19, $85, $1a, $95, $1f, $85, $1e, $81, $1f, $85, $1e, $89, $1c, $85, $1e, $85
	.byte $8f, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26
	.byte $95, $2a, $85, $28, $81, $2a, $85, $23, $89, $21, $85, $23, $95, $28, $85, $26, $81, $28, $85, $26, $89, $25, $85, $26
	.byte $85, $00, $8d
	.byte $41, $1e
	.word @song0ref1621
@song0ref1723:
	.byte $1e, $89, $1c, $85, $1e, $95, $1f, $85, $1e, $81, $1f, $89, $1e, $85, $1c, $85, $1e, $85, $00, $8d, $2a, $85, $28, $81
	.byte $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81, $2a, $85, $26, $89, $25, $85, $26, $95, $2a, $85, $28, $81
	.byte $26, $85, $21, $89, $1f, $85, $1c, $95, $26, $85, $25, $81, $28, $85, $26, $89, $25, $85, $26, $85, $00, $8d
	.byte $41, $1e
	.word @song0ref1621
	.byte $41, $46
	.word @song0ref1723
	.byte $41, $1e
	.word @song0ref1621
	.byte $41, $46
	.word @song0ref1723
	.byte $41, $1e
	.word @song0ref1621
	.byte $41, $46
	.word @song0ref1723
	.byte $41, $1e
	.word @song0ref1621
	.byte $41, $46
	.word @song0ref1723
	.byte $41, $1e
	.word @song0ref1621
	.byte $41, $45
	.word @song0ref1723
	.byte $81, $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $76, $00, $8d
	.byte $41, $6c
	.word @song0ref1361
	.byte $00, $8d
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $8f
	.byte $41, $2b
	.word @song0ref1474
	.byte $8d, $28, $85, $26, $81, $28, $85, $26, $89, $8b
	.byte $41, $28
	.word @song0ref1418
	.byte $21, $85, $1e, $8d, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $00, $81, $42
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
@song0ref2040:
	.byte $87, $00, $9d
@song0ref2043:
	.byte $79, $88, $23, $81, $77, $23, $85, $79, $23, $81, $77, $23, $85, $23, $81, $74, $23, $85, $75, $23, $81, $73, $23, $89
	.byte $00, $a9, $79, $21, $81, $75, $21, $85, $79, $21, $81, $77, $21, $81, $21, $85, $75, $21, $81, $21, $85, $74, $21, $81
	.byte $21, $89, $79, $86, $1e, $89, $77, $1e, $89, $75, $1e, $89, $74, $1e, $89, $00, $8d, $a7
	.byte $41, $29
	.word @song0ref2043
	.byte $81, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81
	.byte $41, $32
	.word @song0ref2040
	.byte $41, $29
	.word @song0ref2043
	.byte $81, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $81, $87, $79
@song0ref2142:
	.byte $25, $85, $26, $81, $25, $85, $26, $89, $1e, $81, $1e, $81, $25, $85, $26, $81, $26, $81, $25, $89, $23, $85, $1f, $85
	.byte $1e, $81, $1f, $a5, $23, $85, $25, $81, $23, $85, $25, $89, $1c, $81, $1c, $81, $23, $85, $25, $81, $25, $81, $23, $89
	.byte $22, $85, $1e, $85, $1c, $81, $1e, $85, $1e, $81, $1e, $81, $23, $85, $25, $81, $26, $81, $87
@song0ref2209:
	.byte $28, $85, $2a, $81, $28, $85, $2a, $89, $23, $81, $23, $81, $2a, $85, $2d, $81, $2d, $81, $2d, $85, $2d, $81, $2b, $85
	.byte $2b, $85, $2a, $81, $2b, $9d, $26, $81, $25, $81, $26, $85, $28, $85, $21, $85, $28, $85, $21, $85, $28, $85, $2b, $81
	.byte $2b, $81, $2b, $89, $2a, $85, $2a, $85, $28, $81, $2a, $85, $21, $85, $26, $85, $25, $81, $23, $81, $87
@song0ref2278:
	.byte $31, $85, $32, $81, $31, $85, $32, $89, $2a, $81, $2a, $81, $31, $85, $32, $81, $32, $81, $31, $89, $2f, $85, $2b, $85
	.byte $2a, $81, $2b, $a5, $2f, $85, $31, $81, $2f, $85, $31, $89, $28, $81, $28, $81, $2f, $85, $31, $81, $31, $81, $2f, $89
	.byte $2e, $85, $2a, $85, $28, $81, $2a, $85, $2a, $81, $2a, $81, $2f, $85, $31, $81, $32, $81, $87
@song0ref2345:
	.byte $34, $85, $36, $81, $34, $85, $36, $89, $2f, $81, $2f, $81, $36, $85, $39, $81, $39, $81, $39, $85, $39, $81, $37, $85
	.byte $37, $85, $36, $81, $37, $9d, $32, $81, $31, $81, $32, $85, $34, $85, $2d, $85, $34, $85, $2d, $85, $34, $85, $37, $81
	.byte $37, $81, $37, $89, $36, $85, $36, $85, $34, $81, $36, $9d, $00, $81, $42
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
	.byte $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $b7, $79, $86
@song0ref2427:
	.byte $2d, $81, $2f, $85, $77, $2d, $81, $2f, $85, $75, $2d, $81, $2f, $85, $74, $2d, $81, $2f, $a9, $75, $23, $81, $25, $85
	.byte $79, $23, $81, $25, $85, $77, $23, $81, $25, $85, $75, $23, $81, $25, $85, $74, $23, $81, $25, $85, $72, $23, $81, $25
	.byte $81, $79, $28, $85, $26, $81, $28, $85, $75, $26, $81, $28, $85, $72, $25, $81, $26, $81, $26, $81, $26, $81, $b7, $79
	.byte $41, $23
	.word @song0ref2427
	.byte $8d, $79, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $b7
	.byte $41, $3b
	.word @song0ref2427
	.byte $79
	.byte $41, $23
	.word @song0ref2427
	.byte $8d, $79, $2a, $85, $28, $81, $2e, $85, $2a, $89, $28, $85, $2a, $85, $8f, $75
	.byte $41, $41
	.word @song0ref2142
	.byte $89
	.byte $41, $43
	.word @song0ref2209
	.byte $89
	.byte $41, $41
	.word @song0ref2278
	.byte $89
	.byte $41, $3b
	.word @song0ref2345
	.byte $95, $00, $81, $42
	.word @song0ch13loop
@song1ch0:
	.byte $46, $0a
@song1ch0loop:
	.byte $9f, $9f, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $9f, $9f, $42
	.word @song1ch1loop
@song1ch4:
@song1ch4loop:
	.byte $03, $0e, $10, $11, $13, $01, $04, $05, $81, $0d, $07, $08, $09, $0a, $06, $0c, $01, $02, $0b, $0f, $00, $95, $42
	.word @song1ch4loop
