; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for PVZ Deplanted music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_pvz_deplanted_music4:=music_data_pvz_deplanted_music4

music_data_pvz_deplanted_music4:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : braniac maniac
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 163,136
; 01 : zen garden
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 163,136
; 02 : dpcm
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	;
	.word 307,256

.export music_data_pvz_deplanted_music4
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env14,@env12,@env13,@env0 ; 00 : blank
	.word @env3,@env2,@env13,@env0 ; 01 : 70. industrial snare (DMC)

@instruments_exp:
	.word @env10, @env12, @env0 ; 00 : 1. Piano (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env10, @env12, @env0 ; 01 : 28. organ (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env8, @env12, @env0 ; 02 : blank: epsm edition
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env10, @env12, @env0 ; 03 : 5. strings (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env10, @env12, @env0 ; 04 : 74. Analog Power (FM)
	.word @env12, @env12
	.byte $00, $02
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env6, @env12, @env25 ; 05 : 7. Harp (PSG)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env10, @env12, @env0 ; 06 : 27. sinewave (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env10, @env12, @env0 ; 07 : 54. vox (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env10, @env12, @env0 ; 08 : 8. Acoustic Bass (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env10, @env12, @env0 ; 09 : 73. guitar chunk (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10
	.word @env10, @env12, @env5 ; 0a : 3. Oboe (FM)
	.word @env19, @env12
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch11

@instrument_epsm_extra_patch0:
	.byte $3a,$c0,$01,$1f,$18,$04,$34,$00,$33,$1f,$00,$00,$f4,$00,$32,$1f,$04,$00,$b1,$00,$01,$1d,$0c,$00,$f7,$00,$1b,$25,$2c,$11,$00
@instrument_epsm_extra_patch1:
	.byte $07,$c0,$46,$1f,$10,$0c,$6a,$00,$73,$1f,$00,$04,$09,$00,$62,$1f,$00,$05,$0b,$00,$20,$1f,$04,$00,$f9,$00,$13,$1d,$16,$16,$00
@instrument_epsm_extra_patch2:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch3:
	.byte $24,$c0,$31,$13,$00,$04,$13,$00,$21,$10,$01,$04,$16,$00,$73,$14,$00,$04,$13,$00,$61,$0e,$00,$04,$26,$00,$21,$1c,$1d,$1b,$00
@instrument_epsm_extra_patch4:
	.byte $3c,$c0,$71,$1f,$00,$00,$00,$00,$71,$1f,$00,$00,$07,$00,$31,$1f,$00,$00,$00,$00,$31,$1f,$00,$00,$07,$00,$11,$11,$12,$17,$00
@instrument_epsm_extra_patch5:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch6:
	.byte $3e,$c0,$02,$1f,$00,$09,$0b,$00,$01,$1f,$00,$02,$0b,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$7f,$0e,$7f,$7f,$00
@instrument_epsm_extra_patch7:
	.byte $2e,$c0,$71,$1f,$00,$00,$05,$00,$71,$0d,$00,$00,$05,$00,$00,$1f,$00,$00,$05,$00,$31,$0a,$00,$00,$05,$00,$24,$1a,$7f,$1d,$00
@instrument_epsm_extra_patch9:
	.byte $1c,$c0,$00,$1f,$0f,$00,$27,$00,$01,$1f,$00,$00,$09,$00,$03,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$0a,$00,$15,$13,$37,$13,$00
@instrument_epsm_extra_patch10:
	.byte $10,$c0,$05,$1f,$16,$00,$73,$00,$00,$1f,$00,$00,$03,$00,$03,$1f,$00,$00,$04,$00,$01,$1f,$10,$0e,$78,$00,$16,$1c,$1a,$0d,$00
@instrument_epsm_extra_patch11:
	.byte $2b,$c0,$21,$1f,$00,$00,$02,$00,$22,$1f,$00,$00,$02,$00,$00,$1f,$00,$00,$00,$00,$42,$10,$00,$00,$07,$00,$1e,$27,$7f,$15,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c5,$00,$01
@env2:
	.byte $c2,$c5,$00,$01
@env3:
	.byte $00,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env4:
	.byte $c6,$7f,$00,$00
@env5:
	.byte $00,$c0,$07,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$03
@env6:
	.byte $1b,$cf,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$02,$c5,$03,$c4,$03,$c3,$04,$c2,$c2,$c2,$00,$18,$c2,$02,$c1,$05,$c0,$08,$c0,$00,$21
@env7:
	.byte $b8,$be,$00,$01
@env8:
	.byte $04,$cf,$00,$01,$ca,$c5,$c0,$00,$06
@env9:
	.byte $00,$cf,$c6,$c2,$c0,$00,$04
@env10:
	.byte $00,$cf,$7f,$00,$02
@env11:
	.byte $ca,$7f,$00,$00
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $04,$cf,$00,$01,$c0,$00,$04
@env15:
	.byte $c1,$7f,$00,$00
@env16:
	.byte $c0,$c5,$00,$01
@env17:
	.byte $00,$cf,$c8,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env18:
	.byte $00,$cf,$cc,$c9,$c6,$c5,$c3,$c1,$c0,$00,$08
@env19:
	.byte $c8,$7f,$00,$00
@env20:
	.byte $c9,$d1,$00,$01
@env21:
	.byte $00,$cf,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env22:
	.byte $00,$c4,$c3,$c2,$c1,$c1,$c0,$00,$06
@env23:
	.byte $00,$cb,$c6,$c3,$c2,$c1,$c0,$00,$06
@env24:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env25:
	.byte $00,$bf,$c0,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0f,$40,$08 ; 00 B3 - industrial bass (Pitch:15)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$11,$0f,$40,$07 ; 01 bongos - C5 (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0f,$40,$07 ; 02 bongos - D5 (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$1b,$0f,$40,$07 ; 03 bongos - Db5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3d,$0f,$40,$07 ; 04 bongos - E5 (Pitch:15)
	.byte $16+.lobyte(FAMISTUDIO_DPCM_PTR),$23,$0f,$40,$07 ; 05 bongos - Eb5 (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$40,$08 ; 06 C3 - smash bass drum (Pitch:15)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$08,$0f,$40,$08 ; 07 C6 - plink (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$2e,$0f,$40,$08 ; 08 D4 - metal light (Pitch:15)
	.byte $6c+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40,$08 ; 09 Db6 - bonk3 (Pitch:15)
	.byte $2b+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0f,$40,$07 ; 0a dice (Pitch:15)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$07 ; 0b dice2 (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$0f,$40,$07 ; 0c E4 - metal loud (Pitch:15)
	.byte $71+.lobyte(FAMISTUDIO_DPCM_PTR),$16,$0f,$40,$08 ; 0d E6 - bonk4 (Pitch:15)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0e,$40,$08 ; 0e Eb6 - bonk (Pitch:14)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0f,$40,$08 ; 0f Eb6 - bonk (Pitch:15)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$04 ; 10 evillaugh0 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 11 evillaugh1 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 12 evillaugh2 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 13 evillaugh3 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 14 evillaugh4 (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$9e,$0f,$40,$08 ; 15 F4 - oil drum snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$3e,$02 ; 16 finalfanfare0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$38,$02 ; 17 finalfanfare1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$58,$03 ; 18 finalfanfare2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 19 finalfanfare3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e9,$0f,$4c,$04 ; 1a finalfanfare4 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$50,$0f,$40,$01 ; 1b industrial snare (Pitch:15)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40,$09 ; 1c laser dabs (Pitch:15)
	.byte $27+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 1d lightfill1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1e lightfill2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1f lightfill3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0b ; 20 lightfill4 (Pitch:15)
	.byte $19+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$09 ; 21 scratch standard (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0f,$40,$09 ; 22 snarish drum (Pitch:15)
	.byte $42+.lobyte(FAMISTUDIO_DPCM_PTR),$88,$0d,$40,$07 ; 23 sunflower (Pitch:13)
	.byte $3f+.lobyte(FAMISTUDIO_DPCM_PTR),$0a,$0f,$40,$07 ; 24 tennis (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 25 winmusic0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 26 winmusic1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 27 winmusic2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$97,$0f,$40,$01 ; 28 winmusic3 (Pitch:15)

@song0ch0:
	.byte $46, $02
@song0ch0loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $72, $4f, $02, $80, $23, $bd, $00, $bd
	.byte $23, $9d, $1e, $9d, $00, $bd, $23, $bd, $00, $bd, $1c, $9d, $17, $9d, $15, $bd, $20, $bd, $71, $af, $7f, $00, $8d, $ff
	.byte $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $72, $4f, $02, $80, $20, $bd, $00, $bd
	.byte $20, $9d, $1b, $dd, $20, $bd, $00, $bd, $19, $9d, $1b, $9d, $19, $bd, $1b, $bd, $71, $af, $7f, $00, $8d, $ff, $ff, $ff
	.byte $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $80, $2a, $83, $00, $2a, $85, $00, $85, $2a, $85, $00, $85
	.byte $2a, $81, $00, $89, $2a, $00, $83, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ff, $8f, $82, $3c, $95, $00, $85, $3c
@song0ref169:
	.byte $8d, $00, $ff, $bd
@song0ref173:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $8f, $1c, $95, $00, $85, $1c
	.byte $41, $19
	.word @song0ref169
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $7f, $8a, $31, $8d, $7d, $31, $8d, $7b, $31, $8d, $7f, $00
	.byte $8d, $ff, $ff, $ff, $ff
@song0ref242:
	.byte $25, $8d, $28, $8d, $2c, $8d, $2f, $8d, $23, $8d, $27, $8d, $2c, $8d, $2f, $8d, $25, $8d, $25, $8d, $27, $8d, $2a, $8d
	.byte $2f, $8d, $7a, $2f, $8d, $00, $9d, $7f
	.byte $41, $16
	.word @song0ref242
	.byte $27, $8d, $28, $8d, $7a, $28, $8d, $00, $9d, $7f, $2c, $8d, $7a, $2c, $8d, $7f, $27, $8d, $7a, $27, $8d, $7f, $2c, $8d
	.byte $7a, $2c, $8d, $7f, $20, $8d, $7a, $20, $8d, $00, $ff, $ff, $ff, $fd, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $7d, $82, $2a, $bd, $00, $ff, $c5, $78, $8a, $31, $8d, $31, $8d, $31
	.byte $8d, $00, $85, $ff, $ff, $ff, $ff, $87, $7a
	.byte $41, $1a
	.word @song0ref242
	.byte $75, $2f, $8d, $00, $9d, $7a
	.byte $41, $16
	.word @song0ref242
	.byte $27, $8d, $28, $8d, $75, $28, $8d, $00, $95, $87, $7a, $2c, $8d, $75, $2c, $8d, $7a, $27, $8d, $75, $27, $8d, $7a, $2c
	.byte $8d, $75, $2c, $8d, $7a, $20, $8d, $75, $20, $85, $87, $00, $ff, $ff, $ff, $f5, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $7a, $84, $25, $bd, $2c, $bd, $25, $9d
	.byte $00, $dd, $25, $bd, $2c, $bd, $00, $fd, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch7loop
@song0ch8:
@song0ch8loop:
	.byte $7b, $80
@song0ref451:
	.byte $31, $85, $36, $85, $3b, $85, $38, $85, $00, $81, $3d, $85, $38, $85, $36, $89, $31, $85, $36, $85, $3b, $85, $38, $8d
	.byte $36, $85, $3b, $85, $38, $85
	.byte $41, $1e
	.word @song0ref451
	.byte $41, $1e
	.word @song0ref451
	.byte $41, $1e
	.word @song0ref451
	.byte $7c
	.byte $41, $1e
	.word @song0ref451
	.byte $41, $1e
	.word @song0ref451
	.byte $41, $1e
	.word @song0ref451
	.byte $41, $17
	.word @song0ref451
	.byte $a5
@song0ref504:
	.byte $31, $81, $3d, $81, $36, $81, $38, $81, $3b, $81, $36, $81, $38, $81, $3d, $85, $3d, $81, $36, $81, $38, $81, $3b, $81
	.byte $36, $81, $38, $85
	.byte $41, $1b
	.word @song0ref504
@song0ref535:
	.byte $81, $3b, $81, $2d, $81, $34, $81, $39, $81, $2d, $81, $34, $81, $39, $81, $34, $85, $2f, $81, $36, $81, $3b, $81, $2f
	.byte $81, $36, $81, $3b, $81, $2f, $85
@song0ref566:
	.byte $2a, $81, $2f, $81, $31, $81, $36, $81, $2a, $81, $2f, $81, $31, $81, $36, $81, $2a, $81, $2e, $81, $31, $81, $36, $81
	.byte $3a, $81, $36, $81, $31, $81, $2e, $81
	.byte $41, $1c
	.word @song0ref504
	.byte $41, $1b
	.word @song0ref504
	.byte $41, $1f
	.word @song0ref535
	.byte $51, $ff, $70
	.byte $41, $20
	.word @song0ref566
	.byte $7c, $00, $ff, $fd, $38, $85, $31, $85, $34, $85, $38, $85, $36, $85, $2f, $89, $2f, $85, $36, $85, $31, $89, $34, $85
	.byte $38, $85, $34, $85, $2c, $85, $33, $85, $2f, $85, $38, $85, $31, $85, $34, $85, $38, $85, $36, $85, $2f, $89, $2f, $85
	.byte $36, $85, $33, $8d, $31, $89, $31, $89, $31, $89, $31, $85, $28, $91, $21, $99, $21, $85, $25, $85, $2a, $9d, $1b, $9d
	.byte $1e, $9d, $27, $9d, $1c, $91, $1c, $8d, $1c, $89, $20, $8d, $28, $91, $21, $99, $21, $85, $25, $85, $2a, $9d, $27, $ad
	.byte $25, $9d, $27, $cd, $97, $20, $9d, $25, $c5
@song0ref718:
	.byte $31, $89, $31, $89, $31, $85, $33, $95, $36, $85, $34, $95, $31, $95, $2c, $8d, $31, $89, $31, $89, $31, $85, $33, $89
	.byte $33, $89, $33, $85, $34, $89, $34, $89, $38, $85, $34, $89, $34, $89, $31, $85
	.byte $41, $28
	.word @song0ref718
	.byte $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $7b, $83, $80
@song0ref768:
	.byte $3d, $85, $38, $85, $36, $85, $3d, $89, $36, $85, $3b, $85, $38, $89, $3d, $85, $38, $85, $36, $85, $3d, $85, $3d, $85
	.byte $38, $85, $36, $85, $3b, $85
	.byte $41, $1e
	.word @song0ref768
	.byte $41, $1e
	.word @song0ref768
	.byte $41, $1d
	.word @song0ref768
	.byte $81, $83
	.byte $41, $1e
	.word @song0ref768
	.byte $41, $1e
	.word @song0ref768
	.byte $41, $1e
	.word @song0ref768
	.byte $41, $15
	.word @song0ref768
	.byte $a1, $79, $82
@song0ref824:
	.byte $38, $8d, $5c, $8d, $00, $81, $36, $81, $34, $81, $36, $81, $33, $81, $34, $81, $33, $81, $2f, $81, $2c, $85, $31, $81
	.byte $5c, $81, $31, $81, $2f, $81, $5c, $81, $31, $8d, $5c, $89, $31, $81, $33, $81, $7c, $86, $2d, $9d, $2f, $9d, $79, $82
	.byte $2a, $bd
	.byte $41, $2c
	.word @song0ref824
	.byte $82, $31, $85, $5c, $85, $79, $31, $85, $5c, $85, $76, $31, $85, $5c, $85, $00, $8d, $7c, $ff, $ff, $83, $80, $34, $8d
	.byte $31, $8d, $33, $85, $36, $89, $33, $85, $34, $85, $2c, $89, $36, $8d, $31, $85, $34, $85, $31, $8d, $34, $8d, $31, $8d
	.byte $33, $85, $36, $89, $33, $85, $34, $85, $31, $b5, $00, $8d, $21, $89, $21, $95, $23, $85, $28, $91, $20, $9d, $20, $8d
	.byte $28, $bd, $2c, $8d, $17, $89, $1e, $89, $1e, $8d, $23, $9d, $21, $89, $21, $8d, $23, $85, $28, $91, $20, $9d, $20, $8d
	.byte $28, $9d, $2a, $9d, $2c, $8d, $21, $8d, $21, $8d, $21, $8d, $2c, $9d, $25, $9d, $2c, $bd, $00, $81
@song0ref993:
	.byte $2f, $8d, $2f, $2f, $83, $2f, $85, $31, $85, $33, $85, $34, $85, $33, $8d, $33, $99, $2f, $8d, $2f, $89, $2f, $8d, $2f
	.byte $2f, $83, $2f, $85, $31, $8d, $31, $85, $31, $85, $33, $8d, $36, $85, $36, $85, $33, $8d, $33, $85, $2f, $85
	.byte $41, $2d
	.word @song0ref993
	.byte $81, $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $00, $ff, $e9, $78
@song0ref1051:
	.byte $88
@song0ref1052:
	.byte $20, $81, $23, $81, $25, $81, $28, $81, $27, $81, $25, $81, $23, $81, $25, $81, $5c, $81, $00, $99
	.byte $41, $14
	.word @song0ref1052
@song0ref1075:
	.byte $20, $81, $5c, $81, $23, $81, $5c, $81, $25, $81, $5c, $81, $28, $81, $28, $81, $5c, $81, $2a, $81, $5c, $81, $2a, $81
	.byte $5c, $81, $28, $81, $2c, $81, $5c, $81, $2a, $81, $5c, $81, $28, $81, $5c, $81, $2a, $81, $5c, $81, $28, $81, $2c, $81
	.byte $5c, $81, $28, $81, $5c, $81, $25, $81, $5c, $81, $28, $81, $2c, $81, $5c, $81, $2c, $81, $28, $81, $5c, $81, $25, $81
	.byte $5c, $81, $23, $81, $5c, $81, $25, $81, $5c, $81, $00, $99
	.byte $41, $14
	.word @song0ref1052
	.byte $41, $53
	.word @song0ref1075
	.byte $ff, $ed, $7b, $82
@song0ref1169:
	.byte $25
@song0ref1170:
	.byte $8d, $5c, $8d, $00, $81
@song0ref1175:
	.byte $2a, $81, $28, $81, $2a, $81, $27, $81, $28, $81, $27, $81, $23, $81, $20, $85, $25, $81, $5c, $81, $25, $81, $23, $81
	.byte $5c, $81, $25, $8d, $5c, $89, $25, $81, $27, $81, $28, $85, $5c, $81, $2a, $85, $5c, $81, $2c, $85, $27, $85, $28, $81
	.byte $27, $85, $25, $81, $23, $85, $1e, $bd
	.byte $41, $3c
	.word @song0ref1169
	.byte $25, $85, $5c, $85, $79, $25, $85, $5c, $85, $76, $25, $85, $5c, $85, $00, $8d, $83, $78
@song0ref1252:
	.byte $88
@song0ref1253:
	.byte $25, $81, $23, $81, $5c, $81, $25, $81, $5c, $81, $23, $23, $25, $81, $23, $81, $27, $81, $25, $81, $5c, $81, $27, $81
	.byte $5c, $81, $28, $81, $2a, $81, $27, $81, $28, $81, $5c, $85, $27, $81, $5c, $85, $25, $81, $5c, $85, $00, $81, $23, $81
	.byte $5c, $81, $20, $81, $5c, $81, $23, $81, $5c, $81
	.byte $41, $1a
	.word @song0ref1253
@song0ref1314:
	.byte $25, $81, $27, $81, $25, $81, $28, $81, $27, $81, $5c, $81, $28, $81, $5c, $81, $2a, $81, $2c, $81, $2a, $81, $28, $81
	.byte $27, $81, $5c, $81, $28, $81, $5c, $81, $27, $81, $25, $81, $23, $81
	.byte $41, $3a
	.word @song0ref1253
	.byte $41, $1a
	.word @song0ref1253
	.byte $25, $81, $27, $81, $25, $81, $28, $81, $5c, $b5, $7a, $80, $2c, $a1, $2d, $99, $27, $dd, $7c, $2f, $9d, $7a, $27, $bd
	.byte $2c, $a1, $2d, $99, $27, $bd, $34, $9d, $36, $9d, $38, $bd, $00, $a9, $27, $d1, $00, $81, $88
@song0ref1401:
	.byte $31, $81, $38, $81, $31, $81, $36, $81, $31, $81, $38, $81, $31, $81, $5c, $81, $31, $81, $38, $81, $31, $81, $36, $81
	.byte $31, $81, $3b, $81, $39, $81, $38, $85, $5c, $81, $36, $85, $5c, $81, $34, $8d, $33, $85, $31, $85, $2f, $85, $5c, $81
	.byte $41, $1f
	.word @song0ref1401
	.byte $8d, $34, $8d, $33, $8d, $2f, $8d, $5c, $81
	.byte $41, $30
	.word @song0ref1401
	.byte $41, $1a
	.word @song0ref1401
	.byte $38, $81, $33, $81, $7f, $00, $81, $1b, $81, $5c, $81, $1b, $81, $5c, $81, $1e, $81, $20, $81, $1e, $81, $1c, $81, $1b
	.byte $81, $5c, $81, $1c, $81, $5c, $81, $1b, $81, $19, $85, $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
	.byte $00, $ff, $e1, $7e
	.byte $41, $14
	.word @song0ref1051
	.byte $41, $14
	.word @song0ref1052
	.byte $41, $54
	.word @song0ref1075
	.byte $41, $14
	.word @song0ref1052
	.byte $41, $53
	.word @song0ref1075
	.byte $ff, $f5, $77, $82, $2c
	.byte $41, $27
	.word @song0ref1170
	.byte $7c, $86, $28, $9d, $2a, $9d, $2f, $9d, $2e, $9d, $77, $82, $2c
	.byte $41, $27
	.word @song0ref1170
	.byte $7c, $86, $28, $9d, $2a, $9d, $00, $bd, $7e
	.byte $41, $3a
	.word @song0ref1252
	.byte $41, $1a
	.word @song0ref1253
	.byte $41, $26
	.word @song0ref1314
	.byte $41, $3a
	.word @song0ref1253
	.byte $41, $1a
	.word @song0ref1253
	.byte $25, $81, $27, $81, $25, $81, $28, $81, $5c, $b9, $7a, $80, $25, $a1, $31, $99, $23, $bd, $25, $9d, $2a, $9d, $23, $bd
	.byte $25, $a1, $31, $99, $23, $bd, $25, $9d, $27, $9d, $28, $ad, $36, $8d, $25, $bd, $27, $bd, $7e, $00, $81, $88
@song0ref1619:
	.byte $25, $81, $2c, $81, $25, $81, $2a, $81, $25, $81, $2c, $81, $25, $81, $5c, $81, $25, $81, $2c, $81, $25, $81, $2a, $81
	.byte $25, $81, $2f, $81, $2d, $81, $2c, $85, $5c, $81, $2a, $85, $5c, $81, $28, $8d, $27, $85, $25, $85, $23, $85, $5c, $81
	.byte $41, $1f
	.word @song0ref1619
	.byte $8d, $28, $8d, $27, $8d, $23, $8d, $5c, $81
	.byte $41, $30
	.word @song0ref1619
	.byte $41, $1a
	.word @song0ref1619
	.byte $2c, $81, $27, $81, $51, $ff, $80, $28, $b9, $83, $42
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $7f, $92
@song0ref1701:
	.byte $25, $85, $25, $85, $23, $89, $25, $85, $25, $81, $25, $85, $23, $8d, $25, $85, $25, $85, $23, $89, $25, $85, $25, $81
	.byte $25, $85, $23, $85, $28, $85
	.byte $41, $14
	.word @song0ref1701
	.byte $23, $a1
	.byte $41, $1e
	.word @song0ref1701
	.byte $41, $14
	.word @song0ref1701
	.byte $23, $a1
	.byte $41, $1e
	.word @song0ref1701
	.byte $41, $14
	.word @song0ref1701
	.byte $23, $a1
	.byte $41, $1e
	.word @song0ref1701
	.byte $41, $14
	.word @song0ref1701
	.byte $23, $a1
	.byte $41, $1e
	.word @song0ref1701
	.byte $21, $85, $21, $89, $21, $85, $21, $81, $23, $89, $23, $89, $23, $81, $23, $81, $23, $85, $23, $85, $2a, $89, $22, $85
	.byte $22, $81, $22, $85, $2a, $85, $22, $85
	.byte $41, $1e
	.word @song0ref1701
	.byte $21, $85, $21, $89, $21, $85, $21, $81, $23, $89, $23, $89, $23, $81, $23, $81, $51, $fe, $80, $23, $85, $23, $85, $2a
	.byte $89, $22, $85, $22, $81, $22, $85, $2a, $85, $22, $85, $7f
@song0ref1834:
	.byte $21, $85, $21, $89, $21, $85, $23, $85, $23, $81, $23, $8d, $23, $85, $25, $85, $25, $85, $23, $89, $25, $85, $25, $81
	.byte $25, $85, $23, $8d
	.byte $41, $1c
	.word @song0ref1834
	.byte $41, $1c
	.word @song0ref1834
@song0ref1868:
	.byte $21, $85, $21, $89, $21, $85, $23, $85, $23, $81, $23, $8d, $23, $85, $51, $ff, $80, $25, $85, $25, $85, $23, $89, $25
	.byte $85, $25, $81, $25, $85, $23, $89, $83, $7a, $80, $21, $ad, $7c, $36, $8d, $33, $89, $33, $8d, $2c, $9d, $33, $81, $7a
	.byte $21, $89, $7c, $33, $91, $7a, $23, $9d, $20, $bd, $21, $a9, $7c, $83, $36, $8d, $33, $89, $33, $8d, $2c, $9d, $33, $81
	.byte $7a, $21, $8d, $21, $8d, $23, $8d, $23, $8d, $25, $bd, $20, $bd, $24, $bd, $7f, $92
	.byte $41, $1c
	.word @song0ref1834
	.byte $41, $1c
	.word @song0ref1834
	.byte $41, $1c
	.word @song0ref1834
	.byte $41, $1d
	.word @song0ref1868
	.byte $42
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
	.byte $00, $ff, $fd, $7c, $90, $19, $bd, $1c, $bd, $1e, $bd, $21, $99, $23, $a1, $19, $bd, $1c, $bd, $1e, $bd, $21, $99, $23
	.byte $a1, $19, $bd, $00, $ff, $bd, $82, $2c, $8d, $5c, $8d, $00, $89, $77
	.byte $41, $1e
	.word @song0ref1175
	.byte $7c, $86, $25, $9d, $27, $9d, $82, $31, $bd, $2c, $8d, $5c, $8d, $00, $89, $77
	.byte $41, $1e
	.word @song0ref1175
	.byte $7c, $86, $25, $9d, $27, $9d, $00, $bd
@song0ref2041:
	.byte $7f, $00, $ff, $e1, $7c, $90, $14, $81, $19, $81, $1b, $81, $1c, $81, $1e, $81, $20, $81, $23, $81, $21, $9d, $23, $9d
	.byte $25, $bd, $21, $9d, $23, $9d, $25, $bd, $80, $38, $a1, $38, $91, $34, $8d, $34, $89, $2f, $89, $2f, $95, $31, $85, $34
	.byte $95, $31, $95, $2a, $cd, $38, $a1, $38, $91, $34, $8d, $34, $89, $2f, $89, $2f, $95, $31, $85, $7a, $1e, $9d, $20, $9d
	.byte $21, $bd, $38, $bd, $7f, $8c, $2c, $85, $33, $85, $2c, $85, $36, $85, $38, $85, $7a, $38, $85, $75, $38, $85, $72, $38
	.byte $85
	.byte $41, $1d
	.word @song0ref2041
	.byte $42
	.word @song0ch13loop
@song0ch14:
@song0ch14loop:
	.byte $ff, $ff, $84
@song0ref2148:
	.byte $25, $81, $00
@song0ref2151:
	.byte $85, $25, $81, $00, $95, $25, $81, $00, $91, $25, $81, $00, $85, $25, $81, $00, $95, $25, $81, $00, $91
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $13
	.word @song0ref2148
	.byte $ad
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $13
	.word @song0ref2148
	.byte $ad
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $13
	.word @song0ref2148
	.byte $ad
@song0ref2214:
	.byte $25, $81, $00, $91, $25, $81, $00, $a1, $25, $81, $00, $91, $25, $81, $00, $89, $25, $81, $00, $89, $25, $81, $00, $81
	.byte $25, $81, $00, $91, $25, $81, $00, $91, $25, $81, $00, $89, $25, $81, $00, $85, $25, $81, $00, $85, $25, $81, $00, $91
	.byte $25, $81, $00, $89
	.byte $41, $34
	.word @song0ref2214
	.byte $41, $1b
	.word @song0ref2214
	.byte $41, $15
	.word @song0ref2151
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $41, $18
	.word @song0ref2148
	.byte $42
	.word @song0ch14loop
@song0ch15:
@song0ch15loop:
	.byte $ff, $ff, $8f, $84
@song0ref2292:
	.byte $25, $81, $00
@song0ref2295:
	.byte $99, $25, $81, $00, $99, $25, $81, $00, $99, $25, $81, $00, $99, $25, $81, $00, $99, $25, $81, $00, $99, $25, $81, $00
	.byte $99, $25, $81, $00, $89, $8f
	.byte $41, $1f
	.word @song0ref2292
	.byte $41, $1c
	.word @song0ref2295
	.byte $a9, $8f
	.byte $41, $1f
	.word @song0ref2292
	.byte $41, $18
	.word @song0ref2295
	.byte $c9, $8f
	.byte $41, $1f
	.word @song0ref2292
	.byte $41, $18
	.word @song0ref2295
	.byte $c9, $7f, $9f
@song0ref2350:
	.byte $25, $81, $00, $b9, $25, $81, $00, $b9, $25, $81, $00, $b9, $25, $81, $00, $b9, $25, $81, $00, $b9, $25, $81, $00, $b9
	.byte $25, $81, $00, $b9, $25, $81, $00, $99, $9f, $25, $81, $00, $b9, $25, $81, $00, $99, $8f
	.byte $41, $1f
	.word @song0ref2292
	.byte $41, $1c
	.word @song0ref2295
	.byte $99, $25, $81, $00, $89, $42
	.word @song0ch15loop
@song0ch16:
@song0ch16loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $75, $9f, $84
	.byte $41, $29
	.word @song0ref2350
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch16loop
@song0ch17:
@song0ch17loop:
@song0ref2437:
	.byte $ff, $ff, $7c, $84
@song0ref2441:
	.byte $25, $81, $00, $81
@song0ref2445:
	.byte $79
@song0ref2446:
	.byte $25, $81, $25, $81, $7c, $25, $81, $00, $81, $79, $25, $81, $25, $81, $7c, $25, $81, $00, $81, $79, $25, $81, $25, $81
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c, $25, $81, $00, $81, $79, $25, $81, $7c, $00, $a1
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7b, $25, $81, $00, $81, $77, $25, $81, $25, $81, $79, $25, $81, $00, $81, $75
	.byte $41, $14
	.word @song0ref2446
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
@song0ref2631:
	.byte $7c, $25, $81, $00, $81, $79, $25, $81, $25, $81
@song0ref2641:
	.byte $7b, $25, $81, $00, $81, $77, $25, $81, $25, $81, $79, $25, $81, $00, $81, $75
@song0ref2657:
	.byte $25, $81
@song0ref2659:
	.byte $25
@song0ref2660:
	.byte $81, $7c, $25, $81, $00, $81, $79, $25, $81, $00
@song0ref2670:
	.byte $81, $7c, $25, $81, $00, $81, $79, $25, $81, $00
@song0ref2680:
	.byte $81, $7c, $25, $81, $00, $81, $79, $25, $81, $25, $81, $7c, $25, $81, $00, $81, $79, $25, $81, $00, $81, $7c, $25, $81
	.byte $00, $81, $79
	.byte $41, $1a
	.word @song0ref2657
	.byte $00
	.byte $41, $25
	.word @song0ref2660
	.byte $79, $25, $81, $25
	.byte $41, $13
	.word @song0ref2670
	.byte $79, $25, $81, $7c, $25, $81, $79
	.byte $41, $26
	.word @song0ref2659
	.byte $79
	.byte $41, $1a
	.word @song0ref2657
	.byte $00, $81, $7c, $25, $81, $00, $81, $79, $25, $81, $00, $81, $7c, $25, $81, $79, $25, $81, $7c, $25, $81, $79, $25
	.byte $41, $15
	.word @song0ref2680
	.byte $79, $25, $81, $00, $81, $7c, $25, $81, $79, $25, $81, $7c, $25, $81, $79, $25
	.byte $41, $15
	.word @song0ref2680
	.byte $79, $25, $81, $00, $81, $7c, $25, $81, $79, $25, $81, $7c, $25, $81, $79, $25
	.byte $41, $15
	.word @song0ref2680
	.byte $79, $25, $81, $00, $81, $7c, $25, $81, $79, $25, $81, $7c, $25, $81, $79, $25
	.byte $41, $15
	.word @song0ref2680
	.byte $41, $14
	.word @song0ref2445
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7b, $25, $81, $00, $81, $77, $25, $81, $25, $81, $79, $25, $81, $00, $81, $75, $25, $81, $25, $81, $42
	.word @song0ch17loop
@song0ch18:
@song0ch18loop:
	.byte $41, $15
	.word @song0ref173
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch18loop
@song0ch19:
@song0ch19loop:
	.byte $41, $1a
	.word @song0ref2437
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c, $25, $81, $00, $81, $79, $25, $81, $7c, $00, $a1
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $41, $16
	.word @song0ref2641
	.byte $25, $81, $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c, $25, $81, $00, $81, $79, $25, $81, $25, $81
	.byte $41, $18
	.word @song0ref2631
	.byte $7f, $00, $9d
	.byte $41, $29
	.word @song0ref2350
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7c
	.byte $41, $18
	.word @song0ref2441
	.byte $7b, $25, $81, $00, $81, $77, $25, $81, $25, $81, $79, $25, $81, $00, $81, $75, $25, $81, $25, $81, $42
	.word @song0ch19loop
@song1ch0:
	.byte $46, $02
@song1ch0loop:
@song1ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch4:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
	.byte $41, $0f
	.word @song1ref4
	.byte $42
	.word @song1ch1loop
@song1ch5:
@song1ch5loop:
	.byte $7e, $8a
@song1ref41:
	.byte $25, $9d, $30, $9d, $77, $2c, $8d, $2c, $9d, $2c, $8d, $7e, $25, $9d, $30, $9d, $77, $2c, $8d, $2c, $9d, $2c, $8d, $7e
	.byte $41, $14
	.word @song1ref41
	.byte $7e
	.byte $41, $14
	.word @song1ref41
	.byte $7e
	.byte $41, $14
	.word @song1ref41
	.byte $7e
	.byte $41, $14
	.word @song1ref41
@song1ref80:
	.byte $7e, $22, $8d, $30, $95, $77, $31, $95, $7e, $20, $8d, $2c, $95, $77, $30, $95, $7e, $2a, $8d, $31, $95, $2c, $95, $2a
	.byte $8d, $2e, $9d, $76, $2e, $8d
	.byte $41, $0c
	.word @song1ref80
	.byte $7e
	.byte $41, $14
	.word @song1ref41
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $7e, $87, $00, $85, $8a
@song1ref126:
	.byte $31, $9d, $2c, $cd, $8f, $31, $9d, $2c, $cd, $87, $00, $85
	.byte $41, $0c
	.word @song1ref126
	.byte $41, $0c
	.word @song1ref126
	.byte $41, $0c
	.word @song1ref126
	.byte $31, $9d, $2c, $cd, $8f, $31, $9d, $2c, $cd, $87
@song1ref157:
	.byte $29, $8d, $31, $9d, $76, $31, $85, $00, $85, $7e, $27, $8d, $30, $9d, $76, $30, $85, $87, $7e, $2e, $8d, $30, $9d, $29
	.byte $8d, $25, $95, $77, $2e, $9d, $00, $85, $7e
	.byte $41, $0e
	.word @song1ref157
	.byte $7e, $87, $00, $85, $31, $9d, $2c, $cd, $8f, $31, $9d, $2c, $cd, $42
	.word @song1ch6loop
@song1ch7:
@song1ch7loop:
	.byte $ff, $7d, $8f, $8a
@song1ref214:
	.byte $35, $8d, $33, $8d, $30, $cd, $00, $fd, $8f, $35, $8d, $33, $8d, $30, $cd, $00, $fd, $8f
	.byte $41, $12
	.word @song1ref214
	.byte $35, $8d, $33, $8d, $30, $cd, $00, $fd, $ff, $ff, $ff, $8f, $35, $8d, $33, $8d, $30, $cd, $42
	.word @song1ch7loop
@song1ch8:
@song1ch8loop:
@song1ref257:
	.byte $7a
@song1ref258:
	.byte $80
@song1ref259:
	.byte $3d, $81, $5c, $99, $38, $81, $5c, $99, $40, $4e, $81, $5c, $99, $40, $4d, $81, $5c, $99
	.byte $41, $10
	.word @song1ref259
	.byte $00, $fd, $ff, $ff, $ff, $7b, $94
@song1ref287:
	.byte $35, $bd, $5c, $9d, $36, $8d, $5c, $8d, $35, $bd, $5c, $bd
	.byte $41, $0c
	.word @song1ref287
	.byte $7c, $8e, $31, $bd, $5c, $bd, $2e, $bd, $5c, $bd, $35, $bd, $5c, $9d, $30, $9d
	.byte $41, $10
	.word @song1ref257
	.byte $41, $10
	.word @song1ref259
	.byte $42
	.word @song1ch8loop
@song1ch9:
@song1ch9loop:
	.byte $87, $76
	.byte $41, $0f
	.word @song1ref258
	.byte $91, $87
	.byte $41, $0f
	.word @song1ref259
	.byte $91, $87, $00, $f5, $ff, $ff, $ff, $7b, $cf, $94, $33, $8d, $5c, $8d, $35, $8d, $5c, $fd, $cf, $33, $8d, $5c, $8d, $38
	.byte $8d, $5c, $fd, $7c, $bf, $8e, $30, $bd, $5c, $bd, $00, $bd, $bf, $33, $9d, $5c, $9d, $00, $85, $76
	.byte $41, $0f
	.word @song1ref258
	.byte $91, $87
	.byte $41, $0f
	.word @song1ref259
	.byte $91, $42
	.word @song1ch9loop
@song1ch10:
@song1ch10loop:
	.byte $7e
@song1ref396:
	.byte $8c
@song1ref397:
	.byte $31, $81, $5c, $81, $2c, $81, $5c, $89, $2a, $81, $5c, $89, $29, $81, $5c, $89, $25, $81, $5c, $81, $27, $81, $5c, $81
	.byte $20, $81, $5c, $81, $2c, $81, $5c, $81, $29, $81, $5c, $a1
	.byte $41, $24
	.word @song1ref397
	.byte $00, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $24
	.word @song1ref397
	.byte $41, $24
	.word @song1ref397
	.byte $42
	.word @song1ch10loop
@song1ch11:
@song1ch11loop:
	.byte $8b, $77
	.byte $41, $0f
	.word @song1ref258
	.byte $8d, $8b
	.byte $41, $0f
	.word @song1ref259
	.byte $8d, $8b, $00, $f1, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $8b
	.byte $41, $0f
	.word @song1ref259
	.byte $8d, $8b
	.byte $41, $0f
	.word @song1ref259
	.byte $8d, $42
	.word @song1ch11loop
@song1ch12:
@song1ch12loop:
	.byte $7a, $8e, $31, $bd, $7c, $31, $bd, $7a, $31, $bd, $7c, $31, $bd, $77, $8c
@song1ref511:
	.byte $35, $81, $5c, $81
@song1ref515:
	.byte $25, $81, $5c, $81, $2c, $81, $5c, $c9, $31, $81, $5c, $89, $30, $81, $5c, $81, $27, $81, $5c, $81, $29, $81, $5c, $81
	.byte $25, $81, $5c, $81, $2c, $81, $5c, $c9, $35, $81, $5c, $89, $33, $81, $5c, $81, $36, $81, $5c, $81
	.byte $41, $30
	.word @song1ref511
	.byte $41, $30
	.word @song1ref511
	.byte $41, $30
	.word @song1ref511
	.byte $87, $31, $81, $5c, $b9, $30, $81, $5c, $99, $2c, $81, $5c, $91, $87, $2e, $81, $5c, $f1, $87, $31, $81, $5c, $b9, $33
	.byte $81, $5c, $99, $30, $81, $5c, $91, $7a, $8e, $31, $bd, $7c, $31, $bd, $7a, $31, $bd, $7c, $31, $bd, $42
	.word @song1ch12loop
@song1ch13:
@song1ch13loop:
	.byte $87, $77
	.byte $41, $23
	.word @song1ref396
	.byte $99, $87
	.byte $41, $23
	.word @song1ref397
	.byte $99, $7e
	.byte $41, $2c
	.word @song1ref515
	.byte $41, $30
	.word @song1ref511
	.byte $41, $30
	.word @song1ref511
	.byte $41, $30
	.word @song1ref511
	.byte $35, $81, $5c, $81, $31, $81, $5c, $b9, $30, $81, $5c, $99, $2c, $81, $5c, $99, $2e, $81, $5c, $f9, $31, $81, $5c, $b9
	.byte $33, $81, $5c, $99, $30, $81, $5c, $99, $00, $85, $77
	.byte $41, $23
	.word @song1ref397
	.byte $99, $87
	.byte $41, $23
	.word @song1ref397
	.byte $99, $42
	.word @song1ch13loop
@song2ch0:
	.byte $46, $0a
@song2ch0loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch0loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $26, $27, $28, $29, $17, $18, $19, $1a, $1b, $11, $12, $13, $14, $15, $00, $1e, $1f, $20, $21, $00, $8f, $1c, $00, $83
	.byte $0b, $0c, $25, $05, $03, $06, $02, $04, $07, $16, $01, $0d, $09, $00, $83, $24, $00, $83, $10, $0f, $0a, $0e, $08, $00
	.byte $83, $23, $1d, $00, $81, $22, $00, $ff, $ff, $fb, $42
	.word @song2ch4loop
