// Generated by export.py using data in metadata.json

#if !__VS_SYSTEM

banked(sound_test_bank.musictext.data.0) const char musicSoundTestString00[11] = "Crazy Dave";
banked(sound_test_bank.musictext.data.1) const char musicSoundTestString01[18] = "Choose Your Seeds";
banked(sound_test_bank.musictext.data.2) const char musicSoundTestString02[10] = "Grasswalk";
banked(sound_test_bank.musictext.data.3) const char musicSoundTestString03[11] = "Moongrains";
banked(sound_test_bank.musictext.data.4) const char musicSoundTestString04[14] = "Watery Graves";
banked(sound_test_bank.musictext.data.5) const char musicSoundTestString05[14] = "Rigor Mormist";
banked(sound_test_bank.musictext.data.6) const char musicSoundTestString06[15] = "Graze the Roof";
banked(sound_test_bank.musictext.data.7) const char musicSoundTestString07[16] = "Ultimate Battle";
banked(sound_test_bank.musictext.data.8) const char musicSoundTestString08[15] = "Braniac Maniac";
banked(sound_test_bank.musictext.data.9) const char musicSoundTestString09[ 9] = "Loonboon";
banked(sound_test_bank.musictext.data.10) const char musicSoundTestString0A[10] = "Celebrawl";
banked(sound_test_bank.musictext.data.11) const char musicSoundTestString0B[11] = "Zen Garden";
banked(sound_test_bank.musictext.data.12) const char musicSoundTestString0C[21] = "Zombies On Your Lawn";
banked(sound_test_bank.musictext.data.13) const char musicSoundTestString0D[13] = "winmusic.ogg";
banked(sound_test_bank.musictext.data.14) const char musicSoundTestString0E[14] = "losemusic.ogg";
banked(sound_test_bank.musictext.data.15) const char musicSoundTestString0F[17] = "finalfanfare.ogg";
banked(sound_test_bank.musictext.data.16) const char musicSoundTestString10[16] = "LAURA SHIGIHARA";


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsUpper[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsLower[] = {
	musicSoundTestString00,
	musicSoundTestString01,
	musicSoundTestString02,
	musicSoundTestString03,
	musicSoundTestString04,
	musicSoundTestString05,
	musicSoundTestString06,
	musicSoundTestString07,
	musicSoundTestString08,
	musicSoundTestString09,
	musicSoundTestString0A,
	musicSoundTestString0B,
	musicSoundTestString0C,
	musicSoundTestString0D,
	musicSoundTestString0E,
	musicSoundTestString0F,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsOriginalArtist[] = {
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
	musicSoundTestString10,
};


#else

const char* const xbgmtextsUpper[] = {};
const u8 xbgmtextsUpperSize[] = {};
const char* const xbgmtextsLower[] = {};
const u8 xbgmtextsLowerSize[] = {};
const char* const xbgmtextsOriginalArtist[] = {};
const u8 xbgmtextsOriginalArtistSize[] = {};

#endif




#if !__VS_SYSTEM

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
	song_crazy_dave,
	song_choose_your_seeds,
	song_grasswalk,
	song_moongrains,
	song_watery_graves,
	song_rigor_mormist,
	song_graze_the_roof,
	song_ultimate_battle,
	song_braniac_maniac,
	song_loonboon,
	song_celebrawl,
	song_zen_garden,
	song_me_when_theres_zombies_on_my_lawn,
	song_win_music_dot_oh_gee_gee,
	song_adventure_start,
	song_final_fanfare_dot_oh_gee_gee,
};

#else

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
};

#endif
