; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for PVZ Deplanted music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_pvz_deplanted_music2:=music_data_pvz_deplanted_music2

music_data_pvz_deplanted_music2:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : grasswalk
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	;
	.word 235,196
; 01 : graze the roof
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	;
	.word 163,136
; 02 : dpcm
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	;
	; FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	;
	; FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	;
	; FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	;
	.word 307,256

.export music_data_pvz_deplanted_music2
.global FAMISTUDIO_DPCM_PTR

@instruments:

@instruments_exp:
	.word @env10, @env13, @env0 ; 00 : 1. Piano (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env10, @env13, @env11 ; 01 : 4. Cello (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env10, @env13, @env0 ; 02 : 5. strings (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env10, @env13, @env0 ; 03 : 2. pizzicato (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env8, @env13, @env0 ; 04 : blank: epsm edition
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env10, @env13, @env0 ; 05 : 54. vox (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env10, @env13, @env0 ; 06 : 27. sinewave (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env10, @env13, @env0 ; 07 : 78. mute guitar (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env10, @env13, @env0 ; 08 : 21. Pizzicato (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env6, @env13, @env25 ; 09 : 7. Harp (PSG)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env10, @env13, @env5 ; 0a : 3. Oboe (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10
	.word @env10, @env13, @env0 ; 0b : 76. cerebass (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch11
	.word @env10, @env13, @env0 ; 0c : 40. resobass (FM)
	.word @env19, @env13
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch12

@instrument_epsm_extra_patch0:
	.byte $3a,$c0,$01,$1f,$18,$04,$34,$00,$33,$1f,$00,$00,$f4,$00,$32,$1f,$04,$00,$b1,$00,$01,$1d,$0c,$00,$f7,$00,$1b,$25,$2c,$11,$00
@instrument_epsm_extra_patch1:
	.byte $2b,$c0,$30,$1f,$00,$00,$00,$00,$30,$1f,$00,$00,$00,$00,$03,$1f,$00,$00,$00,$00,$70,$0f,$00,$00,$07,$00,$20,$1b,$2e,$14,$00
@instrument_epsm_extra_patch2:
	.byte $24,$c0,$31,$13,$00,$04,$13,$00,$21,$10,$01,$04,$16,$00,$73,$14,$00,$04,$13,$00,$61,$0e,$00,$04,$26,$00,$21,$1c,$1d,$1b,$00
@instrument_epsm_extra_patch3:
	.byte $13,$c0,$72,$1f,$1b,$0a,$78,$00,$31,$1f,$1f,$06,$06,$00,$24,$1f,$15,$10,$78,$00,$11,$1f,$10,$0e,$38,$00,$25,$22,$15,$10,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $2e,$c0,$71,$1f,$00,$00,$05,$00,$71,$0d,$00,$00,$05,$00,$00,$1f,$00,$00,$05,$00,$31,$0a,$00,$00,$05,$00,$24,$1a,$7f,$1d,$00
@instrument_epsm_extra_patch6:
	.byte $3e,$c0,$02,$1f,$00,$09,$0b,$00,$01,$1f,$00,$02,$0b,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$7f,$0e,$7f,$7f,$00
@instrument_epsm_extra_patch7:
	.byte $3c,$c0,$00,$5f,$18,$0d,$90,$00,$00,$1f,$11,$0c,$77,$00,$00,$1f,$18,$00,$f7,$00,$00,$1f,$19,$0d,$97,$00,$00,$0d,$00,$0e,$00
@instrument_epsm_extra_patch8:
	.byte $13,$c0,$72,$1f,$16,$18,$48,$00,$31,$1f,$1f,$0d,$06,$00,$24,$1f,$15,$10,$48,$00,$11,$1f,$1f,$10,$09,$00,$10,$22,$17,$0e,$00
@instrument_epsm_extra_patch9:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch10:
	.byte $2b,$c0,$21,$1f,$00,$00,$02,$00,$22,$1f,$00,$00,$02,$00,$00,$1f,$00,$00,$00,$00,$42,$10,$00,$00,$07,$00,$1e,$27,$7f,$15,$00
@instrument_epsm_extra_patch11:
	.byte $33,$c0,$62,$1f,$00,$00,$07,$00,$60,$1f,$00,$0a,$07,$00,$23,$1f,$00,$00,$07,$00,$20,$1f,$09,$0e,$17,$00,$27,$19,$27,$14,$00
@instrument_epsm_extra_patch12:
	.byte $1a,$c0,$00,$1f,$14,$00,$90,$00,$00,$1f,$00,$08,$02,$00,$01,$1f,$00,$09,$07,$00,$00,$1f,$00,$0c,$07,$00,$00,$07,$28,$10,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c5,$00,$01
@env2:
	.byte $c2,$c5,$00,$01
@env3:
	.byte $00,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env4:
	.byte $c6,$7f,$00,$00
@env5:
	.byte $00,$c0,$07,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$03
@env6:
	.byte $1b,$cf,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$02,$c5,$03,$c4,$03,$c3,$04,$c2,$c2,$c2,$00,$18,$c2,$02,$c1,$05,$c0,$08,$c0,$00,$21
@env7:
	.byte $b8,$be,$00,$01
@env8:
	.byte $04,$cf,$00,$01,$ca,$c5,$c0,$00,$06
@env9:
	.byte $00,$cf,$c6,$c2,$c0,$00,$04
@env10:
	.byte $00,$cf,$7f,$00,$02
@env11:
	.byte $00,$c0,$13,$c0,$c1,$c2,$c4,$c2,$c1,$c0,$bf,$be,$bc,$be,$bf,$00,$03
@env12:
	.byte $ca,$7f,$00,$00
@env13:
	.byte $c0,$7f,$00,$01
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $c1,$7f,$00,$00
@env16:
	.byte $c0,$c5,$00,$01
@env17:
	.byte $00,$cf,$c8,$c5,$c4,$c3,$c2,$c1,$c0,$00,$08
@env18:
	.byte $00,$cf,$cc,$c9,$c6,$c5,$c3,$c1,$c0,$00,$08
@env19:
	.byte $c8,$7f,$00,$00
@env20:
	.byte $c9,$d1,$00,$01
@env21:
	.byte $00,$cf,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env22:
	.byte $00,$c4,$c3,$c2,$c1,$c1,$c0,$00,$06
@env23:
	.byte $00,$cb,$c6,$c3,$c2,$c1,$c0,$00,$06
@env24:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env25:
	.byte $00,$bf,$c0,$00,$02

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0f,$40,$08 ; 00 B3 - industrial bass (Pitch:15)
	.byte $1f+.lobyte(FAMISTUDIO_DPCM_PTR),$11,$0f,$40,$07 ; 01 bongos - C5 (Pitch:15)
	.byte $10+.lobyte(FAMISTUDIO_DPCM_PTR),$17,$0f,$40,$07 ; 02 bongos - D5 (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$1b,$0f,$40,$07 ; 03 bongos - Db5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$3d,$0f,$40,$07 ; 04 bongos - E5 (Pitch:15)
	.byte $16+.lobyte(FAMISTUDIO_DPCM_PTR),$23,$0f,$40,$07 ; 05 bongos - Eb5 (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$40,$08 ; 06 C3 - smash bass drum (Pitch:15)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$08,$0f,$40,$08 ; 07 C6 - plink (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$2e,$0f,$40,$08 ; 08 D4 - metal light (Pitch:15)
	.byte $6c+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40,$08 ; 09 Db6 - bonk3 (Pitch:15)
	.byte $2b+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0f,$40,$07 ; 0a dice (Pitch:15)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$07 ; 0b dice2 (Pitch:15)
	.byte $64+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$0f,$40,$07 ; 0c E4 - metal loud (Pitch:15)
	.byte $71+.lobyte(FAMISTUDIO_DPCM_PTR),$16,$0f,$40,$08 ; 0d E6 - bonk4 (Pitch:15)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0e,$40,$08 ; 0e Eb6 - bonk (Pitch:14)
	.byte $65+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$0f,$40,$08 ; 0f Eb6 - bonk (Pitch:15)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$04 ; 10 evillaugh0 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 11 evillaugh1 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$05 ; 12 evillaugh2 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 13 evillaugh3 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$06 ; 14 evillaugh4 (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$9e,$0f,$40,$08 ; 15 F4 - oil drum snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$3e,$02 ; 16 finalfanfare0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$38,$02 ; 17 finalfanfare1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$58,$03 ; 18 finalfanfare2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$03 ; 19 finalfanfare3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$e9,$0f,$4c,$04 ; 1a finalfanfare4 (Pitch:15)
	.byte $66+.lobyte(FAMISTUDIO_DPCM_PTR),$50,$0f,$40,$01 ; 1b industrial snare (Pitch:15)
	.byte $0a+.lobyte(FAMISTUDIO_DPCM_PTR),$3b,$0f,$40,$09 ; 1c laser dabs (Pitch:15)
	.byte $27+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$09 ; 1d lightfill1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1e lightfill2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0a ; 1f lightfill3 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$0b ; 20 lightfill4 (Pitch:15)
	.byte $19+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$09 ; 21 scratch standard (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$26,$0f,$40,$09 ; 22 snarish drum (Pitch:15)
	.byte $42+.lobyte(FAMISTUDIO_DPCM_PTR),$88,$0d,$40,$07 ; 23 sunflower (Pitch:13)
	.byte $3f+.lobyte(FAMISTUDIO_DPCM_PTR),$0a,$0f,$40,$07 ; 24 tennis (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 25 winmusic0 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 26 winmusic1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 27 winmusic2 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$97,$0f,$40,$01 ; 28 winmusic3 (Pitch:15)

@song0ch0:
	.byte $46, $03
@song0ch0loop:
@song0ref4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch19:
@song0ch16:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch1:
@song0ch1loop:
	.byte $41, $16
	.word @song0ref4
	.byte $42
	.word @song0ch1loop
@song0ch8:
@song0ch8loop:
	.byte $80
@song0ref46:
	.byte $16, $5c, $93, $22, $5c, $93, $11, $8d, $16, $5c, $93, $22, $5c, $93, $11, $8d, $12, $5c, $9b, $1e, $5c, $9b, $12, $5c
	.byte $bb
	.byte $41, $19
	.word @song0ref46
	.byte $0f, $5c, $9b, $1b, $5c, $93, $16, $5c, $93, $15, $5c, $9b, $18, $5c, $8b, $16, $5c, $9b, $14, $5c, $9b, $13, $5c, $8b
	.byte $16, $5c, $8b, $0f, $5c, $8b, $16, $5c, $8b, $12, $5c, $9b, $1e, $5c, $8b, $12, $5c, $8b, $0f, $5c, $9b, $1b, $5c, $9b
	.byte $11, $85, $5c, $f5
@song0ref126:
	.byte $7c, $16, $85, $5c, $85, $1d, $5c, $8b, $11, $85, $5c, $85, $1d, $5c, $8b, $16, $85, $5c, $85, $1d, $5c, $8b, $11, $85
	.byte $5c, $85, $1d, $5c, $8b, $12, $85, $5c, $85, $7a, $19, $5c, $8b, $7c, $0d, $85, $5c, $85, $7a, $19, $5c, $8b, $7c, $12
	.byte $85, $5c, $85, $7a, $19, $5c, $8b, $7c, $14, $85, $5c, $85, $7a, $1b, $5c, $8b
	.byte $41, $38
	.word @song0ref126
	.byte $7c
@song0ref194:
	.byte $16, $5c, $93, $7f, $1d, $81, $5c, $81, $22, $81, $5c, $89, $7c, $11, $81, $5c, $89, $16, $81, $5c, $b9
	.byte $41, $13
	.word @song0ref194
	.byte $7b, $86
@song0ref220:
	.byte $22, $85, $5c, $85, $25, $85, $5c, $95, $29, $85, $5c, $95, $29, $85, $5c, $95, $47, $00, $29, $85, $5c, $85, $22, $85
	.byte $5c, $85, $25
@song0ref247:
	.byte $85, $5c, $85, $20, $85, $5c, $85, $29, $85, $5c, $85, $1e, $85, $5c, $85, $2a, $85, $5c, $85, $1d, $85, $5c, $85, $24
	.byte $85, $5c, $85, $22, $85, $5c, $85, $25, $85, $5c, $85, $24, $85, $5c, $85, $2c
	.byte $41, $13
	.word @song0ref247
@song0ref290:
	.byte $22, $85, $5c, $85, $25, $85, $5c, $85, $1e, $85, $5c, $85, $21, $85, $5c, $85, $22, $85, $5c, $85, $25, $85, $5c, $85
	.byte $29, $7c, $85, $27, $85, $25, $85, $24, $85, $7b
	.byte $41, $41
	.word @song0ref220
	.byte $41, $13
	.word @song0ref247
	.byte $41, $20
	.word @song0ref290
	.byte $42
	.word @song0ch8loop
@song0ch9:
@song0ch9loop:
	.byte $7f, $00, $8d, $80, $1d, $5c, $bb, $1d, $5c, $ab, $8f, $19, $5c, $9b, $0d, $5c, $cb, $00, $8d, $1d, $5c, $bb, $1d, $5c
	.byte $ab, $8f, $19, $5c, $9b, $0d, $5c, $8b, $7d, $82, $1e, $81, $5c, $a1, $7a, $1e, $85, $5c, $85, $1c, $85, $5c, $85, $00
	.byte $85, $7f, $80, $16, $5c, $9b, $0f, $5c, $8b, $11, $5c, $9b, $15, $5c, $8b, $7d, $82, $25, $85, $5c, $85, $7f, $8f, $80
	.byte $1d, $81, $5c, $99, $1d, $81, $5c, $99, $1b, $81, $5c, $99, $1b, $81, $5c, $89, $97, $19, $81, $5c, $91, $0d, $5c, $a3
	.byte $16, $81, $5c, $91, $0f, $85, $5c, $85, $7d, $30, $9d, $5c, $9d, $7b, $39, $9d, $5c, $8d, $79, $40, $4d, $8d, $7a, $00
	.byte $8d
@song0ref458:
	.byte $22, $5c, $9b, $22, $5c, $9b, $22, $5c, $9b, $22, $5c, $8b, $8f, $1e, $5c, $9b, $1e, $5c, $9b, $1e, $5c, $9b, $20, $5c
	.byte $8b, $8f
	.byte $41, $19
	.word @song0ref458
	.byte $7c, $86
@song0ref489:
	.byte $3a, $81, $5c, $89, $39, $81, $5c, $81, $35, $81, $5c, $81, $38, $81, $5c, $89, $37, $81, $5c, $89, $35, $81, $5c, $b9
	.byte $41, $18
	.word @song0ref489
@song0ref516:
	.byte $7b, $00, $8d, $29, $85, $5c, $85, $1d, $85, $5c, $85, $25, $85, $5c, $85, $22, $85, $5c, $85, $25, $85, $5c, $85, $1d
	.byte $85, $5c, $85, $25, $85, $5c, $85, $00, $8d, $29, $85, $5c, $95, $25, $85, $5c, $95, $27, $85, $5c, $95, $29, $85, $5c
	.byte $85, $8f, $29, $85, $5c, $95, $27, $85, $5c, $95, $25, $85, $5c, $95, $27, $85, $5c, $85, $8f, $29, $85, $5c, $95, $24
	.byte $85, $5c, $95, $29, $85, $5c, $85, $7c, $1d, $85, $5c, $95
	.byte $41, $52
	.word @song0ref516
	.byte $42
	.word @song0ch9loop
@song0ch10:
@song0ch10loop:
	.byte $7c, $8f
@song0ref609:
	.byte $80, $28, $5c, $8b, $2e, $5c, $ab, $28, $5c, $8b, $2c, $5c, $8b, $2a, $5c, $8b, $28, $bd, $25, $81, $5c, $b9, $7a, $82
	.byte $22, $85, $5c, $85, $7c
	.byte $41, $10
	.word @song0ref609
	.byte $9d, $7d, $82, $25, $8d, $5c, $8d, $7c, $80, $25, $81, $5c, $b9, $27, $ad, $5c, $85, $2a, $85, $5c, $8d, $24, $8d, $5c
	.byte $85, $7d, $82, $27, $85, $80, $27, $8d, $25, $9d, $29, $9d, $2e, $9d, $5c, $9d, $2e, $85, $5c, $85, $2e, $85, $5c, $85
	.byte $31, $85, $5c, $95, $2e, $85, $5c, $85, $2e, $85, $5c, $85, $31, $85, $5c, $95, $9f, $7c, $35, $9d, $5c, $9d, $7a, $3c
	.byte $8d, $5c, $8d, $7c
@song0ref717:
	.byte $40, $52, $85, $5c, $85, $40, $51, $85, $40, $4d, $85, $40, $50, $85, $5c, $85, $40, $4f, $85, $3f, $85, $40, $4e, $85
	.byte $40, $4d, $85, $3d, $85, $40, $4d, $85, $3d, $85, $5c, $85, $40, $4d, $85, $3d, $85, $3a, $9d, $5c, $dd
	.byte $41, $24
	.word @song0ref717
	.byte $00, $dd, $7a, $82, $1d, $85, $5c, $85, $1f, $85, $5c, $85, $22, $85, $5c, $d5, $1d, $85, $5c, $85, $1f, $85, $5c, $85
@song0ref789:
	.byte $22, $85, $5c, $95, $1d, $85, $5c, $95, $22, $85, $5c, $85, $22, $85, $5c, $85, $1d, $85, $5c, $95, $22, $85, $5c, $85
	.byte $22, $85, $5c, $85, $25, $85, $5c, $95, $27, $85, $5c, $95, $24, $85, $5c, $95, $22, $85, $5c, $95, $20, $85, $5c, $95
	.byte $25, $85, $5c, $85, $25, $85, $5c, $85, $2a, $85, $5c, $95, $29, $85, $5c, $8d, $22, $85, $5c, $8d, $25, $85, $5c, $c5
	.byte $41, $48
	.word @song0ref789
	.byte $42
	.word @song0ch10loop
@song0ch11:
@song0ch11loop:
@song0ref868:
	.byte $7c, $5c, $85, $00, $8d, $80, $29, $5c, $bb, $29, $5c, $8b, $2b, $5c, $8b, $29, $5c, $83, $7a, $86, $3a, $8d, $35, $8d
	.byte $37, $8d, $36, $8d, $31, $8d, $00, $95, $82, $1f, $85, $5c, $85, $21, $85
	.byte $41, $11
	.word @song0ref868
	.byte $85, $39, $85, $35, $85, $38, $85, $37, $85, $33, $85, $36, $85, $35, $85, $31, $8d, $00, $ad, $82, $1b, $85, $5c, $a5
	.byte $7c, $80, $29, $85, $5c, $85, $29, $8d, $5c, $8d, $29, $8d, $5c, $85, $7d, $82, $24, $85, $25, $9d, $24, $9d, $22, $9d
	.byte $5c, $9d, $87, $80, $2d, $85, $5c, $85, $30, $85, $5c, $a5, $2d, $85, $5c, $85, $30, $85, $5c, $8d, $33, $85, $5c, $85
	.byte $00, $fd, $78, $84, $35, $fd, $36, $dd, $33, $9d, $35, $fd, $36, $dd, $33, $9d, $00, $e5, $7a, $82, $1e, $85, $5c, $85
	.byte $20, $85, $5c, $e5, $1e, $85, $5c, $85, $20, $85, $5c
@song0ref1017:
	.byte $c5, $21, $85, $5c, $85, $25, $85, $5c, $9d, $87, $21, $85, $5c, $85, $24, $85, $5c, $8d, $29, $85, $5c, $95, $25, $85
	.byte $5c, $a5, $c7, $24, $85, $5c, $85, $29, $85, $5c, $9d, $8f, $25, $85, $5c, $85, $24, $85, $5c, $95, $22, $85, $5c, $b5
	.byte $00
	.byte $41, $30
	.word @song0ref1017
	.byte $42
	.word @song0ch11loop
@song0ch12:
@song0ch12loop:
	.byte $ff, $7a, $87, $86, $39, $8d, $38, $8d, $33, $8d, $35, $8d, $00, $95, $82, $1e, $85, $5c, $85, $20, $85, $5c, $85, $78
	.byte $84, $2e, $bd, $2e, $bd, $2e, $ad, $7d, $82, $19, $8d, $78, $84, $2a, $81, $5c, $b9, $3a, $bd, $39, $9d, $3c, $9d, $3d
	.byte $bd, $3f, $bd, $7b, $94, $2e, $85, $2d, $85, $2e, $85, $30, $85, $31, $85, $5c, $95, $2e, $85, $2d, $85, $2e, $85, $30
	.byte $85, $31, $8d, $33, $8d, $30, $dd, $5c
@song0ref1153:
	.byte $9d, $7c, $2e, $95, $7f, $30, $85, $31, $85, $29, $85, $31, $85, $30, $85, $7c, $2e, $95, $7f, $30, $85, $31, $85, $33
	.byte $85, $31, $85, $30, $85, $7c, $2e, $95, $7f, $30, $85, $31, $85, $25, $85, $31, $85, $30, $85, $7c, $2e, $9d, $7d, $30
	.byte $41, $27
	.word @song0ref1153
	.byte $7d, $2c, $9d, $7c, $51, $ff, $a0, $2e, $9d, $51, $fe, $00, $bf, $00, $9d, $ff, $ff, $ff, $ff, $ff, $79, $84, $3a, $8d
	.byte $3d, $8d, $35, $9d, $3a, $8d, $3d, $8d, $35, $9d, $3d, $bd, $3f, $8d, $3d, $8d, $3c, $9d, $3a, $9d, $3c, $8d, $38, $8d
	.byte $3d, $9d, $3f, $8d, $40, $4e, $8d, $40, $4d, $bd, $5c, $bd, $42
	.word @song0ch12loop
@song0ch13:
@song0ch13loop:
	.byte $ff, $ff, $78, $84, $35, $bd, $31, $bd, $34, $bd, $31, $81, $5c, $a9, $7a, $82, $1d, $85, $5c, $85, $78, $84, $36, $bd
	.byte $35, $bd, $3a, $9d, $38, $9d, $37, $9d, $33, $9d, $00, $fd, $ff, $3d, $fd, $3a, $dd, $3c, $9d, $3d, $fd, $3a, $dd, $3c
	.byte $9d, $00, $fd, $ff, $ff, $ff, $ff, $ff, $79, $2e, $9d, $31, $8d, $30, $8d, $2e, $9d, $31, $8d, $30, $8d, $3a, $9d, $35
	.byte $9d, $36, $9d, $39, $8d, $35, $8d, $35, $8d, $2e, $8d, $33, $9d, $38, $8d, $35, $8d, $36, $9d, $00, $fd, $42
	.word @song0ch13loop
@song0ch14:
@song0ch14loop:
	.byte $7c, $88
@song0ref1367:
	.byte $25, $89, $25, $85, $25, $91, $25, $95, $25, $89, $25, $89, $25, $85, $25, $85, $25, $95, $25, $89, $25, $85, $25, $91
	.byte $25, $89, $25, $89, $25, $89, $25, $89, $25, $85, $25, $9d
	.byte $41, $24
	.word @song0ref1367
	.byte $41, $24
	.word @song0ref1367
	.byte $41, $24
	.word @song0ref1367
	.byte $25, $bd, $25, $bd, $25, $bd, $25, $9d, $25, $9d, $25, $bd, $25, $85, $25, $b5, $25, $bd, $25, $9d, $25, $9d, $00, $fd
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch14loop
@song0ch15:
@song0ch15loop:
	.byte $7e, $00, $8d, $88
@song0ref1453:
	.byte $25, $85, $00, $95, $25, $85, $00, $95, $25, $85, $00, $95, $25, $85, $00, $85, $8f, $25, $85, $00, $95, $25, $85, $00
	.byte $95, $25, $85, $00, $85, $25, $85, $25, $85, $25, $85, $25, $85, $00, $8d
	.byte $41, $27
	.word @song0ref1453
	.byte $41, $27
	.word @song0ref1453
	.byte $41, $27
	.word @song0ref1453
@song0ref1501:
	.byte $25, $8d, $77, $25, $25, $25, $25, $25, $25, $25, $25, $7c, $25, $85, $25, $85
@song0ref1517:
	.byte $00, $8d, $25, $85, $25, $85, $77, $25, $25, $25, $25, $25, $25, $25, $25, $7c, $25, $8d
	.byte $41, $10
	.word @song0ref1517
@song0ref1538:
	.byte $00, $8d, $25, $85, $25, $8d, $25, $85, $77, $25, $25, $25, $25, $7c, $25, $85, $00, $8d
	.byte $41, $11
	.word @song0ref1501
	.byte $8d, $77, $25, $25, $25, $25, $25, $25, $25, $25, $7c, $25, $8d
	.byte $41, $10
	.word @song0ref1517
	.byte $41, $0f
	.word @song0ref1538
	.byte $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch15loop
@song0ch17:
@song0ch17loop:
	.byte $79, $88
@song0ref1594:
	.byte $25, $85, $25, $85, $25, $85, $25, $85, $25, $85, $25, $85, $25, $85, $25, $85
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $41, $10
	.word @song0ref1594
	.byte $00, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch17loop
@song0ch18:
@song0ch18loop:
	.byte $ff, $7a, $db, $88, $25, $81, $00, $9d, $ff, $db, $25, $81, $00, $9d, $ff, $db, $25, $81, $00, $9d, $ff, $db, $25, $81
	.byte $00, $9d, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch18loop
@song1ch0:
	.byte $46, $02, $ff
@song1ch0loop:
@song1ref5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0d
	.word @song1ref5
	.byte $42
	.word @song1ch0loop
@song1ch19:
@song1ch18:
@song1ch16:
@song1ch7:
@song1ch3:
@song1ch2:
@song1ch1:
	.byte $ff
@song1ch1loop:
	.byte $41, $0d
	.word @song1ref5
	.byte $41, $0d
	.word @song1ref5
	.byte $42
	.word @song1ch1loop
@song1ch4:
	.byte $ff
@song1ch4loop:
@song1ref43:
	.byte $ff
@song1ref44:
	.byte $ef, $22, $85, $22, $85, $00, $fd, $ef, $22, $85, $22, $85, $00, $fd
	.byte $41, $0e
	.word @song1ref44
	.byte $41, $0e
	.word @song1ref44
@song1ref64:
	.byte $df, $22, $81, $00, $99, $c7, $22, $81, $00, $89, $22, $89, $22, $81, $00, $81, $22, $81, $22, $81, $00, $81, $22, $81
	.byte $00, $81
	.byte $41, $1a
	.word @song1ref64
	.byte $ff
	.byte $41, $0f
	.word @song1ref43
	.byte $c7, $22, $81, $00, $89, $22, $89, $22, $81, $00, $85, $22, $81, $00, $89, $ff, $ff, $42
	.word @song1ch4loop
@song1ch5:
	.byte $ff
@song1ch5loop:
	.byte $41, $0d
	.word @song1ref5
	.byte $ff, $7c, $92, $30, $8d, $79, $30, $8d, $7c, $2d, $8d, $79, $2d, $8d, $7d, $29, $9d, $2e, $9d, $00, $fd, $7c, $30, $8d
	.byte $79, $30, $8d, $7c, $2d, $8d, $79, $2d, $8d, $7d, $29, $9d, $2e, $9d, $7e, $36, $87, $36, $83, $33, $8d, $30, $8d, $2c
	.byte $8d, $29, $9d, $79, $29, $9d, $7d
@song1ref177:
	.byte $29, $89, $2e, $91, $30, $9d, $29, $89, $2e, $91, $30, $9d, $2a, $89, $2e, $91, $34, $9d, $35, $bd
	.byte $41, $14
	.word @song1ref177
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch5loop
@song1ch6:
	.byte $ff
@song1ch6loop:
	.byte $41, $0d
	.word @song1ref5
	.byte $ff, $7d, $92
@song1ref216:
	.byte $34, $8d, $79, $34, $8d, $7d, $35, $8d, $79, $35, $8d, $7d, $2e, $8d, $30, $8d, $31, $8d, $32, $8d, $00, $fd
	.byte $41, $10
	.word @song1ref216
	.byte $7e, $00, $85, $35, $81, $35, $81, $00, $85, $31, $8d, $2e, $8d, $2a, $95, $7c, $29, $9d, $76, $29, $8d, $7d
@song1ref263:
	.byte $00, $81, $2c, $91, $31, $95, $2e, $91, $2c, $91, $31, $95, $2e, $8d, $83, $2c, $91, $31, $95, $31, $cd
	.byte $41, $15
	.word @song1ref263
	.byte $00, $fd, $ff, $ff, $ff, $42
	.word @song1ch6loop
@song1ch8:
	.byte $7d, $8e
@song1ref297:
	.byte $2e
@song1ref298:
	.byte $81, $5c, $85, $35, $81, $5c, $85, $35, $81, $5c, $89, $7a, $35, $81, $5c, $91, $7d
	.byte $41, $10
	.word @song1ref297
@song1ch8loop:
	.byte $7d
	.byte $41, $10
	.word @song1ref297
	.byte $7d, $31
	.byte $41, $0f
	.word @song1ref298
@song1ref328:
	.byte $7d, $33, $81, $5c, $85, $3a, $81, $5c, $85, $3a, $81, $5c, $89, $7a, $3a, $81, $5c, $91, $7d, $2a, $81, $5c, $85, $31
	.byte $81, $5c, $85, $77, $36, $81, $5c, $85, $7d, $83, $33, $81, $5c, $81, $38, $81, $5c, $89
	.byte $41, $10
	.word @song1ref297
	.byte $7d, $31
	.byte $41, $0f
	.word @song1ref298
	.byte $41, $25
	.word @song1ref328
	.byte $41, $10
	.word @song1ref297
	.byte $7d, $31
	.byte $41, $0f
	.word @song1ref298
	.byte $41, $25
	.word @song1ref328
	.byte $41, $10
	.word @song1ref297
	.byte $7d, $31
	.byte $41, $0f
	.word @song1ref298
	.byte $41, $25
	.word @song1ref328
@song1ref403:
	.byte $2e, $81, $5c, $81, $35, $81, $35, $81, $3a, $81, $5c, $81, $35, $81, $5c, $89, $7a, $35, $81, $5c, $89, $77, $35, $83
	.byte $5c, $7d, $31, $81, $5c, $81, $35, $81, $35, $81, $38, $81, $5c, $81, $35, $81, $5c, $89, $7a, $35, $81, $5c, $89, $77
	.byte $35, $81, $5c, $81, $7d, $33, $81, $5c, $81, $3a, $81, $3a, $81, $3d, $81, $5c, $81, $3a, $81, $5c, $89, $7a, $3a, $81
	.byte $5c, $89, $77, $3a, $81, $5c, $81, $7d, $2a, $81, $5c, $81, $31, $81, $31, $81, $36, $81, $5c, $81, $77, $36, $81, $5c
	.byte $81, $7d, $2c, $81, $5c, $81, $33, $81, $33, $81, $38, $81, $5c, $81, $77, $38, $81, $5c, $81, $7d
	.byte $41, $67
	.word @song1ref403
	.byte $7d
	.byte $41, $10
	.word @song1ref297
	.byte $7d
	.byte $41, $10
	.word @song1ref297
	.byte $7d
@song1ref531:
	.byte $2a, $81, $5c, $81, $78, $2a, $81, $7d, $31, $81, $5c, $81, $78, $31, $81, $7d, $36, $81, $5c, $81
	.byte $41, $10
	.word @song1ref531
@song1ref554:
	.byte $29, $81, $5c, $81, $78, $29, $81, $7d, $30, $81, $5c, $81, $78, $30, $81, $7d, $35, $81, $5c, $81
	.byte $41, $10
	.word @song1ref554
@song1ref577:
	.byte $27, $81, $5c, $81, $78, $27, $81, $7d, $2a, $81, $5c, $81, $78, $2a, $81, $7d, $2e, $81, $5c, $81, $29, $81, $5c, $81
	.byte $78, $29, $81, $7d, $2d, $81, $5c, $81, $78, $2d, $81, $7d, $30, $81, $5c, $81, $2e, $81, $5c, $81, $78, $2e, $81, $7d
	.byte $30, $81, $5c, $81, $78, $30, $81, $7d, $2c, $81, $5c, $81, $31, $81, $5c, $81, $78, $31, $81, $7d, $32, $81, $5c, $81
	.byte $78, $32, $81, $7d, $2e, $81, $5c, $81
	.byte $41, $10
	.word @song1ref531
	.byte $41, $10
	.word @song1ref531
	.byte $41, $10
	.word @song1ref554
	.byte $41, $10
	.word @song1ref554
	.byte $41, $40
	.word @song1ref577
@song1ref672:
	.byte $2a, $81, $5c, $81, $78, $2a, $81, $7d, $2e, $81, $5c, $81, $78, $2e, $81, $7d, $31, $81, $5c, $81, $27, $81, $5c, $81
	.byte $78, $27, $81, $79, $27, $81, $5c, $81, $74, $27, $81, $76, $27, $81, $5c, $81, $72, $27, $81, $00, $b9, $7d
@song1ref718:
	.byte $35, $81, $5c, $81, $3a, $81, $3a, $81, $35, $81, $5c, $81, $3a, $81, $5c, $81, $2e, $81, $5c, $81, $3a, $81, $5c, $81
	.byte $35, $85, $31, $81, $5c, $81
	.byte $41, $1e
	.word @song1ref718
@song1ref751:
	.byte $36, $81, $5c, $81, $3d, $81, $3d, $81, $3a, $81, $5c, $81, $3d, $81, $5c, $81, $2e, $81, $5c, $81, $3a, $81, $5c, $81
	.byte $36, $85, $31, $81, $5c, $81, $35, $81, $5c, $81, $39, $81, $39, $81, $3c, $81, $5c, $81, $35, $81, $5c, $81, $40, $4d
	.byte $81, $5c, $81, $3c, $81, $5c, $81, $39, $81, $5c, $81, $35, $81, $5c, $81
	.byte $41, $1e
	.word @song1ref718
	.byte $41, $1e
	.word @song1ref718
	.byte $41, $3e
	.word @song1ref751
@song1ref823:
	.byte $33, $81, $5c, $81, $78, $33, $81, $7d, $36, $81, $5c, $81, $78, $36, $81, $7d, $3a, $81, $5c, $81, $30, $81, $5c, $81
	.byte $78, $30, $81, $7d, $33, $81, $5c, $81, $78, $33, $81, $7d, $36, $81, $5c, $81, $2e, $81, $5c, $81, $78, $2e, $81, $7d
	.byte $31, $81, $5c, $81, $78, $31, $81, $7d, $35, $81, $5c, $81
	.byte $41, $10
	.word @song1ref672
@song1ref886:
	.byte $33, $81, $5c, $81, $78, $33, $81, $7d, $36, $81, $5c, $81, $78, $36, $81, $7d, $2e, $81, $5c, $81, $35, $81, $5c, $81
	.byte $78, $35, $81, $7d, $39, $81, $5c, $81, $78, $39, $81, $7d, $3c, $81, $5c, $c1
	.byte $41, $30
	.word @song1ref823
	.byte $41, $10
	.word @song1ref672
	.byte $41, $1f
	.word @song1ref886
	.byte $81, $29, $81, $5c, $81, $78, $29, $81, $7d, $30, $81, $5c, $81, $78, $30, $81, $7d, $30, $81, $5c, $89, $78, $30, $81
	.byte $5c, $91, $42
	.word @song1ch8loop
@song1ch9:
@song1ref964:
	.byte $00, $85
@song1ref966:
	.byte $7d, $8e
@song1ref968:
	.byte $35, $81, $5c, $81, $3a, $81, $5c, $a1, $77, $35, $81, $5c, $89, $7d, $35, $81, $5c, $81, $3a, $81, $5c, $a1, $77, $35
	.byte $81, $5c, $81
@song1ch9loop:
	.byte $87
	.byte $41, $10
	.word @song1ref966
@song1ref1000:
	.byte $38, $81, $5c, $a1, $77, $35, $81, $5c, $81, $87, $7d, $3a, $81, $5c, $81, $3d, $81, $5c, $a1, $77, $3a, $81, $5c, $89
	.byte $7d, $31, $81, $5c, $81, $36, $81, $5c, $89, $2c, $81, $5c, $85, $33, $81, $5c, $85, $77, $38, $81, $5c, $81, $87, $7d
	.byte $41, $10
	.word @song1ref968
	.byte $41, $2a
	.word @song1ref1000
	.byte $7d
	.byte $41, $10
	.word @song1ref968
	.byte $41, $2a
	.word @song1ref1000
	.byte $7d
	.byte $41, $10
	.word @song1ref968
	.byte $41, $29
	.word @song1ref1000
	.byte $7b, $86
@song1ref1070:
	.byte $2e, $5c, $8b, $28, $85, $29, $85, $22, $5c, $8b, $28, $85, $29, $85, $2c, $85, $27, $85, $29, $85, $2c, $85, $29, $5c
	.byte $8b, $2c, $85, $2a, $85, $87, $29, $85, $27, $85, $25, $85, $22, $5c, $8b, $20, $85, $22, $85, $25, $85, $27, $85, $29
	.byte $83, $25, $27, $85, $25, $5c, $89, $25, $28, $85, $29, $85
	.byte $41, $38
	.word @song1ref1070
	.byte $27, $85, $22, $85
	.byte $41, $1a
	.word @song1ref964
	.byte $7b, $90, $2e, $85, $77, $31, $81, $7b, $2c, $85, $77, $30, $81, $7b, $2a, $85, $77, $2e, $81, $7b, $2c, $85, $77, $30
	.byte $81, $7b, $2e, $85, $2a, $85, $2c, $85, $77, $30, $95, $7b, $29, $85, $77, $2c, $85, $7b, $24, $85, $77, $29, $85, $00
	.byte $ed, $73, $51, $04, $a0, $84, $35, $8d, $36, $9d, $35, $8d, $33, $8d, $2c, $9d, $29, $8d, $24, $8d, $78, $27, $9d, $5c
	.byte $dd, $7b, $8a, $2a, $9d, $51, $fc, $00, $5c, $95, $c7, $00, $fd, $ff, $ff, $ff, $7b, $80
@song1ref1230:
	.byte $3f, $81, $5c, $81, $3f, $81, $5c, $81, $40, $4e, $81, $5c, $85, $40, $4d, $81, $5c, $85, $3d, $81, $5c, $89, $40, $4e
	.byte $81, $5c, $85, $40, $4e, $81, $5c, $81, $3f, $81, $5c, $85, $3d, $81, $5c, $81, $3a, $81, $5c, $89, $40, $4d, $81, $5c
	.byte $89, $3f, $81, $5c, $81, $3f, $81, $5c, $81, $3c, $81, $5c, $85, $3a, $81, $5c, $85, $39, $81, $5c, $89, $3c, $81, $5c
	.byte $85, $39, $81, $5c, $81, $3c, $81, $5c, $81, $3c, $81, $5c, $81, $3f, $81, $5c, $81, $3a, $81, $5c, $81, $40, $4d, $81
	.byte $5c, $81, $40, $50, $81, $5c, $81, $40, $4d, $81
	.byte $41, $43
	.word @song1ref1230
	.byte $89, $00, $85, $78, $40, $4d, $81, $5c, $a1, $7b, $86, $29, $85, $42
	.word @song1ch9loop
@song1ch10:
	.byte $7b, $ef, $86, $28, $85, $5c, $85
@song1ch10loop:
@song1ref1363:
	.byte $2e, $5c, $93, $29, $85, $5c, $8d, $28, $85, $5c, $85, $2c, $85, $5c, $85, $29, $85, $5c, $85, $29, $5c, $8b, $2c, $85
	.byte $5c, $85, $87, $29, $85, $5c, $85, $25, $85, $5c, $8d, $20, $85, $5c, $85, $25, $85, $5c, $85, $29, $85, $27, $85, $5c
	.byte $8d, $28, $85, $5c, $85
	.byte $41, $31
	.word @song1ref1363
	.byte $27, $85, $5c, $85, $00, $fd, $ff, $ff, $7b, $ef, $80
@song1ref1430:
	.byte $34, $85, $35, $85, $3a, $5c, $8b, $34, $85, $35, $85, $2e, $5c, $8b, $34, $85, $35, $85, $38, $85, $33, $85, $35, $85
	.byte $38, $85, $35, $5c, $8b, $38, $85, $36, $85, $87, $35, $85, $33, $85, $31, $85, $2e, $5c, $8b, $2c, $85, $2e, $85, $31
	.byte $85, $33, $85, $35, $83, $31, $33, $85, $31, $5c, $89, $31
	.byte $41, $3c
	.word @song1ref1430
	.byte $33, $85, $2e, $85, $5c, $ed, $3a, $85, $3c, $85, $3d, $85, $5c, $81, $3c, $81, $5c, $85, $3a, $85, $5c, $81, $3c, $81
	.byte $5c, $85, $3d, $85, $3a, $85, $3c, $8d, $5c, $8d, $38, $85, $5c, $85, $35, $85, $5c, $85
@song1ref1535:
	.byte $34, $85, $5c, $85, $36, $85, $5c, $85, $35, $85, $5c, $35, $5c, $81, $31, $85, $5c, $85, $31, $8d, $5c, $8d, $35, $8d
	.byte $5c, $8d, $3a, $9d, $38, $8d, $36, $8d, $35, $9d, $30, $8d, $35, $8d
	.byte $41, $1a
	.word @song1ref1535
	.byte $00, $fd, $ff, $ef, $7a, $84, $2b, $85, $5c, $85, $2e, $95, $5c, $85, $31, $8d, $5c, $8d, $2e, $95, $5c, $85, $31, $8d
	.byte $5c, $8d, $2e, $95, $5c, $85, $34, $8d, $5c, $8d, $35, $9d, $51, $02, $e0, $9f, $51, $e2, $00, $5c, $81, $7b, $80
@song1ref1623:
	.byte $3e, $81, $5c, $81, $40, $4d, $81, $5c, $85, $40, $4e, $81, $5c, $81, $3f, $81, $5c, $89, $3c, $81, $5c, $89, $40, $4d
	.byte $81, $5c, $81, $40, $4d, $81, $5c, $81, $3d, $81, $5c, $85, $3c, $81, $5c, $85, $35, $81, $5c, $89, $3d, $81, $5c, $81
	.byte $00, $81, $40, $4d, $81, $5c, $81, $3d, $81, $5c, $85, $3c, $81, $5c, $81, $39, $81, $5c, $89, $3a, $81, $5c, $89, $3a
	.byte $81, $5c, $81, $3a, $81, $5c, $81, $3d, $81, $5c, $81, $3d, $81, $5c, $81, $40, $4d, $81, $5c, $81, $3e, $81, $5c, $81
	.byte $40, $52, $81, $5c, $81, $40, $4e, $81, $5c, $81, $7e, $51, $e2, $00, $83, $7b
	.byte $41, $42
	.word @song1ref1623
	.byte $40, $4d, $81, $5c, $99, $76, $40, $4d, $81, $5c, $89, $7b, $86, $28, $85, $5c, $85, $42
	.word @song1ch10loop
@song1ch11:
	.byte $7b, $f7, $86, $29, $85
@song1ch11loop:
	.byte $5c, $8d, $86
@song1ref1767:
	.byte $28, $85, $5c, $85, $22, $5c, $93, $29, $85, $5c, $85, $27, $85, $5c, $85, $2c, $85, $5c, $95, $2a, $85, $8f, $27, $85
	.byte $5c, $85, $22, $5c, $93, $22, $85, $5c, $85, $27, $85, $5c, $83, $25, $5c, $85, $25, $5c, $89, $25, $5c, $85, $29, $85
	.byte $00, $8d
	.byte $41, $2e
	.word @song1ref1767
	.byte $22, $85, $00, $85, $76, $8c
@song1ref1826:
	.byte $2e, $81, $5c, $81, $74, $2e, $81, $5c, $81, $73, $2e, $81, $5c, $81
@song1ref1840:
	.byte $76, $31
@song1ref1842:
	.byte $81, $5c, $81, $2e, $81, $5c, $81, $74, $2e, $81, $5c, $81, $76, $2c, $81, $5c, $81, $2e, $81, $5c, $81, $2e, $81, $5c
	.byte $81, $74, $2e, $81, $5c, $81, $73, $2e, $81, $5c, $81, $76, $35
	.byte $41, $1f
	.word @song1ref1842
	.byte $41, $18
	.word @song1ref1840
@song1ref1885:
	.byte $35, $81, $5c, $81, $2e, $81, $5c, $81, $2c, $81, $5c, $81, $2e, $81, $5c, $81, $31, $81, $5c, $81, $2e, $81, $5c, $81
	.byte $00, $85
	.byte $41, $2d
	.word @song1ref1826
	.byte $41, $1f
	.word @song1ref1842
	.byte $41, $18
	.word @song1ref1840
	.byte $41, $18
	.word @song1ref1885
	.byte $7a, $8a, $29, $bd, $2c, $bd, $2a, $dd, $29, $9d, $29, $bd, $2c, $bd, $2a, $dd, $29, $9d, $00, $fd, $ff
@song1ref1944:
	.byte $00, $85, $80, $35, $85, $5c, $85, $34, $85, $5c, $85, $33, $5c, $33, $5c, $87, $30, $85, $5c, $8d, $33, $8d, $5c, $8d
	.byte $3a, $8d, $8a, $2a, $bd, $29, $bd
	.byte $41, $19
	.word @song1ref1944
	.byte $00, $fd, $ff, $e7, $84, $29, $85, $5c, $85, $2d, $85, $5c, $95, $29, $85, $5c, $8d, $30, $8d, $5c, $95, $29, $85, $5c
	.byte $8d, $30, $8d, $5c, $95, $2a, $85, $5c, $8d, $31, $8d, $5c, $bd, $90
@song1ref2016:
	.byte $36, $81, $35, $81, $5c, $81, $33, $85, $5c, $81, $33, $81, $31, $81, $5c, $81, $30, $85, $5c, $81, $36, $85, $35, $85
	.byte $31, $81, $30, $81, $5c, $81, $2e, $85, $5c, $81, $2e, $81, $2c, $81, $5c, $81, $2a, $85, $5c, $81, $2a, $85, $2e, $85
	.byte $30, $81, $2e, $81, $5c, $81, $2d, $85, $5c, $81, $2d, $81, $2a, $81, $5c, $81, $29, $85, $5c, $81, $2d, $85, $30, $85
	.byte $2e, $8d, $30, $8d, $31, $8d, $35, $8d
	.byte $41, $47
	.word @song1ref2016
	.byte $c5, $42
	.word @song1ch11loop
@song1ch12:
	.byte $ff
@song1ch12loop:
	.byte $7b, $8c, $2e, $81, $5c, $81, $78, $2e, $81, $5c, $81, $76, $2e, $81, $5c, $81
@song1ref2121:
	.byte $7b, $31, $81, $5c, $81, $2e, $81, $5c, $81, $78
@song1ref2131:
	.byte $2e, $81, $5c, $81, $7b, $2c, $81, $5c, $81, $2e
@song1ref2141:
	.byte $81, $5c, $81, $2e, $81, $5c, $81, $78, $2e, $81, $5c, $81, $76, $2e, $81, $5c, $81, $7b, $35, $81, $5c, $81, $2e, $81
	.byte $5c, $81, $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c
	.byte $41, $0f
	.word @song1ref2141
	.byte $41, $28
	.word @song1ref2121
	.byte $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c
	.byte $41, $0f
	.word @song1ref2141
	.byte $41, $28
	.word @song1ref2121
	.byte $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c
	.byte $41, $0f
	.word @song1ref2141
	.byte $41, $28
	.word @song1ref2121
	.byte $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c
	.byte $41, $0f
	.word @song1ref2141
	.byte $41, $28
	.word @song1ref2121
	.byte $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c
	.byte $41, $0f
	.word @song1ref2141
	.byte $41, $28
	.word @song1ref2121
	.byte $79
	.byte $41, $18
	.word @song1ref2131
	.byte $41, $18
	.word @song1ref2121
	.byte $41, $18
	.word @song1ref1885
	.byte $2c, $81, $5c, $81, $00, $fd, $90, $31, $85, $5c, $81, $30, $85, $5c, $81, $2e, $85, $5c, $81, $30, $85, $5c, $81, $31
	.byte $85, $2e, $85, $30, $9d, $2c, $8d, $29, $8d, $00, $ed, $73, $51, $04, $a0, $84, $3a, $8d, $3a, $9d, $38, $8d, $36, $8d
	.byte $30, $9d, $2c, $8d, $29, $8d, $8a, $27, $9d, $29, $9d, $79, $29, $bd, $7b, $00, $9d, $27, $9d, $51, $fc, $00, $5c, $95
	.byte $a7, $7c, $8c
@song1ref2337:
	.byte $2e, $81, $7a, $2e, $81, $7b, $35, $81, $79, $35, $81, $3a, $81, $77, $3a, $81, $78, $35, $81, $76, $35, $81, $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
@song1ref2371:
	.byte $7c, $2a, $81, $7a, $2a, $81, $7b, $31, $81, $79, $31, $81, $36, $81, $77, $36, $81, $78, $31, $81, $76, $31, $81
	.byte $41, $10
	.word @song1ref2371
@song1ref2397:
	.byte $7c, $29, $81, $7a, $29, $81, $7b, $30, $81, $79, $30, $81, $35, $81, $77, $35, $81, $78, $30, $81, $76, $30, $81
	.byte $41, $10
	.word @song1ref2397
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $7c
	.byte $41, $10
	.word @song1ref2337
	.byte $41, $10
	.word @song1ref2371
	.byte $41, $10
	.word @song1ref2371
	.byte $41, $10
	.word @song1ref2397
	.byte $41, $10
	.word @song1ref2397
	.byte $7c
@song1ref2452:
	.byte $2a, $81, $5c, $81, $79, $2a, $81, $5c, $85, $76, $2a
@song1ref2463:
	.byte $81, $5c, $85, $7c, $27, $81, $5c, $81, $79, $27, $81, $5c, $85, $76, $27, $81, $5c, $85, $7c, $29, $81, $5c, $81, $79
	.byte $29, $81, $5c, $85, $76, $29, $81, $5c, $85, $7c, $25, $81, $5c, $81, $79, $25, $81, $5c, $85, $76, $25
	.byte $41, $13
	.word @song1ref2463
	.byte $79, $2b, $81, $5c, $85, $76, $2b, $81, $5c, $85, $7b, $84, $2e, $8d, $30, $8d, $31, $8d, $35, $8d, $7c, $8c
	.byte $41, $2d
	.word @song1ref2452
	.byte $41, $13
	.word @song1ref2463
	.byte $79, $2b, $81, $5c, $85, $76, $2b, $81, $7c, $2d, $81, $5c, $81, $76, $2d, $81, $5c, $b9, $42
	.word @song1ch12loop
@song1ch13:
	.byte $ff
@song1ch13loop:
	.byte $87, $7f, $96
@song1ref2565:
	.byte $16, $85, $7c, $0a, $5c, $83, $79, $0a, $5c, $ab, $7f, $19, $85, $7c, $0d, $5c, $83, $79, $0d, $5c, $a3, $87, $7f, $1b
	.byte $85, $7c, $0f, $5c, $83, $79, $0f, $5c, $ab, $7f, $12, $85, $5c, $95, $14, $85, $5c, $8d, $87
	.byte $41, $22
	.word @song1ref2565
	.byte $41, $22
	.word @song1ref2565
	.byte $41, $21
	.word @song1ref2565
	.byte $7b, $98
@song1ref2619:
	.byte $16, $85, $22, $81, $1d, $81, $20, $85, $22, $81, $16, $89, $22, $81, $1d, $81, $20, $85, $22, $81, $16, $81, $19, $85
	.byte $25, $81, $20, $81, $23, $85, $25, $81, $19, $89, $25, $81, $20, $81, $23, $85, $25, $81, $19, $81, $1b, $85, $27, $81
	.byte $22, $81, $25, $85, $27, $81, $1b, $89, $27, $81, $22, $81, $25, $85, $27, $81, $1b, $81, $1e, $89, $22, $89, $25, $85
	.byte $20, $89, $24, $89, $27, $85
	.byte $41, $4e
	.word @song1ref2619
	.byte $41, $15
	.word @song1ref2619
	.byte $89, $22, $81, $1d, $81, $20, $85, $22, $81, $16, $a1
@song1ref2714:
	.byte $1e, $8d, $5c, $85, $1e, $81, $1e, $81, $5c, $81, $1e, $85, $5c, $81, $1e, $85, $1b, $85, $5c, $85, $1d
@song1ref2735:
	.byte $81, $1d, $81, $5c, $81, $1d, $81, $5c, $81, $1d, $81, $1d, $81, $1d, $81, $20, $81, $24, $81, $29, $81, $24, $81, $20
	.byte $81, $1d, $81, $1b, $8d, $1b, $81, $1b, $81, $5c, $81, $16, $81, $1d, $85, $5c, $81, $1d, $81, $1d, $81, $1f, $81, $21
	.byte $81, $1d, $81, $16, $8d, $18, $8d, $19, $8d, $16, $81, $1a, $81, $1d, $81, $22, $81
	.byte $41, $56
	.word @song1ref2714
	.byte $00, $fd, $ff, $ff, $16, $8d, $18, $8d, $19, $8d, $1d, $8d, $16, $8d, $18, $8d, $19, $8d, $1d, $8d, $1b, $8d, $1d, $8d
	.byte $1e, $8d, $22, $8d, $1d, $8d, $1d, $81, $1d, $81, $5c
	.byte $41, $0d
	.word @song1ref2735
	.byte $21, $81, $24, $81, $29, $81, $1b, $9d, $18, $9d, $19, $9d, $16, $9d, $18, $9d, $15, $9d, $16, $8d, $18, $8d, $19, $8d
	.byte $1d, $8d, $1b, $99, $15, $85, $15, $85, $15, $81, $15, $81, $18, $81, $1d, $81, $21, $81, $22, $9d, $1e, $9d, $18, $9d
	.byte $15, $9d, $5c, $bd, $42
	.word @song1ch13loop
@song1ch14:
	.byte $7a, $88
@song1ref2898:
	.byte $25, $00, $87, $25, $00, $8b, $25, $00, $87, $25, $00, $93, $25, $00, $87, $25, $00, $8b, $25, $00, $87, $25, $00, $93
@song1ch14loop:
	.byte $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
@song1ref2931:
	.byte $83, $25, $00, $25, $00, $87, $25, $00, $25, $00, $87, $25, $00, $25, $00, $8f, $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
	.byte $41, $10
	.word @song1ref2931
	.byte $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
	.byte $41, $10
	.word @song1ref2931
	.byte $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
	.byte $41, $10
	.word @song1ref2931
	.byte $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
	.byte $41, $10
	.word @song1ref2931
	.byte $7a
	.byte $41, $18
	.word @song1ref2898
	.byte $7c
	.byte $41, $0e
	.word @song1ref2898
	.byte $41, $10
	.word @song1ref2931
	.byte $ff, $7f
@song1ref3004:
	.byte $25, $00, $a3, $25, $00, $93, $25, $00, $a3, $25, $79, $25, $7f, $25, $00, $87, $25, $00, $83, $25, $00, $9b, $25, $00
	.byte $83, $79, $25, $00, $87, $7f, $25, $00, $83, $79, $25, $00, $7f
@song1ref3041:
	.byte $25, $00, $8b, $25, $00, $8b, $25, $00, $83, $25, $79, $25, $7f, $25, $00, $83, $79, $25, $00, $83, $7f, $25, $00
	.byte $41, $32
	.word @song1ref3004
	.byte $ff
@song1ref3068:
	.byte $25, $00, $83, $25, $00, $8f, $25, $00, $83, $79, $25, $00, $7f, $25, $00, $93
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3041
	.byte $25, $00, $83, $25, $00
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0e
	.word @song1ref3068
	.byte $41, $0d
	.word @song1ref3068
	.byte $d3, $42
	.word @song1ch14loop
@song1ch15:
	.byte $7a, $8f, $88, $25, $00, $9b, $25, $00, $9b, $25, $00, $9b, $25, $00, $8b
@song1ch15loop:
@song1ref3151:
	.byte $7c, $8f, $25, $00, $9b, $25, $00, $9b, $25, $00, $9b, $25, $00, $25, $00, $83, $25, $00, $7a
@song1ref3170:
	.byte $8f, $25, $00, $9b, $25, $00, $9b, $25, $00, $9b, $25, $00, $8b
	.byte $41, $1e
	.word @song1ref3151
	.byte $41, $1e
	.word @song1ref3151
	.byte $41, $1e
	.word @song1ref3151
	.byte $41, $1e
	.word @song1ref3151
	.byte $41, $1e
	.word @song1ref3151
	.byte $ff
	.byte $41, $0d
	.word @song1ref3170
	.byte $8f, $25, $00, $9b, $25, $00, $cb
	.byte $41, $0d
	.word @song1ref3170
	.byte $8f, $25, $00, $9b, $25, $00, $cb, $ff
	.byte $41, $0d
	.word @song1ref3170
	.byte $41, $0d
	.word @song1ref3170
	.byte $41, $0d
	.word @song1ref3170
	.byte $41, $0d
	.word @song1ref3170
	.byte $41, $0d
	.word @song1ref3170
	.byte $8f, $25, $00, $9b, $25, $00, $cb
	.byte $41, $0d
	.word @song1ref3170
	.byte $8f, $25, $00, $9b, $25, $00, $cb, $42
	.word @song1ch15loop
@song1ch17:
	.byte $7a, $88
@song1ref3257:
	.byte $25, $00, $74, $25, $00, $25, $00, $25, $00, $7a, $25, $00, $74, $25, $00, $25, $00, $25, $00, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
@song1ch17loop:
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a, $25, $00, $83, $74, $25, $25, $25, $00, $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
@song1ref3351:
	.byte $7a, $25, $00, $74, $25, $00, $25, $00, $25, $00, $7a, $25, $00, $83, $74, $25, $25, $25, $00, $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $41, $0f
	.word @song1ref3351
	.byte $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $41, $0f
	.word @song1ref3351
	.byte $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $41, $0f
	.word @song1ref3351
	.byte $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $41, $0f
	.word @song1ref3351
	.byte $7a
	.byte $41, $0f
	.word @song1ref3257
	.byte $25
	.byte $41, $0f
	.word @song1ref3351
	.byte $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a, $25, $00, $83, $74, $25, $00, $83, $7a, $25, $00, $83, $74, $25, $25, $25, $00, $7a
	.byte $41, $10
	.word @song1ref3257
	.byte $7a, $25, $00, $83, $74, $25, $00, $83, $7b
@song1ref3540:
	.byte $25, $00, $73, $25, $00
@song1ref3545:
	.byte $25, $00, $25, $00, $7b, $25, $00, $73, $25, $00
@song1ref3555:
	.byte $25, $00, $25, $00, $7b, $25, $00, $73, $25, $00, $7b, $25, $00, $73, $25, $00, $25, $00, $7b, $25, $00, $73
	.byte $41, $10
	.word @song1ref3545
	.byte $41, $10
	.word @song1ref3555
	.byte $73, $25, $00, $25, $00, $7b, $25, $00, $73, $25, $00, $25, $00, $25, $00, $76
	.byte $41, $10
	.word @song1ref3540
	.byte $76
	.byte $41, $14
	.word @song1ref3540
	.byte $41, $10
	.word @song1ref3555
	.byte $73
	.byte $41, $10
	.word @song1ref3545
	.byte $41, $10
	.word @song1ref3555
	.byte $73
	.byte $41, $10
	.word @song1ref3545
	.byte $41, $10
	.word @song1ref3555
	.byte $73, $25, $00, $25, $00, $7b, $25, $00, $73, $25, $00, $25, $00, $25, $00, $76
	.byte $41, $10
	.word @song1ref3540
	.byte $76
	.byte $41, $14
	.word @song1ref3540
	.byte $41, $10
	.word @song1ref3555
	.byte $73, $25, $00, $25, $00, $7b, $25, $00, $73, $25, $00, $25, $00, $25, $00, $76
	.byte $41, $10
	.word @song1ref3540
	.byte $76
	.byte $41, $14
	.word @song1ref3540
	.byte $41, $10
	.word @song1ref3555
	.byte $73, $25, $00, $25, $00
@song1ref3680:
	.byte $7a, $25, $00, $83, $74, $25, $00, $25, $00, $7a, $25, $00, $83, $74, $25, $00, $7a, $25, $00, $83, $74, $25, $00, $25
	.byte $00, $83, $7a, $25, $00, $83, $74, $25, $00, $83
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $1a
	.word @song1ref3680
	.byte $41, $19
	.word @song1ref3680
	.byte $c3, $42
	.word @song1ch17loop
@song2ch0:
	.byte $46, $0a
@song2ch0loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch0loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $26, $27, $28, $29, $17, $18, $19, $1a, $1b, $11, $12, $13, $14, $15, $00, $1e, $1f, $20, $21, $00, $8f, $1c, $00, $83
	.byte $0b, $0c, $25, $05, $03, $06, $02, $04, $07, $16, $01, $0d, $09, $00, $83, $24, $00, $83, $10, $0f, $0a, $0e, $08, $00
	.byte $83, $23, $1d, $00, $81, $22, $00, $ff, $ff, $fb, $42
	.word @song2ch4loop
