// Generated by export.py using data in metadata.json

#if !__VS_SYSTEM

banked(sound_test_bank.musictext.data.0) const char musicSoundTestString00[15] = "Stay Inside Me";
banked(sound_test_bank.musictext.data.1) const char musicSoundTestString01[10] = "idfk lmao";


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsUpper[] = {
	NULL,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsLower[] = {
	musicSoundTestString00,
};


banked(sound_test_bank.musictext.ptr) const char* const xbgmtextsOriginalArtist[] = {
	musicSoundTestString01,
};


#else

const char* const xbgmtextsUpper[] = {};
const u8 xbgmtextsUpperSize[] = {};
const char* const xbgmtextsLower[] = {};
const u8 xbgmtextsLowerSize[] = {};
const char* const xbgmtextsOriginalArtist[] = {};
const u8 xbgmtextsOriginalArtistSize[] = {};

#endif




#if !__VS_SYSTEM

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
	song_stay_inside_me_epsm,
};

#else

banked(sound_test_bank.musictext.index) const u8 xbgmlookuptable[] = {
};

#endif
