; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music2:=music_data_famidash_music2

music_data_famidash_music2:
	.byte 2
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Menu Theme
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 262,218
; 01 : Scheming Weasel
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.word 335,279
; 02 : dpcm
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	.endif
	.word 307,256

.export music_data_famidash_music2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env14,@env15,@env17,@env0 ; 00 : blank string
	.word @env2,@env15,@env18,@env0 ; 01 : sample
	.word @env27,@env15,@env17,@env0 ; 02 : menu acc
	.word @env24,@env15,@env19,@env0 ; 03 : shift string
	.word @env12,@env15,@env17,@env0 ; 04 : triangle pluck 3
	.word @env6,@env4,@env20,@env0 ; 05 : hat
	.word @env11,@env4,@env17,@env0 ; 06 : rel hats
	.word @env1,@env15,@env17,@env0 ; 07 : echo
	.word @env13,@env15,@env17,@env0 ; 08 : loud blank string

@instruments_exp:


@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env3:
	.byte $00,$c0,$bd,$bb,$ba,$ba,$bc,$bf,$c1,$c4,$c6,$c6,$c5,$c3,$00,$01
@env4:
	.byte $bd,$c0,$00,$01
@env5:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env6:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env7:
	.byte $c0,$c4,$c4,$00,$00
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $00,$c0,$02,$bf,$05,$be,$0e,$bf,$05,$c0,$04,$c1,$05,$c2,$0e,$c1,$05,$c0,$c0,$00,$01
@env10:
	.byte $c0,$c1,$c1,$00,$00
@env11:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env12:
	.byte $00,$cf,$02,$c0,$00,$03
@env13:
	.byte $0b,$c6,$c8,$ca,$cb,$cc,$05,$cb,$cb,$00,$08,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c3,$c2,$c1,$c0,$00,$1b
@env14:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$14
@env15:
	.byte $c0,$7f,$00,$01
@env16:
	.byte $c0,$ca,$ca,$c0,$00,$00
@env17:
	.byte $7f,$00,$00
@env18:
	.byte $c2,$7f,$00,$00
@env19:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env20:
	.byte $c0,$c1,$00,$00
@env21:
	.byte $c0,$c0,$c6,$00,$00
@env22:
	.byte $c0,$c3,$c8,$00,$00
@env23:
	.byte $c0,$c3,$c3,$00,$00
@env24:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env25:
	.byte $c0,$c9,$c9,$c0,$00,$00
@env26:
	.byte $c0,$c3,$c7,$00,$00
@env27:
	.byte $00,$c8,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$06,$c1,$07,$c0,$00,$10

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 00 BSV (Pitch:11)
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0c,$40,$02 ; 01 BSV_1 (Pitch:12)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 02 fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 03 fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$04,$40,$00 ; 04 fdbass C (Pitch:4)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40,$00 ; 05 fdbass C (Pitch:7)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 06 fdbass C (Pitch:9)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 07 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 08 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40,$00 ; 09 fdbass C (Pitch:14)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0a fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 0b fdbass C# (Pitch:10)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 0c fdbass C# (Pitch:13)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0d fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$07,$40,$00 ; 0e fdbass D (Pitch:7)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 0f fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 10 fdkick (Pitch:14)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40,$01 ; 11 is a (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40,$01 ; 12 machine (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0b,$40,$01 ; 13 MUSIC_PCM_DS-geo (Pitch:11)
	.byte $4a+.lobyte(FAMISTUDIO_DPCM_PTR),$7a,$0a,$40,$02 ; 14 one (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 15 snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$01 ; 16 this (Pitch:15)
	.byte $68+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0a,$40,$01 ; 17 three (Pitch:10)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$01 ; 18 time (Pitch:15)
	.byte $69+.lobyte(FAMISTUDIO_DPCM_PTR),$52,$0a,$40,$02 ; 19 two (Pitch:10)

@song0ch0:
	.byte $46, $06
@song0ch0loop:
	.byte $47, $01, $79, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02, $84
@song0ref14:
	.byte $0d, $47, $01, $0d, $47, $01, $19, $47, $01, $0d, $47, $01, $0d, $81, $47, $01, $19, $47, $01, $25, $81, $47, $01, $74
	.byte $19, $47, $01, $25, $81, $47, $01, $72, $19, $47, $01, $25, $81, $47, $01, $71, $19, $47, $01, $79, $14, $47, $01, $14
	.byte $47, $01, $20, $47, $01, $14, $47, $01, $14, $81, $47, $01, $20, $47, $01, $2c, $81, $47, $01, $74, $20, $47, $01, $2c
	.byte $81, $47, $01, $72, $20, $47, $01, $2c, $81, $47, $01, $71, $20, $47, $01, $79, $12, $47, $01, $12, $47, $01, $1e, $47
	.byte $01, $12, $47, $01, $12, $81, $47, $01, $1e, $47, $01, $2a, $81, $47, $01, $12, $47, $01, $1e, $47, $01, $12, $47, $01
	.byte $72, $1e, $47, $01, $2a, $81, $00
@song0ref141:
	.byte $47, $01, $79, $10, $47, $01, $10, $47, $01, $1c, $47, $01, $10, $47, $01, $10, $81, $47, $01, $1c, $47, $01, $28, $81
	.byte $47, $01, $0f, $47, $01, $1b, $47, $01, $0f, $83, $47, $01, $1b, $81, $47, $01, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $4f, $02
	.byte $41, $3f
	.word @song0ref14
	.byte $47, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $02
	.byte $41, $3f
	.word @song0ref14
	.byte $47, $01, $4f, $02
	.byte $41, $20
	.word @song0ref14
	.byte $41, $09
	.word @song0ref141
	.byte $47, $01, $10, $47, $01, $1c, $47, $01, $10, $47, $01, $72, $1c, $47, $01, $28, $81, $00, $79, $49, .lobyte(@env3)
	.byte .hibyte(@env3), $4f, $02, $80, $0f, $99, $45, $81, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7a, $49, .lobyte(@env5), .hibyte(@env5), $4f, $01, $86
@song0ref251:
	.byte $0d, $97, $45, $83, $86, $14, $97, $45, $83, $12, $97, $45, $83, $10, $8b, $45, $0f, $8b, $45, $49, .lobyte(@env5)
	.byte .hibyte(@env5), $4f, $01
	.byte $41, $12
	.word @song0ref251
	.byte $49, .lobyte(@env5), .hibyte(@env5), $4f, $01
	.byte $41, $12
	.word @song0ref251
	.byte $49, .lobyte(@env5), .hibyte(@env5), $4f, $01, $0d, $99, $45, $81, $86, $14, $99, $45, $81, $10, $99, $45, $81, $49
	.byte .lobyte(@env9), .hibyte(@env9), $4f, $03, $80, $0f, $99, $45, $81, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $88
@song0ref319:
	.byte $19, $19, $25, $19, $19, $00, $25, $31, $00, $8d, $20, $20, $2c, $20, $20, $00, $2c, $38, $00, $8d, $1e, $1e, $2a, $1e
	.byte $1e, $00, $2a, $36, $00, $1e, $2a, $1e, $00, $85
@song0ref353:
	.byte $1c, $1c, $28, $1c, $1c, $00, $28, $34, $00, $1b, $27, $1b, $00, $81, $27, $00
	.byte $41, $32
	.word @song0ref319
	.byte $41, $32
	.word @song0ref319
	.byte $41, $14
	.word @song0ref319
	.byte $41, $09
	.word @song0ref353
	.byte $1c, $28, $1c, $00, $a5, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7c, $8a
@song0ref392:
	.byte $20, $81, $21, $81, $7a, $1e, $7c, $21, $7a, $23, $21, $81, $7c, $21, $81, $7a, $1f, $7c, $21, $81, $78, $21, $7a, $21
	.byte $23, $81, $7c, $21, $81, $7a, $1e, $7c, $21, $7a, $1c, $1e, $81, $7c, $1d, $81, $7a, $1f, $21, $81, $7c, $1e, $78, $23
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $20
	.word @song0ref392
	.byte $7c
	.byte $41, $14
	.word @song0ref392
	.byte $7a, $23, $89, $78, $8c, $23, $89, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref479:
	.byte $52, $41
@song0ref481:
	.byte $11, $85, $16, $81, $11, $83
@song0ref487:
	.byte $11, $11, $81, $16, $85, $11, $81, $11, $81, $16, $81, $11, $16, $81, $11, $11, $81, $16, $16, $16, $16
	.byte $41, $1b
	.word @song0ref481
	.byte $41, $1b
	.word @song0ref479
	.byte $41, $1b
	.word @song0ref481
	.byte $41, $1b
	.word @song0ref479
	.byte $41, $1b
	.word @song0ref481
	.byte $41, $1b
	.word @song0ref479
	.byte $11, $85, $16, $83, $11, $81
	.byte $41, $08
	.word @song0ref487
	.byte $85, $11, $85, $11, $81, $11, $85, $42
	.word @song0ch4loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch5loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch5loop
@song1ch0:
	.byte $46, $06
@song1ch0loop:
	.byte $4c, $ff
@song1ref6:
	.byte $7c, $4f, $00, $80
@song1ref10:
	.byte $19, $81, $47, $03, $1b, $81, $1c, $00, $47, $03, $4f, $01, $1e, $81, $4f, $02, $20, $00, $47, $03, $4f, $01, $21, $81
	.byte $4f, $02, $20, $00, $47, $03, $4f, $01, $1f, $81, $4f, $02, $20, $81, $47, $03, $4f, $01, $21, $81, $4f, $02, $20, $00
	.byte $47, $03, $4f, $01, $1e, $81, $1c, $00, $47, $03, $1b, $81, $4f, $00, $19, $81, $47, $03, $14, $81, $15, $81, $00, $91
	.byte $19, $81, $47, $05, $17, $47, $03, $15, $14, $81, $00, $99, $4f, $00
	.byte $41, $2c
	.word @song1ref10
@song1ref99:
	.byte $4f, $02
@song1ref101:
	.byte $1e, $81, $47, $03, $1d, $81, $1e, $81, $47, $03, $20, $81, $21, $81, $00, $81, $7a, $4b, .lobyte(@env26), .hibyte(@env26)
	.byte $82, $36, $78, $81, $76, $81, $74, $81, $7a, $4d, $36, $78, $81, $76, $81, $74, $81, $7a, $4b, .lobyte(@env22), .hibyte(@env22)
	.byte $36, $78, $81, $76, $81, $74, $81, $7a, $4b, .lobyte(@env26), .hibyte(@env26), $36, $78, $81, $76, $81, $74, $81, $72
	.byte $81, $71, $85, $7f, $4b, .lobyte(@env15), .hibyte(@env15), $4c, $80
	.byte $41, $0c
	.word @song1ref101
@song1ref173:
	.byte $25, $81, $00, $81, $20, $8d, $21, $81, $00, $89
	.byte $41, $1b
	.word @song1ref99
	.byte $74, $89, $7f, $4b, .lobyte(@env15), .hibyte(@env15), $4c
@song1ref193:
	.byte $80, $21, $81, $47, $03, $20, $81, $21, $81, $47, $03, $23, $81, $25, $81, $00, $81, $25, $81, $00, $81, $24, $8d, $20
	.byte $81, $00, $89, $7c, $4f, $00
	.byte $41, $2c
	.word @song1ref10
	.byte $4f, $00
	.byte $41, $2c
	.word @song1ref10
	.byte $75, $4f, $02, $87, $8e
@song1ref236:
	.byte $38, $83, $38, $3f, $95, $3f, $83, $40, $4c, $3f, $95, $38, $83, $38, $3f, $85, $40, $4c, $85, $3f, $8d, $40, $50, $8d
	.byte $87
	.byte $41, $0a
	.word @song1ref236
	.byte $40, $4c, $83, $40, $4d, $40, $4c, $85, $39, $85, $3f, $8d, $3d, $8d
	.byte $41, $2c
	.word @song1ref6
	.byte $4f, $00
	.byte $41, $2c
	.word @song1ref10
	.byte $41, $0c
	.word @song1ref99
@song1ref289:
	.byte $7a, $4b, .lobyte(@env26), .hibyte(@env26), $4f, $01, $82, $1e, $78, $81, $76, $81, $74, $81, $7a, $4d, $1e, $78, $81
	.byte $76, $81, $74, $81, $7a, $4b, .lobyte(@env22), .hibyte(@env22), $1e, $78, $81, $76, $81, $74, $81, $7a, $4b, .lobyte(@env26)
	.byte .hibyte(@env26), $1e, $78, $81, $76, $81, $74, $81, $72, $81, $71, $85, $7f, $4b, .lobyte(@env15), .hibyte(@env15)
	.byte $4c, $4f, $02, $80
	.byte $41, $0c
	.word @song1ref101
	.byte $41, $0a
	.word @song1ref173
	.byte $41, $0c
	.word @song1ref99
	.byte $41, $12
	.word @song1ref289
	.byte $7f, $4b, .lobyte(@env15), .hibyte(@env15), $4c, $4f, $02
	.byte $41, $16
	.word @song1ref193
	.byte $7c, $4f, $00
	.byte $41, $2c
	.word @song1ref10
	.byte $4f, $00
	.byte $41, $24
	.word @song1ref10
	.byte $24, $85, $25, $00, $83, $08, $83, $45, $01, $81, $45, $89, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $4c, $76, $4f, $03, $87, $4b, .lobyte(@env7), .hibyte(@env7), $90
@song1ref404:
	.byte $10, $45, $83, $4d, $10, $45, $83, $4d, $10, $45, $8b
@song1ref415:
	.byte $4d, $10, $45, $83, $4d, $10, $45, $83, $4d, $10, $45, $8b, $4d, $10, $45, $83, $4d, $10, $45, $83, $4d, $10, $45, $8b
	.byte $75, $4b, .lobyte(@env23), .hibyte(@env23), $10, $76, $81, $77, $81, $78, $81, $4b, .lobyte(@env7), .hibyte(@env7)
	.byte $10, $45, $8b, $87
	.byte $41, $12
	.word @song1ref415
@song1ref460:
	.byte $4b, .lobyte(@env23), .hibyte(@env23), $12, $45, $83, $4d, $12, $45, $83, $4d, $12, $45, $8b, $4b, .lobyte(@env7), .hibyte(@env7)
	.byte $10, $45, $83, $4d, $10, $45, $83, $4d, $10, $45, $83, $87
	.byte $41, $12
	.word @song1ref415
	.byte $41, $0e
	.word @song1ref460
@song1ref495:
	.byte $8b, $87, $4b, .lobyte(@env23), .hibyte(@env23)
@song1ref500:
	.byte $12, $45, $83, $4d, $12, $45, $83, $4d, $12, $45, $8b, $4d, $12, $45, $83, $4d, $12, $45, $83, $4d, $12, $45, $8b, $4d
	.byte $41, $11
	.word @song1ref500
	.byte $83, $87, $4d
	.byte $41, $12
	.word @song1ref500
@song1ref533:
	.byte $4d, $12, $45, $83, $4d, $12, $45, $83, $4b, .lobyte(@env10), .hibyte(@env10), $12, $45, $8b, $4b, .lobyte(@env21)
	.byte .hibyte(@env21), $0f, $45, $83, $4d, $0f, $45, $83, $4d, $0f, $45, $83, $00, $85, $4b, .lobyte(@env7), .hibyte(@env7)
	.byte $41, $12
	.word @song1ref404
	.byte $41, $13
	.word @song1ref460
	.byte $41, $12
	.word @song1ref415
	.byte $41, $0e
	.word @song1ref460
	.byte $8b, $87, $4b, .lobyte(@env25), .hibyte(@env25), $0b, $45, $83, $4d, $0b, $45, $83
@song1ref590:
	.byte $4d, $0c
@song1ref592:
	.byte $85, $4d, $0b, $45, $83, $4d, $0b, $45, $83, $4d, $0b, $45, $83, $00
	.byte $41, $0a
	.word @song1ref592
	.byte $41, $0c
	.word @song1ref590
	.byte $41, $0a
	.word @song1ref592
	.byte $41, $0b
	.word @song1ref590
	.byte $4d, $0b, $85, $4d, $0c, $45, $83, $4d, $0c, $45, $83, $4d, $0c, $45, $83, $4d, $0c, $45, $83, $4d, $0c, $85, $4b, .lobyte(@env16)
	.byte .hibyte(@env16), $0b, $45, $83, $4b, .lobyte(@env25), .hibyte(@env25), $0c, $45, $83, $4b, .lobyte(@env16), .hibyte(@env16)
	.byte $0b, $45, $83, $00, $85, $4b, .lobyte(@env7), .hibyte(@env7)
	.byte $41, $12
	.word @song1ref404
	.byte $41, $13
	.word @song1ref460
	.byte $41, $12
	.word @song1ref415
	.byte $41, $0e
	.word @song1ref460
	.byte $41, $14
	.word @song1ref495
	.byte $4d
	.byte $41, $11
	.word @song1ref500
	.byte $83, $87, $4d
	.byte $41, $12
	.word @song1ref500
	.byte $41, $14
	.word @song1ref533
	.byte $4b, .lobyte(@env7), .hibyte(@env7)
	.byte $41, $12
	.word @song1ref404
	.byte $41, $13
	.word @song1ref460
	.byte $41, $12
	.word @song1ref415
	.byte $41, $0e
	.word @song1ref460
	.byte $8b, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $ff, $ff, $ff, $ff, $bf, $7f, $80
@song1ref718:
	.byte $2a, $81, $47, $03, $29, $81, $2a, $81, $47, $03, $2c, $81, $2d, $81, $00, $81, $2a, $81, $00, $81, $2c, $8d, $27, $81
	.byte $00, $89, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf
	.byte $41, $18
	.word @song1ref718
	.byte $42
	.word @song1ch2loop
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
@song1ch3:
@song1ch3loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref793:
	.byte $06, $89, $00, $89, $05
@song1ref798:
	.byte $85, $06, $89, $00, $89, $05, $85, $06, $89, $00, $89, $05, $85, $06, $89, $00, $91
	.byte $41, $0c
	.word @song1ref793
@song1ref818:
	.byte $07, $89, $00, $89, $08, $85, $06, $89, $00, $91
	.byte $41, $0c
	.word @song1ref793
	.byte $41, $0a
	.word @song1ref818
@song1ref834:
	.byte $07, $89, $00, $89, $06
@song1ref839:
	.byte $85, $07, $89, $00, $89, $06, $85, $07, $89, $00, $89, $06, $85, $07, $89, $00, $91
	.byte $41, $10
	.word @song1ref834
	.byte $0f, $85, $08, $89, $00, $91
	.byte $41, $0c
	.word @song1ref793
@song1ref868:
	.byte $07, $85, $11, $47, $00, $11, $47, $02, $11, $00, $11, $00, $83, $08, $85, $06, $85, $11, $47, $00, $11, $47, $02, $11
	.byte $00, $11, $00, $8b
	.byte $41, $0c
	.word @song1ref793
	.byte $41, $14
	.word @song1ref868
	.byte $08, $85, $00, $ad, $0f, $85, $08, $85, $00, $ad, $0f, $85, $08, $85, $00, $ad, $08, $85, $0c, $81, $00, $b9
	.byte $41, $0c
	.word @song1ref793
@song1ref927:
	.byte $07, $85, $11, $00, $83, $16, $85, $08, $85, $06, $85, $11, $00, $83, $16, $85, $00
	.byte $41, $0d
	.word @song1ref798
	.byte $41, $11
	.word @song1ref927
	.byte $41, $10
	.word @song1ref839
	.byte $89, $06, $85, $07, $89, $00, $91
	.byte $41, $10
	.word @song1ref834
	.byte $0f, $85, $08, $89, $00, $91
@song1ref969:
	.byte $09, $89, $00, $89, $08, $85, $09, $89, $00, $89, $08, $85, $0d, $85, $11, $00, $83, $16, $85, $0a, $85, $09, $85, $11
	.byte $00, $83, $16, $85, $00, $85
	.byte $41, $1e
	.word @song1ref969
	.byte $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $01
@song2ch0loop:
	.byte $97, $97, $42
	.word @song2ch0loop
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
@song2ch3:
@song2ch2:
@song2ch1:
@song2ch1loop:
	.byte $97, $97, $42
	.word @song2ch1loop
@song2ch4:
@song2ch4loop:
	.byte $16, $11, $10, $0e, $0b, $04, $03, $17, $12, $19, $13, $01, $02, $18, $1a, $15, $00, $14, $00, $89, $42
	.word @song2ch4loop
