; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Shovel Knight Dig EPSM:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_shovel_knight_dig_epsm:=music_data_shovel_knight_dig_epsm

music_data_shovel_knight_dig_epsm:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 307,256

.export music_data_shovel_knight_dig_epsm
.global FAMISTUDIO_DPCM_PTR

@instruments:

@instruments_exp:
	.word @env4, @env7, @env0 ; 00 : 4A. Strings
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch0
	.word @env4, @env7, @env0 ; 01 : 56. Bell 2
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch1
	.word @env4, @env17, @env0 ; 02 : 39. Octave Piano
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch2
	.word @env1, @env7, @env0 ; 03 : 09. SSG Piano
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch3
	.word @env8, @env7, @env0 ; 04 : 0A. SSG Echoey
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch4
	.word @env4, @env7, @env0 ; 05 : 56. Bell 2 R
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch5
	.word @env4, @env7, @env0 ; 06 : 29. Crash Noise Short (B-7)
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch6
	.word @env4, @env7, @env0 ; 07 : 23. Hat Open 2 (D-6)
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch7
	.word @env4, @env7, @env0 ; 08 : 4D. Brass
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch8
	.word @env4, @env18, @env0 ; 09 : 4B. Timpani
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch9
	.word @env4, @env7, @env0 ; 0a : 3C. DX7 Epiano
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch10
	.word @env4, @env7, @env0 ; 0b : 48. Accordion
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch11
	.word @env4, @env7, @env0 ; 0c : 5D. Lead 3 R
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch12
	.word @env4, @env7, @env0 ; 0d : 5E. Lead 4
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch13
	.word @env4, @env7, @env0 ; 0e : 5D. Lead 3
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch14
	.word @env4, @env7, @env0 ; 0f : 3E. Epiano CP70
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch15
	.word @env4, @env7, @env0 ; 10 : 2A. Ride Cymbal (G#4)
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch16
	.word @env4, @env7, @env0 ; 11 : 57. Chimes
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch17
	.word @env9, @env7, @env0 ; 12 : 0E. SSG LongCrash
	.word @env12, @env19
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch18
	.word @env4, @env7, @env0 ; 13 : 0F. SSG PureNoise
	.word @env12, @env10
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch19
	.word @env6, @env7, @env0 ; 14 : 05. ClosedHat
	.word @env12, @env16
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch20
	.word @env4, @env7, @env0 ; 15 : 33. Bass 1
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch21
	.word @env4, @env7, @env0 ; 16 : 34. Bass 2
	.word @env15, @env7
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch22

@instrument_epsm_extra_patch0:
	.byte $3c,$c0,$71,$1f,$02,$00,$16,$00,$71,$16,$08,$00,$1a,$00,$31,$17,$1c,$00,$19,$00,$31,$16,$09,$00,$18,$00,$1b,$00,$18,$00,$00
@instrument_epsm_extra_patch1:
	.byte $24,$c0,$33,$1f,$08,$00,$f7,$00,$42,$9f,$07,$00,$f7,$00,$7e,$1f,$08,$00,$f7,$00,$74,$5f,$08,$00,$f6,$00,$28,$00,$2d,$00,$00
@instrument_epsm_extra_patch2:
	.byte $3d,$c0,$3c,$15,$05,$02,$2b,$00,$74,$18,$0c,$0a,$f8,$00,$7c,$15,$04,$02,$27,$00,$32,$18,$07,$04,$dd,$00,$28,$00,$23,$00,$00
@instrument_epsm_extra_patch3:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch4:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch5:
	.byte $24,$40,$33,$1f,$08,$00,$f7,$00,$42,$9f,$07,$00,$f7,$00,$7e,$1f,$08,$00,$f7,$00,$74,$5f,$08,$00,$f6,$00,$28,$00,$2d,$00,$00
@instrument_epsm_extra_patch6:
	.byte $38,$c0,$3f,$17,$02,$08,$f2,$00,$7c,$19,$02,$08,$f2,$00,$33,$1f,$02,$08,$f5,$00,$76,$17,$0a,$08,$f5,$00,$00,$0e,$04,$00,$00
@instrument_epsm_extra_patch7:
	.byte $3c,$c0,$7f,$1f,$00,$00,$00,$00,$0b,$1f,$0d,$0c,$ff,$00,$3c,$1f,$00,$00,$00,$00,$30,$1f,$16,$0c,$5f,$00,$05,$08,$00,$00,$00
@instrument_epsm_extra_patch8:
	.byte $3c,$c0,$32,$cd,$00,$00,$02,$00,$32,$1b,$0c,$00,$37,$00,$71,$d6,$00,$00,$04,$00,$72,$11,$02,$00,$3a,$00,$1e,$00,$1b,$00,$00
@instrument_epsm_extra_patch9:
	.byte $28,$c0,$36,$1f,$12,$00,$25,$00,$77,$1e,$0f,$00,$25,$00,$03,$1f,$04,$00,$15,$00,$04,$1f,$0c,$00,$d5,$00,$0a,$1b,$1f,$00,$00
@instrument_epsm_extra_patch10:
	.byte $3c,$c0,$3a,$1c,$1f,$06,$24,$00,$31,$da,$0c,$06,$38,$00,$71,$dc,$00,$00,$0a,$00,$71,$9a,$0b,$07,$34,$00,$22,$00,$17,$00,$00
@instrument_epsm_extra_patch11:
	.byte $3c,$c0,$76,$1f,$00,$00,$00,$00,$72,$0f,$10,$00,$2d,$00,$32,$1f,$00,$00,$00,$00,$33,$0e,$10,$00,$28,$00,$1d,$08,$19,$00,$00
@instrument_epsm_extra_patch12:
	.byte $3c,$40,$33,$1f,$00,$00,$00,$00,$31,$1f,$0a,$00,$1b,$00,$71,$1f,$00,$00,$00,$00,$71,$1f,$0a,$00,$1d,$00,$1c,$04,$15,$08,$00
@instrument_epsm_extra_patch13:
	.byte $34,$c0,$02,$1f,$09,$00,$60,$00,$01,$0f,$0b,$00,$7d,$00,$01,$1f,$05,$00,$50,$00,$01,$14,$0d,$00,$4d,$00,$1a,$03,$14,$00,$00
@instrument_epsm_extra_patch14:
	.byte $3c,$c0,$33,$1f,$00,$00,$00,$00,$31,$1f,$0a,$00,$1b,$00,$71,$1f,$00,$00,$00,$00,$71,$1f,$0a,$00,$1d,$00,$1c,$04,$15,$08,$00
@instrument_epsm_extra_patch15:
	.byte $2b,$c0,$73,$1f,$10,$00,$f7,$00,$64,$1b,$06,$00,$f6,$00,$33,$df,$04,$00,$f8,$00,$04,$5b,$07,$00,$f8,$00,$23,$2e,$11,$06,$00
@instrument_epsm_extra_patch16:
	.byte $2d,$c0,$7b,$19,$00,$00,$00,$00,$7f,$9f,$0e,$0a,$fa,$00,$32,$1f,$03,$19,$0f,$00,$39,$1f,$0c,$0d,$ff,$00,$00,$00,$00,$05,$00
@instrument_epsm_extra_patch17:
	.byte $3c,$c0,$7a,$1f,$15,$0c,$64,$00,$71,$1f,$10,$08,$37,$00,$3c,$1f,$15,$0c,$64,$00,$31,$1f,$10,$08,$37,$00,$0a,$00,$05,$00,$00
@instrument_epsm_extra_patch18:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch19:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch20:
	.byte $04,$c0,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$00,$1f,$00,$00,$07,$00,$20,$00,$20,$00,$00
@instrument_epsm_extra_patch21:
	.byte $38,$c0,$0a,$1f,$12,$00,$26,$00,$70,$1f,$0e,$04,$2f,$00,$30,$5f,$0a,$04,$26,$00,$00,$5f,$0a,$03,$29,$00,$24,$2d,$12,$00,$00
@instrument_epsm_extra_patch22:
	.byte $38,$c0,$06,$1f,$0d,$00,$2c,$00,$71,$1f,$09,$00,$8d,$00,$30,$1f,$08,$00,$8d,$00,$11,$5f,$0a,$00,$8e,$00,$21,$2c,$16,$00,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$ce,$cd,$cc,$07,$cb,$03,$ca,$ca,$c9,$02,$c8,$03,$c7,$02,$c6,$02,$c5,$c5,$c4,$02,$c3,$04,$c2,$c2,$c1,$0f,$c0,$00,$1d
@env2:
	.byte $00,$c0,$bd,$bb,$ba,$bb,$be,$c2,$c5,$c6,$c5,$c3,$00,$01
@env3:
	.byte $00,$c0,$b7,$b3,$b7,$c0,$c9,$cd,$c9,$00,$01
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$c2,$c7,$00,$00
@env6:
	.byte $00,$cf,$cb,$c7,$c5,$c3,$c2,$c2,$c0,$00,$08
@env7:
	.byte $c0,$7f,$00,$01
@env8:
	.byte $08,$cf,$cf,$cd,$04,$cd,$00,$05,$c3,$c9,$03,$c7,$c6,$c4,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$14
@env9:
	.byte $00,$cf,$03,$ce,$08,$cd,$0c,$cc,$0e,$cb,$09,$ca,$08,$c9,$08,$c8,$05,$c7,$03,$c6,$02,$c5,$c3,$c2,$c0,$00,$18
@env10:
	.byte $c7,$7f,$00,$00
@env11:
	.byte $7f,$00,$00
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@env14:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env15:
	.byte $c8,$7f,$00,$00
@env16:
	.byte $c3,$c1,$c3,$00,$02
@env17:
	.byte $b4,$7f,$00,$00
@env18:
	.byte $a8,$7f,$00,$00
@env19:
	.byte $c2,$c5,$c5,$c6,$02,$c7,$03,$c6,$c6,$c5,$0b,$c6,$c6,$c5,$c6,$02,$c5,$00,$10

@samples:

@song0ch0:
	.byte $46, $03, $bf
@song0ch0loop:
@song0ref5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch0loop
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch1:
	.byte $bf
@song0ch1loop:
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch1loop
@song0ch5:
	.byte $77, $86, $3d, $81, $31, $81, $78, $36, $81, $38, $81, $79, $3b, $81, $36, $81, $7a, $38, $81, $3d, $7b, $81, $36, $81
	.byte $38, $7c, $81, $31, $81, $36, $7d, $81, $38, $81, $3b, $7e, $81, $36, $81, $7f, $38, $81
@song0ch5loop:
	.byte $7e, $a8
@song0ref98:
	.byte $31, $81, $7a, $31, $81, $7c, $31, $81, $7a, $31, $81, $7c, $31, $81, $7a, $31, $81, $7e
	.byte $41, $0c
	.word @song0ref98
@song0ref119:
	.byte $7c, $31, $81, $7a, $31, $81, $7e, $31, $81, $7a, $31, $81, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $8d, $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $41, $08
	.word @song0ref119
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7e
	.byte $41, $0c
	.word @song0ref98
	.byte $7c, $31, $85, $78, $a6, $31, $79, $81, $7a, $81, $7c, $81, $7f, $a4, $31, $ff, $ff, $f5, $4e, $ff, $88, $36, $45, $38
	.byte $45, $39, $85, $49, .lobyte(@env14), .hibyte(@env14), $8b, $45, $81, $49, .lobyte(@env0), .hibyte(@env0), $4a, $88
	.byte $36, $45, $38, $45, $39, $87, $49, .lobyte(@env14), .hibyte(@env14), $87, $45, $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $88, $3b, $45, $39, $45, $38, $99, $49, .lobyte(@env13), .hibyte(@env13), $91, $43, $50, $64, $44, $20, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $87, $45, $85, $00, $ff, $ff, $ff, $fd
	.byte $41, $08
	.word @song0ref5
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch5loop
@song0ch6:
	.byte $bf
@song0ch6loop:
	.byte $83, $78, $86
@song0ref390:
	.byte $23, $85, $23, $85, $23, $85, $23, $81, $23, $85, $23, $81, $23, $85, $23, $85, $23
@song0ref407:
	.byte $85
@song0ref408:
	.byte $25, $85, $25, $85, $25
@song0ref413:
	.byte $85, $25, $81, $25, $85, $25, $81, $25, $85, $25, $8d, $27, $85, $27, $85, $27, $85, $27, $81, $27, $85, $27, $81, $27
	.byte $85, $27, $85, $27
	.byte $41, $11
	.word @song0ref407
	.byte $41, $0f
	.word @song0ref408
	.byte $41, $08
	.word @song0ref407
	.byte $41, $0a
	.word @song0ref413
	.byte $85, $25, $85
	.byte $41, $16
	.word @song0ref390
	.byte $2a, $85, $2a, $81, $2a, $85, $2a, $81, $2a, $85, $2a, $89, $45, $ff, $ff, $ff, $fd, $00, $ff, $ff, $ff, $fd
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $42
	.word @song0ch6loop
@song0ch7:
	.byte $ab, $4b, .lobyte(@env5), .hibyte(@env5), $88, $36, $7e, $81, $7d, $81, $7c, $81, $7b, $81, $7a, $81, $79, $81, $78
	.byte $85
@song0ch7loop:
	.byte $4c
@song0ref512:
	.byte $00, $ff, $ff, $ff, $fd, $ff, $ff, $ff, $ff, $7e, $4b, .lobyte(@env7), .hibyte(@env7), $4c
@song0ref526:
	.byte $19
@song0ref527:
	.byte $81
@song0ref528:
	.byte $0d, $81, $0d, $81, $0d, $81, $0d, $81, $0d, $81
	.byte $41, $0c
	.word @song0ref526
	.byte $41, $08
	.word @song0ref526
	.byte $1e
	.byte $41, $0b
	.word @song0ref527
	.byte $41, $0c
	.word @song0ref526
@song0ref551:
	.byte $0b, $81, $0d, $81, $0d, $81, $0d, $81, $1e
	.byte $41, $0b
	.word @song0ref527
	.byte $21
	.byte $41, $0b
	.word @song0ref527
	.byte $41, $08
	.word @song0ref528
	.byte $41, $08
	.word @song0ref551
	.byte $0d, $81, $0d, $81
	.byte $41, $0c
	.word @song0ref526
	.byte $0b, $81, $0b, $81, $0b, $81
	.byte $41, $08
	.word @song0ref551
	.byte $0d, $81, $0d, $81, $0d, $81
	.byte $41, $08
	.word @song0ref551
	.byte $0d, $81, $0d, $81
	.byte $41, $0c
	.word @song0ref526
	.byte $41, $08
	.word @song0ref528
	.byte $1e
	.byte $41, $0b
	.word @song0ref527
	.byte $41, $08
	.word @song0ref528
	.byte $0e
@song0ref616:
	.byte $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $1a
	.byte $41, $0c
	.word @song0ref616
	.byte $81, $0e, $81, $0e, $81, $0e, $81, $08, $81, $08, $81, $08
@song0ref643:
	.byte $81, $08, $81, $08, $81, $08, $81, $14
	.byte $41, $08
	.word @song0ref643
	.byte $81, $18, $81, $1b, $81, $1e, $81, $1e, $81, $20, $81, $7f
@song0ref666:
	.byte $25
@song0ref667:
	.byte $81
@song0ref668:
	.byte $19, $81, $19, $81, $19, $81, $19, $81, $19, $81
	.byte $41, $0c
	.word @song0ref666
	.byte $41, $08
	.word @song0ref666
	.byte $2a
	.byte $41, $0b
	.word @song0ref667
	.byte $41, $0c
	.word @song0ref666
@song0ref691:
	.byte $17, $81, $19, $81, $19, $81, $19, $81, $2a
	.byte $41, $0b
	.word @song0ref667
	.byte $2d
	.byte $41, $0b
	.word @song0ref667
	.byte $41, $08
	.word @song0ref668
	.byte $41, $08
	.word @song0ref691
	.byte $19, $81, $19, $81
	.byte $41, $0c
	.word @song0ref666
	.byte $17, $81, $17, $81, $17, $81, $17
@song0ref727:
	.byte $81, $15
@song0ref729:
	.byte $81, $15, $81, $15, $81, $15, $81, $15, $81, $15, $81, $21
	.byte $41, $0c
	.word @song0ref729
	.byte $41, $0d
	.word @song0ref727
	.byte $15, $81, $15, $81, $15, $81, $21
	.byte $41, $0c
	.word @song0ref729
	.byte $81, $15, $81, $15, $81, $15
@song0ref763:
	.byte $81, $14
@song0ref765:
	.byte $81, $14
@song0ref767:
	.byte $81, $14, $81, $14, $81, $14, $81, $14, $81, $20
	.byte $41, $0c
	.word @song0ref765
	.byte $41, $0d
	.word @song0ref763
	.byte $14, $81, $14, $81, $14, $81, $20
	.byte $41, $0c
	.word @song0ref765
	.byte $45, $20, $45, $2c, $81, $20, $81
	.byte $41, $09
	.word @song0ref512
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch7loop
@song0ch8:
	.byte $76, $51, $01, $70, $a2, $40, $55, $89, $40, $4e, $89, $40, $50, $81, $51, $01, $80, $87, $3d, $89, $36, $81, $38, $81
	.byte $3d, $85
@song0ch8loop:
	.byte $7a, $a0, $2d, $95, $77, $9e, $0d, $a5, $0f, $bd, $5c, $95, $10, $8d, $17, $85, $1e, $a5, $0f, $a5, $0e, $fd, $0d, $95
	.byte $19, $a5, $78, $80, $2e, $81, $75, $2e, $81, $2e, $81, $2e, $81, $78, $31, $81, $75, $31, $81, $31, $81, $31, $81, $78
	.byte $36, $81, $75, $36, $81, $36, $81, $36, $81, $78, $3a, $81, $75, $3a, $81, $3a, $81, $3a, $81, $00, $ff, $ff, $ff, $fd
	.byte $78
@song0ref910:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $2c, $89, $76, $83, $78, $2c, $81, $76, $83, $78, $34, $8d, $76, $87
	.byte $78, $34, $81, $33, $81, $31, $76, $33, $78, $34, $76, $31, $78
@song0ref942:
	.byte $36, $85, $31, $83, $5c, $31, $81, $5c, $81, $31, $8b, $49, .lobyte(@env2), .hibyte(@env2), $89, $5c, $8d, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $82, $2d, $89, $76, $83, $78, $2d, $81, $76, $83, $78, $36, $8d, $76, $87, $78, $36, $81, $34
	.byte $81, $36, $76, $81, $78, $39, $76, $81, $78
@song0ref991:
	.byte $38, $85, $31, $85, $31, $85, $31, $8b, $49, .lobyte(@env2), .hibyte(@env2), $99, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $82, $2c, $89, $76, $83, $78, $2c, $81, $76, $83, $78, $34, $89, $49, .lobyte(@env2), .hibyte(@env2), $8b, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $82
@song0ref1029:
	.byte $34, $81, $33, $5c, $31, $5c, $34, $5c, $36, $95, $49, .lobyte(@env2), .hibyte(@env2), $8f, $5c, $8d
@song0ref1045:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c
@song0ref1050:
	.byte $36, $5c, $38, $5c, $39, $85, $49, .lobyte(@env3), .hibyte(@env3), $8b, $5c, $81
	.byte $41, $09
	.word @song0ref1045
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $9c, $3b, $5c, $39, $5c, $38, $95, $49, .lobyte(@env2), .hibyte(@env2), $95
	.byte $43, $50, $dc, $44, $20, $83, $5c, $89
	.byte $41, $39
	.word @song0ref910
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $2d, $89, $76, $83, $78, $2d, $81, $76, $83, $78
@song0ref1106:
	.byte $38, $89, $49, .lobyte(@env2), .hibyte(@env2), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $82, $38, $81, $36, $5c
	.byte $34, $5c, $38, $5c, $36, $9d, $49, .lobyte(@env2), .hibyte(@env2), $8f, $5c, $8d, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $82, $38, $85, $5c, $85, $38, $81, $5c, $81, $3d, $89, $49, .lobyte(@env3), .hibyte(@env3), $8b, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $82, $3d, $5c, $3f, $81, $40, $4c, $81, $3d, $5c, $3f, $95, $49, .lobyte(@env2), .hibyte(@env2)
	.byte $95, $43, $50, $ca, $4b, $27, $83, $5c, $89
	.byte $41, $09
	.word @song0ref512
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch8loop
@song0ch9:
	.byte $73, $51, $04, $80, $9a, $40, $50, $8d, $43, $50, $d1, $50, $44, $8d, $82, $0d, $8d, $43, $50, $fd, $19, $01, $8b, $5c
@song0ch9loop:
	.byte $76, $84
@song0ref1217:
	.byte $20, $85, $20, $74, $85, $76, $20, $74, $85, $76, $20, $74, $81, $76, $20, $83, $74, $81, $76, $20, $74, $81, $76, $20
	.byte $74, $85, $76, $20, $81, $74, $83, $76, $20
@song0ref1250:
	.byte $81, $74, $83, $76, $22, $85, $22, $74, $85, $76, $22, $74, $85, $76, $22
@song0ref1265:
	.byte $74, $81, $76, $22, $83, $74, $81, $76, $22, $74, $81, $76, $22, $74, $85, $76, $22, $81, $74, $8b
@song0ref1285:
	.byte $76
@song0ref1286:
	.byte $23, $85, $23, $74, $85, $76, $23, $74, $85, $76, $23, $74, $81, $76, $23, $83, $74, $81, $76, $23, $74, $81, $76, $23
	.byte $74, $85, $76, $23, $81, $74, $83, $76, $23
	.byte $41, $14
	.word @song0ref1250
@song0ref1322:
	.byte $76, $21, $85, $21, $74, $85, $76, $21, $74, $85, $76, $21, $74, $81, $76, $21, $83, $74, $81, $76, $21, $74, $81, $76
	.byte $21, $74, $85, $76, $21, $81, $74, $83, $76, $21, $81, $74, $83
	.byte $41, $15
	.word @song0ref1322
	.byte $76
	.byte $41, $19
	.word @song0ref1217
	.byte $76, $25, $74, $85, $76, $25
	.byte $41, $0a
	.word @song0ref1265
	.byte $74, $83, $76, $22, $81, $74, $83, $78, $80, $28, $b5, $27, $81, $28, $81, $2a, $ad, $2e, $81, $2f, $81, $2e, $81, $2a
	.byte $81, $27, $bd, $25, $95, $2c, $8d, $31, $8d, $2d, $ad, $2c, $81, $2a, $81, $28, $81, $27, $81, $25, $81, $23, $81, $21
	.byte $95, $28, $8d, $2f, $8d, $2d, $ad, $28, $85, $2d, $85, $77, $2f, $9d, $2d, $95, $2c, $8d, $8b
@song0ref1442:
	.byte $8a, $2c, $89, $75, $83, $77, $2c, $81, $75, $83, $77, $34, $8d, $75, $87, $77, $34, $81, $33, $81, $31, $75, $33, $77
	.byte $34, $75, $31, $77
	.byte $41, $0e
	.word @song0ref942
@song0ref1473:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $2d, $89, $75, $83, $77, $2d, $81, $75, $83, $77, $36, $8d, $75, $87
	.byte $77, $36, $81, $34, $81, $36, $75, $81, $77, $39, $75, $81, $77
	.byte $41, $09
	.word @song0ref991
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $2c, $89, $75, $83, $77, $2c, $81, $75, $83, $77, $34, $89, $49, .lobyte(@env2)
	.byte .hibyte(@env2), $8b, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a
	.byte $41, $0d
	.word @song0ref1029
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $98
	.byte $41, $09
	.word @song0ref1050
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $98
	.byte $41, $09
	.word @song0ref1050
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $98, $3b, $5c, $39, $5c, $38, $95, $49, .lobyte(@env2), .hibyte(@env2), $9b
	.byte $5c, $89, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $11
	.word @song0ref1442
	.byte $77
	.byte $41, $0e
	.word @song0ref942
	.byte $41, $11
	.word @song0ref1473
	.byte $77
	.byte $41, $09
	.word @song0ref991
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a, $2d, $89, $75, $83, $77, $2d, $81, $75, $83, $77
	.byte $41, $27
	.word @song0ref1106
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $83, $5c, $89, $00, $ff, $ff, $ff, $f1
	.byte $41, $08
	.word @song0ref5
	.byte $42
	.word @song0ch9loop
@song0ch10:
	.byte $73, $51, $02, $80, $96, $31, $9f, $8d, $43, $50, $f0, $3d, $31, $89, $5c, $81
@song0ch10loop:
	.byte $76, $84
	.byte $41, $13
	.word @song0ref1286
@song0ref1646:
	.byte $81, $74, $83
@song0ref1649:
	.byte $76, $25, $85, $25, $74, $85, $76, $25, $74, $85, $76, $25, $74, $81, $76, $25, $83, $74, $81, $76, $25, $74, $81, $76
	.byte $25, $74, $85, $76, $25, $81, $74, $8b, $76, $27, $85, $27, $74, $85, $76, $27, $74, $85, $76, $27, $74, $81, $76, $27
	.byte $83, $74, $81, $76, $27, $74, $81, $76, $27, $74, $85, $76, $27, $81, $74, $83, $76, $27
	.byte $41, $14
	.word @song0ref1646
	.byte $41, $11
	.word @song0ref1649
	.byte $74, $83, $76, $25
	.byte $41, $13
	.word @song0ref1646
	.byte $74, $83, $76, $25, $81, $74, $83
	.byte $41, $13
	.word @song0ref1285
	.byte $81, $74, $83, $76, $25, $85, $25
@song0ref1745:
	.byte $74, $85, $76, $2a, $74, $85, $76, $2a, $74, $81, $76, $2a, $83, $74, $81, $76, $2a, $74, $81, $76, $2a, $74, $85, $76
	.byte $25, $81, $74, $83, $76, $25, $81, $74, $83
	.byte $41, $13
	.word @song0ref1285
	.byte $41, $27
	.word @song0ref1646
	.byte $41, $14
	.word @song0ref1646
	.byte $00, $ff, $fd
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch10loop
@song0ch11:
	.byte $73, $51, $02, $80, $80, $36, $9f, $8d, $43, $50, $eb, $42, $36, $89, $5c, $81
@song0ch11loop:
	.byte $76, $84
@song0ref1822:
	.byte $28, $85, $28, $74, $85, $76, $28, $74, $85, $76, $28, $74, $81, $76, $28, $83, $74, $81, $76, $28, $74, $81, $76, $28
	.byte $74, $85, $76, $28, $81, $74, $83, $76, $28, $81, $74, $83, $76, $2a, $85, $2a
	.byte $41, $0c
	.word @song0ref1745
@song0ref1865:
	.byte $76, $2a, $81, $74, $8b, $76, $2c, $85, $2c, $74, $85, $76, $2c, $74, $85, $76, $2c, $74, $81, $76, $2c, $83, $74, $81
	.byte $76, $2c, $74, $81, $76, $2c, $74, $85, $76, $2c, $81, $74, $83, $76, $2c, $81, $74, $83, $76, $2a, $85, $2a
	.byte $41, $0c
	.word @song0ref1745
	.byte $76, $2a, $81, $74, $8b, $76, $2a, $85, $2a
	.byte $41, $0c
	.word @song0ref1745
	.byte $76, $2a, $81, $74, $83, $76, $2a, $81, $74, $83, $76
	.byte $41, $15
	.word @song0ref1822
	.byte $76
	.byte $41, $18
	.word @song0ref1822
	.byte $74, $85, $76, $2e, $74, $85, $76, $2e, $74, $81, $76, $31, $83, $74, $81, $76, $31, $74, $81, $76, $31, $74, $85, $76
	.byte $36, $81, $74, $83, $76, $36, $81, $74, $83, $76
	.byte $41, $18
	.word @song0ref1822
	.byte $41, $0c
	.word @song0ref1745
	.byte $41, $1b
	.word @song0ref1865
	.byte $41, $0c
	.word @song0ref1745
	.byte $76, $2a, $81, $74, $8b, $00, $ff, $fd
	.byte $41, $08
	.word @song0ref5
	.byte $41, $08
	.word @song0ref5
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch11loop
@song0ch12:
	.byte $73, $51, $02, $80, $80, $38, $9f, $8d, $43, $50, $e8, $44, $38, $89, $5c, $81
@song0ch12loop:
	.byte $00, $95, $79, $94
@song0ref2032:
	.byte $2c, $85, $5c, $85, $33, $85, $77, $2c, $85, $79, $31, $85, $77, $33, $85, $79, $2c, $85, $77, $31, $85, $79, $2a, $85
	.byte $5c, $85, $31, $85, $5c, $85, $00, $9d
	.byte $41, $14
	.word @song0ref2032
	.byte $00, $ff, $ff, $95, $ff, $ff, $ff, $e7, $7a, $92, $14, $81, $14, $81, $14, $85, $14, $81, $14, $81, $19, $ff, $ed, $17
	.byte $8d, $19, $f5, $77, $90
@song0ref2096:
	.byte $26, $5c, $28, $5c, $2a, $91, $5c, $81
	.byte $41, $08
	.word @song0ref2096
	.byte $2c, $5c, $2a, $5c, $2a, $8d, $25, $8d, $24, $8d, $20, $85, $5c, $85
	.byte $41, $09
	.word @song0ref512
	.byte $41, $08
	.word @song0ref5
	.byte $42
	.word @song0ch12loop
@song0ch13:
	.byte $9f, $8e, $3f, $89, $7a, $8c, $40, $60, $89, $aa, $23, $81, $43, $50, $0e, $2f, $31, $43, $25
@song0ch13loop:
	.byte $79, $aa
@song0ref2152:
	.byte $19, $85, $19, $83, $5c, $19, $81, $5c, $81, $25, $5c, $19, $81, $5c, $81, $19
@song0ref2168:
	.byte $5c, $19, $83, $5c, $19, $85, $25, $81, $5c, $81, $1b, $85, $1b, $81, $5c, $81, $1b, $83, $5c
@song0ref2187:
	.byte $27, $5c, $1b, $81, $5c, $81, $1b, $5c, $1b, $83, $5c, $1b, $85, $27, $81, $5c, $81
@song0ref2204:
	.byte $1c, $85, $1c, $83, $5c, $1c, $81, $5c, $81, $28, $5c, $1c, $81, $5c, $81, $1c, $5c, $1c, $83, $5c, $1c, $85, $28, $81
	.byte $5c, $81, $1b, $85, $1b, $83, $5c, $1b, $81, $5c, $81
	.byte $41, $11
	.word @song0ref2187
@song0ref2242:
	.byte $1a, $85, $1a, $83, $5c, $1a, $81, $5c, $81, $15, $5c, $1a, $81, $5c, $81, $15, $5c, $1a, $83, $5c, $1a, $85, $26, $81
	.byte $5c, $81
	.byte $41, $16
	.word @song0ref2242
	.byte $17, $81, $5c, $81
	.byte $41, $09
	.word @song0ref2152
	.byte $14, $5c, $19, $81, $5c, $81, $14
	.byte $41, $0a
	.word @song0ref2168
@song0ref2288:
	.byte $14, $85, $14, $83, $5c, $14, $81, $5c, $81, $14, $5c, $14, $81, $5c, $81, $14, $5c, $1e, $81, $20, $5c, $2a, $81, $43
	.byte $50, $15, $36, $38, $43, $2c, $23, $81, $25, $81
	.byte $41, $2f
	.word @song0ref2152
	.byte $81, $20, $81, $43, $50, $0c, $2c, $2e, $43, $22, $43, $50, $23, $2e, $33, $43, $27
	.byte $41, $23
	.word @song0ref2204
	.byte $2c, $81, $20, $81, $5c, $81, $1b, $5c, $14, $83, $5c, $1b, $85, $20
@song0ref2359:
	.byte $81, $5c, $81, $1e, $85, $1e, $83, $5c, $1e, $81, $5c, $81, $2a
@song0ref2372:
	.byte $5c, $1e, $81, $5c, $81, $1e, $5c, $1e, $83, $5c, $19, $85, $1e, $81, $5c, $81, $17, $85, $17, $83, $5c, $17, $81, $5c
	.byte $81, $1e, $5c, $23, $81, $5c, $81, $23, $5c, $23, $83, $5c, $23, $85, $25
	.byte $41, $0c
	.word @song0ref2359
	.byte $1e
	.byte $41, $0a
	.word @song0ref2372
	.byte $1e, $85, $1e, $81, $43, $50, $0b, $2a, $2c, $43, $20
	.byte $41, $0b
	.word @song0ref2288
	.byte $20, $81, $5c, $81, $20, $5c, $14, $81, $14, $5c, $20, $81, $20, $81, $14, $81, $14, $5c, $78, $ac
@song0ref2452:
	.byte $25
@song0ref2453:
	.byte $48, $02, $81
@song0ref2456:
	.byte $19, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81
	.byte $41, $0c
	.word @song0ref2452
	.byte $41, $08
	.word @song0ref2452
	.byte $2a
	.byte $41, $0b
	.word @song0ref2453
	.byte $41, $0c
	.word @song0ref2452
@song0ref2489:
	.byte $17, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81, $2a
	.byte $41, $0b
	.word @song0ref2453
	.byte $2d
	.byte $41, $0b
	.word @song0ref2453
	.byte $41, $08
	.word @song0ref2456
	.byte $41, $08
	.word @song0ref2489
	.byte $19, $48, $02, $81, $19, $48, $02, $81
	.byte $41, $0c
	.word @song0ref2452
	.byte $17, $48, $02, $81, $17, $48, $02, $81, $17, $48, $02, $81
	.byte $41, $08
	.word @song0ref2489
	.byte $19, $48, $02, $81, $19, $48, $02, $81, $19, $48, $02, $81
	.byte $41, $08
	.word @song0ref2489
	.byte $19, $48, $02, $81, $19, $48, $02, $81
	.byte $41, $0c
	.word @song0ref2452
	.byte $41, $08
	.word @song0ref2456
	.byte $2a
	.byte $41, $0b
	.word @song0ref2453
	.byte $41, $08
	.word @song0ref2456
	.byte $1a
@song0ref2582:
	.byte $48, $02, $81, $1a, $48, $02, $81, $1a, $48, $02, $81, $1a, $48, $02, $81, $1a, $48, $02, $81, $1a, $48, $02, $81, $26
	.byte $41, $0c
	.word @song0ref2582
	.byte $48, $02, $81, $1a, $48, $02, $81, $1a, $48, $02, $81, $1a
@song0ref2621:
	.byte $48, $02, $81, $14
@song0ref2625:
	.byte $48, $02, $81, $14, $48, $02, $81, $14
@song0ref2633:
	.byte $48, $02, $81, $14, $48, $02, $81, $14, $48, $02, $81, $14, $48, $02, $81, $20
	.byte $41, $08
	.word @song0ref2633
	.byte $48, $02, $81, $24, $48, $02, $81, $27, $48, $02, $81, $2a, $48, $02, $81, $2a, $48, $02, $81, $2c, $48, $02, $81
	.byte $41, $0c
	.word @song0ref2452
	.byte $41, $0c
	.word @song0ref2452
	.byte $41, $08
	.word @song0ref2452
	.byte $2a
	.byte $41, $0b
	.word @song0ref2453
	.byte $41, $0c
	.word @song0ref2452
	.byte $41, $09
	.word @song0ref2489
	.byte $41, $0b
	.word @song0ref2453
	.byte $2d
	.byte $41, $0b
	.word @song0ref2453
	.byte $41, $08
	.word @song0ref2456
	.byte $41, $08
	.word @song0ref2489
	.byte $19, $48, $02, $81, $19, $48, $02, $81
	.byte $41, $0c
	.word @song0ref2452
	.byte $17, $48, $02, $81, $17, $48, $02, $81, $17, $48, $02, $81, $17
@song0ref2731:
	.byte $48, $02, $81, $15
@song0ref2735:
	.byte $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $21
	.byte $41, $0c
	.word @song0ref2735
	.byte $41, $0d
	.word @song0ref2731
	.byte $15, $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $21
	.byte $41, $0c
	.word @song0ref2735
	.byte $48, $02, $81, $15, $48, $02, $81, $15, $48, $02, $81, $15
	.byte $41, $0e
	.word @song0ref2621
	.byte $41, $0c
	.word @song0ref2625
	.byte $41, $0d
	.word @song0ref2621
	.byte $14, $48, $02, $81, $14, $48, $02, $81, $14, $48, $02, $81, $20, $48, $02, $81, $14, $48, $02
	.byte $41, $0a
	.word @song0ref767
	.byte $5c, $20, $5c, $2c, $81, $20, $81
	.byte $41, $09
	.word @song0ref512
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch13loop
