; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Famidash music:
; FAMISTUDIO_EXP_EPSM = 1
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1
; FAMISTUDIO_USE_PHASE_RESET = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_famidash_music1:=music_data_famidash_music1

music_data_famidash_music1:
	.byte 5
	.word @instruments
	.word @instruments_exp
	.word @samples-5
; 00 : Stereo Madness
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.word 327,273
; 01 : Jumper
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.word 364,303
; 02 : Electroman Adventures
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	.endif
	.word 348,290
; 03 : Desert City
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song3ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song3ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song3ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song3ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song3ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song3ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song3ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song3ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song3ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song3ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song3ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song3ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song3ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song3ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song3ch19
	.endif
	.word 176,146
; 04 : Casual Game Music 09
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song4ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song4ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song4ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song4ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song4ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song4ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song4ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song4ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song4ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song4ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song4ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song4ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song4ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song4ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song4ch19
	.endif
	.word 194,162
; 05 : dpcm
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song5ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song5ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song5ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song5ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song5ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song5ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song5ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song5ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song5ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song5ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song5ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song5ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song5ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song5ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song5ch19
	.endif
	.word 307,256

.export music_data_famidash_music1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env9,@env40,@env0 ; 00 : hat
	.word @env21,@env9,@env31,@env0 ; 01 : rel hats
	.word @env22,@env30,@env3,@env0 ; 02 : snare
	.word @env11,@env41,@env31,@env0 ; 03 : kick
	.word @env19,@env25,@env31,@env0 ; 04 : blank
	.word @env1,@env9,@env31,@env0 ; 05 : shaker
	.word @env49,@env25,@env31,@env0 ; 06 : triangle pluck 2
	.word @env28,@env25,@env4,@env0 ; 07 : pizzicato
	.word @env36,@env25,@env31,@env35 ; 08 : cut string 2
	.word @env27,@env25,@env31,@env0 ; 09 : triangle pluck
	.word @env29,@env25,@env31,@env0 ; 0a : clap no app
	.word @env5,@env25,@env33,@env0 ; 0b : sample
	.word @env2,@env25,@env31,@env0 ; 0c : echo
	.word @env29,@env32,@env31,@env0 ; 0d : clap
	.word @env23,@env25,@env31,@env0 ; 0e : loud blank string
	.word @env19,@env25,@env7,@env0 ; 0f : electroman lead
	.word @env39,@env6,@env31,@env0 ; 10 : tight triangle kick
	.word @env17,@env25,@env20,@env0 ; 11 : hex guitar 2
	.word @env42,@env9,@env3,@env0 ; 12 : cymbal
	.word @env17,@env25,@env31,@env0 ; 13 : DMC: drums + bass
	.word @env37,@env25,@env31,@env0 ; 14 : Instrument 1
	.word @env26,@env25,@env31,@env0 ; 15 : infernoplex_piano
	.word @env47,@env25,@env31,@env0 ; 16 : blank instant decay
	.word @env38,@env46,@env33,@env0 ; 17 : octave arp
	.word @env43,@env25,@env34,@env0 ; 18 : shift string
	.word @env21,@env25,@env31,@env0 ; 19 : Instrument 2
	.word @env17,@env25,@env8,@env0 ; 1a : hex guitar 1
	.word @env18,@env25,@env31,@env0 ; 1b : lots of hits
	.word @env16,@env25,@env31,@env0 ; 1c : 02 but tri
	.word @env12,@env25,@env31,@env0 ; 1d : blank vol rise

@instruments_exp:


@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c3,$c6,$c8,$c3,$c0,$00,$05
@env2:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env3:
	.byte $c1,$c0,$00,$01
@env4:
	.byte $c1,$c2,$00,$01
@env5:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env6:
	.byte $da,$d0,$ce,$c4,$00,$03
@env7:
	.byte $c2,$c1,$03,$c0,$02,$c0,$00,$01
@env8:
	.byte $c3,$c2,$c1,$c2,$c2,$c1,$00,$02
@env9:
	.byte $bd,$c0,$00,$01
@env10:
	.byte $00,$c8,$c4,$c2,$c0,$00,$04
@env11:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env12:
	.byte $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$0f
@env13:
	.byte $c0,$c4,$c4,$00,$00
@env14:
	.byte $c0,$c4,$c7,$00,$00
@env15:
	.byte $00,$c0,$c0,$bf,$03,$c0,$c0,$c1,$03,$c0,$00,$01
@env16:
	.byte $00,$c4,$02,$c5,$02,$c6,$02,$c0,$c5,$03,$c4,$03,$c0,$00,$0c
@env17:
	.byte $00,$cf,$7f,$00,$02
@env18:
	.byte $0c,$c9,$c5,$c3,$c2,$c1,$c9,$c5,$c3,$c2,$00,$01,$c9,$c7,$c6,$c5,$c4,$c4,$c3,$00,$12
@env19:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env20:
	.byte $c3,$c2,$c1,$c3,$00,$03
@env21:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env22:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env23:
	.byte $0b,$c6,$c8,$ca,$cb,$cc,$05,$cb,$cb,$00,$08,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c3,$c2,$c1,$c0,$00,$1b
@env24:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env25:
	.byte $c0,$7f,$00,$01
@env26:
	.byte $00,$ce,$02,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$00,$10
@env27:
	.byte $00,$cf,$c0,$00,$02
@env28:
	.byte $00,$c8,$c6,$c5,$c4,$c3,$03,$c2,$04,$c1,$00,$09
@env29:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env30:
	.byte $c6,$cc,$00,$01
@env31:
	.byte $7f,$00,$00
@env32:
	.byte $bc,$c1,$c0,$00,$02
@env33:
	.byte $c2,$7f,$00,$00
@env34:
	.byte $c1,$c2,$c1,$c0,$00,$00
@env35:
	.byte $00,$c2,$7f,$00,$02
@env36:
	.byte $00,$c4,$c5,$c6,$c6,$c7,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0d
@env37:
	.byte $00,$c3,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env38:
	.byte $00,$c9,$c7,$c5,$00,$03
@env39:
	.byte $00,$cf,$03,$c0,$00,$03
@env40:
	.byte $c0,$c1,$00,$00
@env41:
	.byte $c9,$cf,$00,$01
@env42:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env43:
	.byte $08,$c4,$c5,$c6,$08,$c5,$00,$05,$c5,$04,$c4,$07,$c3,$05,$c2,$02,$c1,$02,$c0,$00,$12
@env44:
	.byte $c0,$c3,$c7,$00,$00
@env45:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@env46:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env47:
	.byte $00,$cf,$cf,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env48:
	.byte $c0,$c5,$c5,$00,$00
@env49:
	.byte $00,$cf,$cf,$c0,$00,$03

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$a8,$0b,$40,$02 ; 00 BSV (Pitch:11)
	.byte $2a+.lobyte(FAMISTUDIO_DPCM_PTR),$7f,$0c,$40,$02 ; 01 BSV_1 (Pitch:12)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 02 fdbass A# (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40,$00 ; 03 fdbass B (Pitch:13)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40,$00 ; 04 fdbass B (Pitch:15)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 05 fdbass C (Pitch:9)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 06 fdbass C (Pitch:10)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 07 fdbass C (Pitch:12)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40,$00 ; 08 fdbass C (Pitch:13)
	.byte $35+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 09 fdbass C (Pitch:15)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$08,$40,$00 ; 0a fdbass C# (Pitch:8)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40,$00 ; 0b fdbass C# (Pitch:9)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40,$00 ; 0c fdbass C# (Pitch:10)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40,$00 ; 0d fdbass C# (Pitch:12)
	.byte $47+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40,$00 ; 0e fdbass C# (Pitch:15)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40,$00 ; 0f fdbass D (Pitch:10)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40,$00 ; 10 fdbass D (Pitch:11)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0d,$40,$00 ; 11 fdbass D (Pitch:13)
	.byte $59+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40,$00 ; 12 fdbass D (Pitch:15)
	.byte $6b+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40,$00 ; 13 fdkick (Pitch:14)
	.byte $0f+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40,$01 ; 14 is a (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40,$01 ; 15 machine (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0b,$40,$01 ; 16 MUSIC_PCM_DS-geo (Pitch:11)
	.byte $4a+.lobyte(FAMISTUDIO_DPCM_PTR),$7a,$0a,$40,$02 ; 17 one (Pitch:10)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$34,$00 ; 18 snare (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40,$01 ; 19 this (Pitch:15)
	.byte $68+.lobyte(FAMISTUDIO_DPCM_PTR),$58,$0a,$40,$01 ; 1a three (Pitch:10)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40,$01 ; 1b time (Pitch:15)
	.byte $69+.lobyte(FAMISTUDIO_DPCM_PTR),$52,$0a,$40,$02 ; 1c two (Pitch:10)

@song0ch0:
	.byte $46, $06, $53, $4f, $00
@song0ref6:
	.byte $98
@song0ref7:
	.byte $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $25, $81, $2c, $81, $20, $81, $27, $81, $20, $81, $27, $81
	.byte $20, $81, $27, $81, $20, $81, $27, $81, $4f, $01, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81, $29, $81, $22, $81
	.byte $29, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $1e, $81, $25, $81, $4f, $02
	.byte $41, $40
	.word @song0ref7
@song0ref78:
	.byte $4f, $01, $25, $00
@song0ref82:
	.byte $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f, $2c, $75, $25, $7f, $25, $75, $2c, $7f
	.byte $2c, $75, $25, $7f, $20, $75, $2c, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $20, $75, $27, $7f
	.byte $27, $75, $20, $7f, $20, $75, $27, $7f, $27, $75, $20, $7f, $22, $75, $27, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f
	.byte $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $22, $75, $29, $7f, $29, $75, $22, $7f, $1e, $75, $29, $7f
	.byte $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f, $25, $75, $1e, $7f, $1e, $75, $25, $7f
	.byte $25, $75, $1e, $7f, $4f, $01, $25, $75, $25, $7f
	.byte $41, $3e
	.word @song0ref82
	.byte $45, $9d, $7f
	.byte $41, $42
	.word @song0ref78
	.byte $7f
	.byte $41, $40
	.word @song0ref82
	.byte $7f
	.byte $41, $40
	.word @song0ref82
	.byte $7f
	.byte $41, $3e
	.word @song0ref82
	.byte $45, $fd, $ff, $76, $4f, $03, $a8
@song0ref240:
	.byte $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $30, $83, $30, $83, $30, $83, $30, $83, $30, $81, $31, $77
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $81, $78, $81, $33, $83, $33, $83, $33, $83, $33, $83, $33, $81, $79
	.byte $31, $83, $31, $83, $31, $81, $7a, $81, $31, $83, $7b, $31, $83, $31, $83, $30, $81, $7c, $81, $30, $83, $30, $83, $30
	.byte $7d, $83, $30, $81, $31
@song0ref317:
	.byte $83, $31, $83, $31, $83, $31, $83, $31, $83, $31, $83, $33, $83, $33, $83, $33, $83, $35, $7e, $83, $35, $81, $7f, $4f
	.byte $03
	.byte $41, $17
	.word @song0ref240
	.byte $41, $11
	.word @song0ref317
	.byte $33, $83, $33, $81
	.byte $41, $17
	.word @song0ref240
	.byte $41, $12
	.word @song0ref317
	.byte $83, $35, $81, $45, $87, $44, $00
@song0ch1:
	.byte $78, $53, $4f, $03
	.byte $41, $14
	.word @song0ref6
	.byte $4f, $01, $20, $81, $27, $81, $20, $81, $27, $71, $20, $78, $20, $71, $27, $78, $27, $71, $20, $78, $22, $71, $27, $78
	.byte $29, $71, $22, $78, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $29, $76, $29, $71, $22, $76, $22, $71, $88, $29
	.byte $76, $98, $29, $71, $88, $22, $76, $4f, $03, $98, $1e, $71, $88, $29, $76, $98, $25, $71, $88, $1e, $76, $98, $1e, $71
	.byte $88, $25, $76, $98, $25, $71, $88, $1e, $76, $98, $1e, $71, $88, $25, $76, $98, $25, $71, $88, $1e, $76, $98, $1e, $71
	.byte $88, $25, $76, $98, $25, $71, $88, $1e, $76, $98, $25, $71, $a6, $1e, $76, $98, $2c, $71, $88, $25, $76, $98, $25, $71
	.byte $88, $2c, $76, $98, $2c, $71, $88, $25, $76, $98, $25, $71, $88, $2c, $76, $98, $2c, $71, $88, $25, $76, $98, $25, $71
	.byte $88, $2c, $76, $98, $2c, $71, $88, $25, $76, $4f, $01, $98, $20, $71, $88, $2c, $76, $98, $27, $71, $88, $20, $76, $98
	.byte $20, $71, $88, $27, $76, $98, $27, $71, $88, $20, $76, $98, $20, $72, $88, $27, $76, $98, $27, $72, $88, $20, $76, $98
	.byte $20, $72, $88, $27, $76, $98, $27, $72, $88, $20, $76, $98, $22, $72, $88, $27, $76, $98, $29, $72, $88, $22, $76, $98
	.byte $22, $72, $88, $29, $76, $98, $29, $72, $88, $22, $76, $98, $22, $72, $88, $29, $76, $98, $29, $72, $88, $22, $76, $98
	.byte $22, $72, $88, $29, $76, $98, $29, $72, $88, $22, $76, $98, $1e, $72, $88, $29, $76, $98, $25, $72, $88, $1e, $76, $98
	.byte $1e, $72, $88, $25, $76, $98, $25, $72, $88, $1e, $76, $98, $1e, $72, $88, $25, $76, $98, $25, $72, $88, $1e, $76, $98
	.byte $1e, $72, $88, $25, $76, $98, $25, $72, $88, $1e, $7a, $4b, .lobyte(@env14), .hibyte(@env14), $b0, $19, $9d, $4d, $14
	.byte $9d, $4b, .lobyte(@env44), .hibyte(@env44), $16, $9d, $4b, .lobyte(@env14), .hibyte(@env14), $12, $9d, $4d, $19, $9d
	.byte $4d, $14, $9d, $4b, .lobyte(@env44), .hibyte(@env44), $16, $9d, $4b, .lobyte(@env14), .hibyte(@env14), $12, $9d, $45
	.byte $9d, $7c, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $4f, $03, $ac
@song0ref717:
	.byte $25, $81, $25, $81, $25, $81, $25, $25, $25, $25, $83, $25, $81, $25, $25, $83, $24, $83, $24, $83, $24, $24, $83, $24
	.byte $83, $24, $25, $81, $25, $81, $25, $81, $25, $25, $81, $25, $83, $25, $81, $25, $25, $25, $81, $27, $83, $27, $83, $27
	.byte $27, $83, $27, $83, $27, $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $03
	.byte $41, $35
	.word @song0ref717
	.byte $4f, $03
	.byte $41, $32
	.word @song0ref717
	.byte $29, $29, $81, $29, $4f, $01, $a8
@song0ref824:
	.byte $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81, $7c, $25, $78, $25, $81
	.byte $7c, $25, $78, $25, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24, $81, $7c, $24, $78, $24
	.byte $81, $7c, $24, $78, $24, $7c
	.byte $41, $12
	.word @song0ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27
	.byte $7c
	.byte $41, $20
	.word @song0ref824
	.byte $7c
	.byte $41, $12
	.word @song0ref824
	.byte $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $27, $78, $27, $81, $7c, $29, $78, $29, $81, $7c, $29, $78, $29
	.byte $45, $87, $44, $00
@song0ch2:
	.byte $ff, $ff, $a6
@song0ref945:
	.byte $19, $9d, $14, $9d, $16, $9d, $12, $9d, $19, $9d, $14, $9d, $16, $9d, $12, $9d, $00, $9d
@song0ref963:
	.byte $19, $81, $25, $19, $83, $25, $19, $83, $25, $19, $83, $25, $19, $14, $81, $20, $14, $83, $20, $14, $83, $20, $14, $83
	.byte $20, $14, $16, $81, $22, $16, $83, $22, $16, $83, $22, $16, $83, $22, $16, $12, $81, $1e, $12, $83, $1e, $12, $83, $1e
	.byte $12, $83, $1e, $12
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $34
	.word @song0ref963
	.byte $41, $11
	.word @song0ref945
	.byte $87, $44, $00
@song0ch3:
	.byte $ff, $ef, $71, $88, $1f, $72, $81, $73, $81, $74, $81, $75, $81, $76, $81, $77, $81, $78, $81, $79, $a4, $1f, $81, $ac
	.byte $21, $81, $7f
@song0ref1070:
	.byte $84, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $84, $14, $81, $80, $21, $23
@song0ref1088:
	.byte $86, $14, $81, $80, $21, $81, $84, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $84, $14, $81, $80, $21, $23
	.byte $86, $14, $81, $80, $21, $81
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $1c
	.word @song0ref1070
	.byte $8f, $71, $a6, $1f, $72, $81, $73, $81, $75, $81, $77, $81, $7a, $81, $7c, $81, $7f, $81
	.byte $41, $14
	.word @song0ref1088
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $41, $20
	.word @song0ref1070
	.byte $84, $14, $81, $80, $21, $23, $86, $14, $80, $23, $21, $81, $84, $14, $81, $80, $21, $23, $a4, $1f, $8d, $45, $ed, $ff
	.byte $89, $44, $00
@song0ch4:
	.byte $ff, $ff
@song0ref1223:
	.byte $87, $19, $8d, $19, $8d, $19, $8d, $19, $8d, $19, $8d, $19, $8d, $19, $8d, $19, $85
	.byte $41, $11
	.word @song0ref1223
	.byte $9f
@song0ref1244:
	.byte $14, $81, $08, $81, $19, $81, $08, $85, $08, $81, $19, $81, $08, $81, $14, $81, $07, $81, $19, $81, $07, $85, $07, $81
	.byte $19, $81, $07, $81, $14, $81, $10, $81, $19, $81, $10, $85, $10, $81, $19, $81, $10, $81, $14, $81, $06, $81, $19, $81
	.byte $06, $85, $06, $81, $19, $81, $06, $81
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $41, $38
	.word @song0ref1244
	.byte $00, $fd, $ff, $89, $44, $00
@song0ch19:
@song0ch18:
@song0ch17:
@song0ch16:
@song0ch15:
@song0ch14:
@song0ch13:
@song0ch12:
@song0ch11:
@song0ch10:
@song0ch9:
@song0ch8:
@song0ch7:
@song0ch6:
@song0ch5:
	.byte $ff, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $89, $44, $00
@song1ch0:
	.byte $46, $08, $4f, $01, $b2, $2a, $83, $a8
@song1ref9:
	.byte $2a, $81, $2a, $26, $81, $2d, $26, $81, $32, $2b, $81, $2d, $2a, $81, $2d, $83, $2a, $2d, $81, $26, $2a, $83, $2a, $81
	.byte $2a, $26, $81, $2d, $32, $81, $2d, $2b, $81, $2a, $28, $83, $26, $87, $4f, $02, $26, $4f, $02, $2a, $83
	.byte $41, $1e
	.word @song1ref9
	.byte $34, $36, $81, $37, $36, $81, $32, $34, $81, $32, $34, $81, $36, $74, $88, $32, $81, $45, $7f, $a8
@song1ref77:
	.byte $36, $81, $36, $37, $81, $37, $36, $81, $36, $32, $81, $32, $36, $81, $36, $37, $81, $37, $39, $81, $39, $32, $81, $32
	.byte $41, $12
	.word @song1ref77
	.byte $30, $81, $31, $32, $81, $32
	.byte $41, $18
	.word @song1ref77
	.byte $41, $12
	.word @song1ref77
	.byte $30, $81, $31, $32, $81, $32
	.byte $41, $18
	.word @song1ref77
	.byte $41, $15
	.word @song1ref77
	.byte $3e, $81, $3e, $3c, $81, $3c, $3b, $81, $3b
@song1ref137:
	.byte $39, $81, $39, $37, $81, $36, $37, $81, $36, $37, $81, $36, $34, $81, $2d, $32, $81, $32, $36, $81, $36, $37, $81, $37
	.byte $41, $0e
	.word @song1ref137
	.byte $32, $7d, $4f, $01, $81, $75, $81, $7f
@song1ref172:
	.byte $2a, $2b, $81, $2a, $2b, $81, $2d, $83, $32, $2d, $81, $2b, $2a, $83, $2b, $81, $2a, $26, $81, $2a, $26, $81
	.byte $41, $0d
	.word @song1ref172
	.byte $81, $2d, $2b, $81, $2a, $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song1ref172
	.byte $41, $11
	.word @song1ref172
	.byte $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song1ref172
	.byte $41, $11
	.word @song1ref172
	.byte $2b, $81, $2d, $26, $81
	.byte $41, $16
	.word @song1ref172
	.byte $2a, $2b, $81, $2a, $2b, $81, $2d, $83, $32, $36, $81, $37, $36, $81, $32, $34, $81, $32, $34, $81, $36, $98, $32
@song1ref255:
	.byte $00, $ae, $1a, $00, $83, $1a, $00, $1a, $00, $81, $1a, $1e, $00, $81, $1e, $00, $1f, $1e, $00, $1e, $00, $81, $1e, $1f
	.byte $00, $81, $1f, $00, $21, $00, $81, $1f, $00, $81, $1f, $21, $00, $81, $21, $00, $26, $25, $00, $21, $00, $81, $21, $98
	.byte $0e
	.byte $41, $27
	.word @song1ref255
	.byte $25, $00, $81, $21, $00, $81, $21, $a8
@song1ref315:
	.byte $32, $87, $2b, $83, $2d, $81, $00, $81, $32, $83, $37, $83, $36, $81, $2b, $34, $83
	.byte $41, $0e
	.word @song1ref315
	.byte $37, $39, $83
	.byte $41, $11
	.word @song1ref315
	.byte $41, $0e
	.word @song1ref315
	.byte $37, $39, $83, $4f, $00, $b8
@song1ref350:
	.byte $26, $83, $2b, $83, $2a, $83, $28, $83, $26, $83, $2b, $83, $2a, $83, $28, $83, $26, $83, $2b, $83, $2a, $83, $28, $83
	.byte $2d, $83, $2b, $83, $2a, $83, $25, $83, $4f, $00
	.byte $41, $20
	.word @song1ref350
	.byte $b2, $26, $83, $00, $87, $44, $00
@song1ch1:
	.byte $78, $4f, $02, $ac
@song1ref399:
	.byte $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $0e, $74, $15, $78, $1a, $12, $74, $15, $78
	.byte $1e, $12, $74, $15, $78, $1e, $12, $74, $15, $78, $1e, $12, $74, $15, $78, $1e, $13, $74, $17, $78, $1f, $13, $74, $17
	.byte $78, $1f, $13, $74, $17, $78, $1f, $13, $74, $17, $78, $1f, $15, $74, $19, $78, $21, $15, $74, $19, $78, $21, $15, $74
	.byte $19, $78, $21, $15, $74, $19, $78, $21, $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $4f, $02
	.byte $41, $30
	.word @song1ref399
	.byte $41, $0d
	.word @song1ref399
	.byte $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $12, $74, $1a, $78, $1e, $7a, $b0, $26, $81, $45
	.byte $2b, $81, $45, $2a, $81, $45, $28, $81, $45, $2d, $81, $45, $2b, $81, $45, $2a, $81, $45, $25, $81, $45, $26, $81, $45
	.byte $89, $44, $00
@song1ch2:
	.byte $df, $df, $df, $df, $df, $df, $00, $81, $a6
@song1ref613:
	.byte $1a, $00, $81, $1a, $00, $81, $1a, $00, $81, $1a, $00, $81, $1e, $00, $81, $1e, $00, $81, $1e, $00, $81, $1e, $00, $81
	.byte $1f, $00, $81, $1f, $00, $81, $1f, $00, $81, $1f, $00, $81, $21, $00, $81, $21, $00, $81, $21, $00, $81, $21, $00, $81
	.byte $41, $30
	.word @song1ref613
	.byte $41, $30
	.word @song1ref613
	.byte $41, $2e
	.word @song1ref613
@song1ref670:
	.byte $1a, $81, $00, $8f, $1a, $1e, $81, $00, $8f, $1e, $1f, $81, $00, $8f, $1f, $21, $81, $00, $91
	.byte $41, $13
	.word @song1ref670
	.byte $41, $13
	.word @song1ref670
	.byte $41, $13
	.word @song1ref670
	.byte $41, $13
	.word @song1ref670
	.byte $41, $13
	.word @song1ref670
	.byte $0e, $83, $00, $87, $44, $00
@song1ch3:
	.byte $7c, $96, $1f, $7a, $83, $74, $81, $71, $81, $70, $d5, $df, $7c, $1f, $7a, $83, $7f
@song1ref728:
	.byte $80
@song1ref729:
	.byte $22, $81, $22, $22, $81, $22, $22, $81, $22, $82, $22, $83, $80, $22, $81, $22, $22, $81, $22, $22, $81, $22, $82, $22
	.byte $83
	.byte $41, $15
	.word @song1ref728
	.byte $81, $80, $22
	.byte $41, $16
	.word @song1ref729
	.byte $41, $11
	.word @song1ref728
	.byte $84, $16, $81, $80, $22
@song1ref771:
	.byte $7c, $96, $1f, $7a, $83, $7f
@song1ref777:
	.byte $84, $14, $81, $80, $22, $22, $81, $22, $84, $14, $81, $80, $22, $82, $22, $81, $80, $22, $84, $14, $81, $80, $22, $22
	.byte $81, $22, $84, $14, $81, $80, $22, $82, $22, $81, $80, $22
	.byte $41, $18
	.word @song1ref777
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $41, $1a
	.word @song1ref771
	.byte $41, $18
	.word @song1ref777
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $41, $1a
	.word @song1ref771
	.byte $41, $18
	.word @song1ref777
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $41, $1a
	.word @song1ref771
	.byte $41, $18
	.word @song1ref777
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $41, $1a
	.word @song1ref771
	.byte $41, $18
	.word @song1ref777
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $41, $1a
	.word @song1ref771
	.byte $41, $18
	.word @song1ref777
	.byte $41, $15
	.word @song1ref777
	.byte $78, $22, $81, $22, $7a, $22, $81, $22, $7b, $22, $81, $22, $22, $81, $22, $7c, $22, $81, $22, $7f, $22, $81, $22, $22
	.byte $81, $22, $84, $14, $83, $7c, $96, $1f, $7a, $83, $74, $81, $71, $81, $70, $85, $44, $00
@song1ch4:
	.byte $14, $dd, $df, $14, $dd, $d1, $14, $14, $83
@song1ref931:
	.byte $19, $83, $14, $83, $19, $81, $14, $83, $14, $19, $83, $14, $83, $19, $81, $14, $83, $14
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $41, $12
	.word @song1ref931
	.byte $19, $ad, $19, $83, $14, $8d, $44, $00
@song1ch19:
@song1ch18:
@song1ch17:
@song1ch16:
@song1ch15:
@song1ch14:
@song1ch13:
@song1ch12:
@song1ch11:
@song1ch10:
@song1ch9:
@song1ch8:
@song1ch7:
@song1ch6:
@song1ch5:
	.byte $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $8f, $44, $00
@song2ch0:
	.byte $46, $03, $77, $9e, $21, $8d, $43, $50, $39, $2d, $21, $85, $43, $15, $85, $4f, $02, $a6, $10, $85, $00, $85, $10, $83
	.byte $00, $10, $85, $00, $8d, $0c, $85, $00, $85, $10, $85, $00, $85, $10
@song2ref39:
	.byte $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $83, $00, $10, $85, $00, $85, $09, $85
	.byte $10, $85, $00, $85, $10, $85, $00, $85, $11, $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85, $10, $85, $00, $85
	.byte $10, $83, $00, $10, $85, $00, $85, $15, $85, $0c, $85, $00, $85, $13, $85, $00, $85, $13
	.byte $41, $24
	.word @song2ref39
	.byte $4f, $00, $9e, $21, $8d, $43, $50, $3c, $2d, $23, $83, $00, $88, $21, $81, $00, $81, $24, $85, $21, $85, $1f, $81, $00
	.byte $81, $21, $85, $00, $8d, $23, $24, $83, $00, $85, $1f, $85, $00, $85, $24, $85, $00, $85
@song2ref150:
	.byte $21, $85, $00, $8d, $21, $81, $00, $81, $24, $85, $21, $85, $1f, $81, $00, $81, $21, $85, $00, $85, $21, $81, $00, $81
	.byte $24, $81, $00, $81, $21, $81, $00, $81, $1c, $81, $00, $81, $22, $85, $00, $85, $1f, $85, $21, $85, $00, $8d, $21, $81
	.byte $00, $81, $24, $85, $21, $85, $1f, $81, $00, $81, $21, $85, $00, $8d, $1c, $81, $00, $81, $1c, $81, $00, $81, $1c, $81
	.byte $00, $81, $1f, $81, $00, $81, $1f, $81, $00, $81, $1f, $81, $00, $81, $a6
	.byte $41, $20
	.word @song2ref150
	.byte $24, $81, $00, $81, $26, $81, $00, $81, $21, $81, $00, $81, $1f, $81, $00, $81, $9e, $1c, $81, $00, $81, $1c, $81, $00
	.byte $81, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $1c, $85, $00, $85, $1c, $85, $24, $85, $21, $85, $50, $fe, $2e
	.byte $2f, $89, $43, $23, $89, $21, $81, $23, $81, $24, $85, $21, $81, $23, $81, $24, $85, $21, $81, $23, $81, $26, $85, $23
	.byte $81, $24, $81, $26, $85, $24, $81, $26, $81, $28, $85, $24, $81, $23, $81, $24, $81, $00, $81, $24, $81, $21, $81, $23
	.byte $85, $24, $81, $23, $81, $24, $81, $00, $81, $23, $85
@song2ref347:
	.byte $21, $89, $00, $81
@song2ref351:
	.byte $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $1d, $8d, $00, $85, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85
	.byte $1f, $85, $87, $00, $85, $23, $85, $24, $85, $24, $85, $23, $85, $21, $85, $26, $8d, $24, $85, $23, $85, $24, $8d, $23
	.byte $85, $1f, $85, $21, $85, $87, $00, $85
	.byte $41, $32
	.word @song2ref351
	.byte $8d
	.byte $41, $39
	.word @song2ref347
	.byte $41, $36
	.word @song2ref347
	.byte $8d
	.byte $41, $39
	.word @song2ref347
	.byte $41, $36
	.word @song2ref347
	.byte $8d, $7f
@song2ref426:
	.byte $4f, $01, $96
@song2ref429:
	.byte $21, $85, $9c, $28, $81, $00, $81, $96, $23, $85, $9c, $28, $81, $00, $81, $96, $24, $85, $9c, $28, $81, $00, $81, $96
	.byte $21, $85, $1d, $8d, $9c, $24, $81, $00, $81, $29, $81, $00, $81, $24, $81, $00, $89, $24, $81, $00, $81, $29, $81, $00
	.byte $81, $24, $81, $00, $81, $96, $24, $85, $9c, $2b, $81, $00, $81, $96, $23, $85, $9c, $2b, $81, $00, $81, $96, $24, $85
	.byte $23, $85, $21, $85, $26, $8d, $9c, $26, $81, $00, $81, $2b, $81, $00, $81, $26, $81, $00, $81, $96, $24, $85, $9c, $26
	.byte $81, $00, $81, $2b, $81, $00, $81, $26, $81, $00, $81
	.byte $41, $41
	.word @song2ref426
	.byte $85, $4b, .lobyte(@env48), .hibyte(@env48), $30, $83, $45, $87, $4b, .lobyte(@env13), .hibyte(@env13), $30, $83, $45
	.byte $87, $7a, $4b, .lobyte(@env25), .hibyte(@env25), $4c, $b4, $13, $8d, $4f, $03, $8f, $15, $85, $18, $85, $17, $85, $17
	.byte $85, $18, $85, $15, $85, $15, $85, $50, $f9, $27, $28, $83, $43, $1c, $87, $43, $1c, $85, $18, $85, $1a, $85, $1c, $85
	.byte $18, $85, $1a, $85, $18, $85, $21, $85, $1c, $85, $1a, $85, $21, $85, $1c, $85, $1a, $85, $1c, $85, $50, $f9, $2c, $2d
	.byte $81, $43, $21, $81, $49, .lobyte(@env45), .hibyte(@env45), $87, $b4, $21, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $21, $85, $1f, $85, $24, $85, $23, $85, $21, $85, $1f, $85, $21, $8d, $23, $8d, $50, $f4, $2f, $30, $43, $24, $83
	.byte $21, $8d, $26, $85, $49, .lobyte(@env45), .hibyte(@env45), $87, $49, .lobyte(@env0), .hibyte(@env0), $4a, $b4, $24
	.byte $85, $23, $85, $24, $85, $26, $85, $24, $85, $26, $85, $28, $85, $2d, $8d, $49, .lobyte(@env24), .hibyte(@env24), $87
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d
	.byte $83, $49, .lobyte(@env15), .hibyte(@env15), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $50, $0e, $39, $37
	.byte $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d, $83, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39
	.byte $43, $2d, $83, $43, $50, $0e, $39, $37, $43, $2b, $83, $43, $50, $f2, $37, $39, $43, $2d, $9b, $4f, $02, $88, $21, $85
	.byte $76, $a2, $15, $85, $73, $15, $85, $7a, $88, $21, $85, $73, $a2, $15, $85, $76, $15, $85, $73, $15, $85, $76, $15, $85
	.byte $7a, $88, $21, $85, $76, $a2, $15, $85, $73, $15, $85, $7a, $88, $21, $85, $73, $a2, $15, $85, $76, $15, $85, $73, $15
	.byte $85, $76, $15, $85, $7a, $4f, $02, $88, $21, $85, $76, $a2, $15, $85, $73, $15, $85, $7a, $88, $21, $85, $73, $a2, $15
	.byte $85, $76, $15, $85, $73, $15, $85, $76, $15, $85, $7a, $88, $21, $85, $76, $a2, $15, $85, $73, $15, $85, $76, $15, $85
	.byte $7a, $88, $24, $85, $23, $85, $24, $85, $23, $85, $7f, $4f, $02, $b4, $21, $85, $7a, $87, $76, $87, $79, $88, $21, $85
	.byte $73, $a2, $15, $85, $74, $15, $85, $72, $15, $85, $74, $15, $85, $78, $88, $21, $85, $74, $a2, $15, $85, $71, $15, $85
	.byte $77, $88, $21, $85, $71, $a2, $15, $85, $73, $15, $85, $71, $15, $85, $73, $15, $85, $76, $4f, $02, $88, $21, $85, $71
	.byte $a2, $15, $85, $73, $15, $85, $75, $88, $21, $85, $71, $a2, $15, $85, $72, $15, $85, $71, $15, $85, $72, $15, $85, $74
	.byte $88, $21, $85, $72, $a2, $15, $85, $71, $15, $85, $00, $85, $73, $88, $24, $85, $23, $85, $24, $85, $23, $85, $44, $00
@song2ch1:
	.byte $77, $4f, $02, $a6
@song2ref993:
	.byte $15, $85, $00, $85, $15, $85, $00, $85, $18, $85, $00, $85, $18, $85, $15, $85, $00
@song2ref1010:
	.byte $85, $15, $85, $10, $85, $00, $85, $13, $85, $00, $85, $13
@song2ref1022:
	.byte $85, $00, $85, $15, $85, $00, $85, $15, $85, $00, $85, $18, $85, $00, $85, $18, $85, $15, $85, $00, $8d, $15, $85, $00
	.byte $85, $13, $85, $00, $85, $14, $85, $00, $85, $15, $85, $00, $85, $15, $85, $00, $85, $18, $85, $00, $85, $18, $85, $15
	.byte $85, $00, $8d, $10, $85, $00, $85, $17, $85, $00, $85, $17
	.byte $41, $21
	.word @song2ref1022
	.byte $4f, $02
	.byte $41, $4f
	.word @song2ref993
	.byte $41, $2d
	.word @song2ref1010
	.byte $ff, $ff, $b7, $9e, $21, $8d, $00, $ad, $1c, $85, $87, $00, $ad, $1f, $8d, $00, $b5, $b7, $21, $8d, $00, $ad, $1c, $85
	.byte $87, $00, $ad, $1f, $8d, $00, $b5, $7f, $96
@song2ref1126:
	.byte $21, $85, $00, $85, $21, $85, $00, $85, $21, $85, $00, $85, $2d, $85, $77, $9e, $21, $8d, $7f, $00, $85, $96, $24, $85
	.byte $00, $85, $24, $85, $00, $85, $24, $85, $77, $9e, $1c, $85, $7f, $96, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85
	.byte $23, $85, $21, $85, $77, $9e, $1f, $8d, $7f, $00, $85, $96, $23, $85, $00, $85, $24, $85, $00, $85, $23, $85, $00, $85
	.byte $41, $3c
	.word @song2ref1126
	.byte $41, $3c
	.word @song2ref1126
	.byte $41, $3c
	.word @song2ref1126
	.byte $77, $9e, $21, $8d, $43, $50, $39, $2d, $21, $85, $43, $15, $85, $7f, $96
@song2ref1222:
	.byte $1c, $85, $00, $85, $1c, $85, $1d, $8d, $00, $85, $1d, $85, $00, $85, $1d, $85, $00, $85, $1d, $85, $00, $85, $1f, $85
	.byte $00, $85, $1f, $85, $00, $85, $1f, $85, $1f, $85, $1f, $85, $1f, $8d, $00, $85, $1f, $85, $00, $85, $21, $85, $00, $85
	.byte $1f, $85, $00, $85, $1c, $85, $00, $85, $1c, $85, $00, $85
	.byte $41, $34
	.word @song2ref1222
	.byte $4f, $01
	.byte $41, $5c
	.word @song2ref429
	.byte $41, $42
	.word @song2ref426
	.byte $00, $85, $23, $85, $00, $85, $24, $85, $00, $85, $23, $85, $00, $85, $7a, $4f, $02, $88
@song2ref1311:
	.byte $1c, $85, $00, $8d, $1c, $85, $00, $9d, $1c, $85, $00, $8d, $1c, $85, $00, $9d, $1c, $85, $00, $8d, $1c, $85, $00, $9d
	.byte $1c, $85, $00, $95, $1c, $85, $1c, $85, $1c, $85, $1c, $85, $51, $ff, $30, $4f, $02
	.byte $41, $24
	.word @song2ref1311
	.byte $44, $00
@song2ch2:
	.byte $ff, $ff, $ff, $ff, $a6
@song2ref1363:
	.byte $1c, $85, $00, $85, $1c, $85, $00, $85, $1c, $85, $00, $85, $1c, $83, $00, $1c, $85, $00, $8d, $18, $85, $00, $85, $1c
	.byte $85, $00, $85, $1c, $85, $00, $85
	.byte $41, $1f
	.word @song2ref1363
	.byte $41, $1f
	.word @song2ref1363
	.byte $41, $1f
	.word @song2ref1363
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song2ref1409:
	.byte $96
@song2ref1410:
	.byte $28, $85, $00, $85, $28, $85, $00, $85, $28, $85, $00, $85, $34, $85, $29, $8d, $00, $85, $29, $85, $00, $85, $29, $85
	.byte $00, $85, $29, $85, $00, $85, $2b, $85, $00, $85, $2b, $85, $00, $85, $2b, $85, $2b, $85, $2b, $85, $32, $8d, $00, $85
	.byte $2b, $85, $00, $85, $2d, $85, $00, $85, $2b, $85, $00, $85
	.byte $41, $3c
	.word @song2ref1410
	.byte $41, $3c
	.word @song2ref1410
	.byte $41, $3c
	.word @song2ref1410
	.byte $41, $1e
	.word @song2ref1410
	.byte $88, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85, $23, $85, $1f, $85, $26, $8d, $00, $85, $23, $85, $00, $85, $24
	.byte $85, $00, $85, $23, $85, $00, $85
	.byte $41, $1e
	.word @song2ref1409
@song2ref1516:
	.byte $88, $24, $85, $00, $85, $23, $85, $00, $85, $24, $85, $23, $85, $1f, $85, $26, $8d, $00, $85, $1f, $85, $00, $85, $21
	.byte $85, $00, $85, $1f, $85, $00, $85
	.byte $41, $1e
	.word @song2ref1409
	.byte $41, $1e
	.word @song2ref1516
	.byte $41, $1e
	.word @song2ref1409
	.byte $41, $1e
	.word @song2ref1516
	.byte $ff, $ff, $ff, $ff, $44, $00
@song2ch3:
@song2ref1566:
	.byte $86, $14, $85, $82, $21, $85
@song2ref1572:
	.byte $80, $1d, $85, $82, $21, $85, $86, $14, $85, $82, $21, $85, $80, $1d, $85, $82, $21, $85, $86, $14, $85, $82, $21, $85
	.byte $80, $1d, $85, $82, $21, $85, $86, $14, $85, $82, $21, $85, $80, $1d, $85, $82, $21, $85
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $aa, $21, $8d
	.byte $41, $1c
	.word @song2ref1572
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $41, $20
	.word @song2ref1566
	.byte $86, $14, $85, $82, $21, $85, $80, $1d, $85, $82, $21, $85, $80, $1d, $85, $82, $21, $85, $80, $1d, $85, $82, $21, $85
	.byte $a4, $20, $8d, $7c, $84, $14, $85, $80, $21, $85, $21, $85, $21, $85, $84, $14, $85, $80, $21, $85, $7f
@song2ref1698:
	.byte $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85, $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85
	.byte $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85, $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $41, $20
	.word @song2ref1698
	.byte $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85, $86, $1f, $85, $82, $21, $85, $84, $14, $85, $82, $21, $85
	.byte $a4, $19, $8d, $80, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $1e, $85, $a4, $20, $8d
@song2ref1831:
	.byte $84, $14, $85, $80, $21, $85
@song2ref1837:
	.byte $86, $14, $85, $80, $21, $85, $84, $14, $85, $80, $21, $85, $86, $14, $85, $80, $21, $85, $84, $14, $85, $80, $21, $85
	.byte $86, $14, $85, $80, $21, $85, $84, $14, $85, $80, $21, $85, $86, $14, $85, $80, $21, $85
	.byte $41, $1c
	.word @song2ref1831
	.byte $51, $ff, $00
	.byte $41, $1c
	.word @song2ref1837
	.byte $41, $20
	.word @song2ref1831
	.byte $84, $14, $85, $80, $21, $85, $44, $00
@song2ch4:
@song2ref1900:
	.byte $14, $85, $0d, $81, $00, $81, $19, $85, $0d, $81, $00, $81, $14, $85, $11, $81, $00, $81, $19, $85, $0d, $81, $00, $81
	.byte $14, $85, $0d, $81, $00, $81, $19, $85, $0b, $81, $00, $81, $14, $85, $0c, $81, $00, $81, $19, $85, $0c, $81, $00, $81
	.byte $41, $2c
	.word @song2ref1900
	.byte $07, $81, $00, $81
	.byte $41, $30
	.word @song2ref1900
	.byte $41, $2c
	.word @song2ref1900
	.byte $07, $81, $00, $81
	.byte $41, $30
	.word @song2ref1900
	.byte $41, $2c
	.word @song2ref1900
	.byte $07, $81, $00, $81
	.byte $41, $30
	.word @song2ref1900
	.byte $41, $2c
	.word @song2ref1900
	.byte $07, $81, $00, $81, $14, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $19, $85, $0d, $48, $01, $81, $0d, $48, $01, $81
	.byte $14, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $19, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $14, $85, $11, $48
	.byte $01, $81, $11, $48, $01, $81, $19, $85, $11, $48, $01, $81, $11, $48, $01, $81, $14, $85, $11, $48, $01, $81, $11, $48
	.byte $01, $81, $19, $85, $11, $48, $01, $81, $11, $48, $01, $81, $14, $85, $0e, $48, $01, $81, $0e, $48, $01, $81, $19, $85
	.byte $0e, $48, $01, $81, $0e, $48, $01, $81, $14, $85, $0e, $48, $01, $81, $0e, $48, $01, $81, $19, $85, $0e, $48, $01, $81
	.byte $0e, $48, $01, $81, $14, $85, $04, $48, $01, $81, $04, $48, $01, $81, $19, $85, $04, $48, $01, $81, $04, $48, $01, $81
	.byte $14, $85, $04, $48, $01, $81, $04, $48, $01, $81, $19, $85, $04, $48, $01, $81, $04
@song2ref2142:
	.byte $48, $01, $81, $14, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $19, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $14
	.byte $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $19, $85, $0d, $48, $01, $81, $0d, $48, $01, $81, $14, $85, $09, $48, $01
	.byte $81, $09, $48, $01, $81, $19, $85, $09, $48, $01, $81, $09, $48, $01, $81, $14, $85, $09, $48, $01, $81, $09, $48, $01
	.byte $81, $19, $85, $09, $48, $01, $81, $09, $48, $01, $81, $14, $85, $11, $48, $01, $81, $11, $48, $01, $81, $19, $85, $11
	.byte $48, $01, $81, $11, $48, $01, $81, $14, $85, $11, $48, $01, $81, $11, $48, $01, $81, $19, $85, $11, $48, $01, $81, $11
	.byte $48, $01, $81, $14, $85, $12, $48, $01, $81, $12, $48, $01, $81, $19, $85, $12, $48, $01, $81, $12, $48, $01, $81, $14
	.byte $85, $0e, $48, $01, $81, $0e, $48, $01, $81, $19, $85, $0e, $48, $01, $81, $0e
	.byte $41, $4e
	.word @song2ref2142
	.byte $48, $01, $89, $12, $48, $01, $81, $12, $48, $01, $89, $0e, $48, $01, $81, $0e, $48, $01, $89, $0e, $48, $01, $81, $0e
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $60
	.word @song2ref2142
	.byte $41, $4e
	.word @song2ref2142
	.byte $48, $01, $89, $12, $48, $01, $81, $12, $48, $01, $89, $0e, $48, $01, $81, $0e, $48, $01, $89, $0e, $48, $01, $81, $0e
	.byte $48, $01
@song2ref2379:
	.byte $81, $14, $85, $0d, $81, $0d, $81, $0d, $81, $00, $81, $0d, $81, $0d, $81, $14, $85, $0d, $81, $0d, $81, $0d, $81, $00
	.byte $81, $0d, $81, $0d
	.byte $41, $1c
	.word @song2ref2379
	.byte $41, $1c
	.word @song2ref2379
	.byte $41, $1c
	.word @song2ref2379
	.byte $41, $1c
	.word @song2ref2379
	.byte $41, $1c
	.word @song2ref2379
	.byte $81, $14, $85, $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $14, $85, $0d, $81, $00, $81, $0d, $81, $00
	.byte $81, $0d, $81, $00, $81, $14, $85, $0d, $81, $00, $89, $0d, $81, $00, $81, $14, $85, $0d, $81, $00, $89, $0d, $81, $00
	.byte $81, $44, $00
@song2ch19:
@song2ch18:
@song2ch17:
@song2ch16:
@song2ch15:
@song2ch14:
@song2ch13:
@song2ch12:
@song2ch11:
@song2ch10:
@song2ch9:
@song2ch8:
@song2ch7:
@song2ch6:
@song2ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $44, $00
@song3ch0:
	.byte $46, $03
@song3ch0loop:
	.byte $bf, $bf, $bf, $bf, $4f, $01, $aa, $19, $89, $12, $89, $19, $81, $1a, $81, $19, $95, $00, $85, $97, $19, $81, $1a, $81
	.byte $19, $89, $17, $91, $16, $95, $00, $a5, $b9, $47, $02, $ac, $19, $47, $01, $19, $47, $00, $19, $4f, $01, $aa, $19, $89
	.byte $12, $89, $19, $81, $1a, $81, $19, $95, $00, $85, $97, $19, $81, $1a, $81, $19, $89, $17, $8d, $16, $81, $16, $85, $19
	.byte $95, $00, $9d, $b7, $1c, $85, $1c, $8d, $00, $85, $1a, $8d, $00, $95, $19, $95, $00, $a5, $1c, $95, $00, $9d, $1a, $85
	.byte $19, $95, $00, $a5, $1c, $95, $00, $9d, $1a, $85, $87, $19, $8b, $00, $a7, $15, $95, $00, $a5, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $7c, $aa
@song3ref134:
	.byte $06, $85, $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $85, $19, $81, $19, $81, $06, $81, $06, $85
	.byte $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $85, $19, $81, $19, $81, $06, $81
	.byte $41, $2c
	.word @song3ref134
	.byte $41, $2c
	.word @song3ref134
	.byte $41, $2c
	.word @song3ref134
	.byte $41, $2c
	.word @song3ref134
@song3ref190:
	.byte $06, $85, $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $81, $08, $81, $09, $81, $0b, $81, $0d, $81
	.byte $06, $85, $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $81, $08, $81, $09, $81, $0b, $81, $0d, $81
	.byte $41, $2c
	.word @song3ref134
	.byte $41, $2c
	.word @song3ref134
@song3ref244:
	.byte $04, $89, $19, $81, $04, $89, $19, $85, $43, $04, $85, $19, $85, $19, $81, $19, $81, $04, $81, $04, $89, $19, $81, $04
	.byte $89, $19, $85, $43, $04, $85, $19, $85, $19, $81, $19, $81, $04, $81
	.byte $41, $24
	.word @song3ref244
	.byte $41, $30
	.word @song3ref190
	.byte $41, $30
	.word @song3ref190
	.byte $06, $85, $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $81, $08, $85, $09, $85
	.byte $41, $28
	.word @song3ref190
	.byte $0e, $85, $0d, $85, $06, $85, $00, $81, $19, $81, $06, $85, $00, $81, $19, $85, $00, $85, $19, $81, $08, $81, $09, $81
	.byte $0b, $81, $0d, $81, $42
	.word @song3ch1loop
@song3ch19:
@song3ch18:
@song3ch17:
@song3ch16:
@song3ch15:
@song3ch14:
@song3ch13:
@song3ch12:
@song3ch11:
@song3ch10:
@song3ch9:
@song3ch8:
@song3ch7:
@song3ch6:
@song3ch5:
@song3ch2:
@song3ch2loop:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $80
@song3ref394:
	.byte $23, $81, $00, $85, $23, $81, $9a, $20, $85, $00
@song3ref404:
	.byte $81, $92, $14, $00, $80, $23, $81, $00
@song3ref412:
	.byte $85, $92, $14, $00, $80, $23, $81, $00, $81, $23, $23, $23, $23, $23, $81, $00, $85, $23, $81, $9a, $20, $85, $00, $81
	.byte $92, $14, $00, $80, $23, $81, $00, $81, $9a, $1a, $81, $92, $14, $00, $80, $23, $81, $00, $81, $23, $23, $23, $23
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a
	.byte $41, $20
	.word @song3ref404
	.byte $41, $27
	.word @song3ref412
	.byte $41, $22
	.word @song3ref394
	.byte $1a, $81, $92, $14, $00, $80, $23, $81, $00, $85, $92, $14, $00, $80, $23, $81, $00, $81, $23, $23, $23, $23, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref548:
	.byte $14, $81, $00, $85, $14, $81, $00, $ad, $14, $81, $00, $85, $14, $81, $00, $ad, $14, $81, $00, $85, $14, $81, $00, $91
	.byte $14, $81, $00, $95, $14, $81, $00, $85, $14, $81, $00, $ad
	.byte $41, $24
	.word @song3ref548
	.byte $41, $24
	.word @song3ref548
	.byte $41, $24
	.word @song3ref548
	.byte $41, $24
	.word @song3ref548
	.byte $41, $24
	.word @song3ref548
	.byte $41, $24
	.word @song3ref548
	.byte $42
	.word @song3ch4loop
@song4ch0:
	.byte $46, $06
@song4ch0loop:
	.byte $8e
@song4ref5:
	.byte $10, $81, $20, $81, $20, $81, $23, $81, $23, $81
@song4ref15:
	.byte $22, $81, $22, $81, $1f, $81, $1f
@song4ref22:
	.byte $81, $00, $91, $14, $83, $00, $10, $81, $20, $81, $20, $81, $23, $81, $23, $81, $25, $81, $25, $81, $22, $81, $22
	.byte $41, $10
	.word @song4ref22
	.byte $41, $1e
	.word @song4ref15
@song4ref51:
	.byte $81, $00, $99
@song4ref54:
	.byte $10, $81, $1f, $81, $20, $81, $10, $81, $1f, $81, $20, $81, $10, $81, $1f, $81
	.byte $41, $0c
	.word @song4ref54
	.byte $1c, $81, $00, $81
	.byte $41, $10
	.word @song4ref54
	.byte $41, $0c
	.word @song4ref54
@song4ref83:
	.byte $23
@song4ref84:
	.byte $81, $00
@song4ref86:
	.byte $81, $13, $81, $22, $81, $23, $81, $13, $81, $22, $81, $23, $81, $13, $81, $22
	.byte $41, $0d
	.word @song4ref86
	.byte $1f
	.byte $41, $12
	.word @song4ref84
	.byte $41, $0d
	.word @song4ref86
	.byte $26, $81, $00, $81
	.byte $41, $28
	.word @song4ref5
	.byte $41, $10
	.word @song4ref22
	.byte $41, $1e
	.word @song4ref15
	.byte $81, $00, $99
@song4ref128:
	.byte $04, $81, $17, $81, $00, $81, $17, $81, $08, $81, $17, $81, $0a, $81, $17, $81
	.byte $41, $0c
	.word @song4ref128
	.byte $0b, $81, $17, $81
	.byte $41, $10
	.word @song4ref128
	.byte $41, $0c
	.word @song4ref128
	.byte $00, $85
@song4ref159:
	.byte $07, $81, $1a, $81, $00, $81, $1a, $81, $0b, $81, $1a, $81, $0d, $81, $1a, $81
	.byte $41, $0c
	.word @song4ref159
	.byte $0e, $81, $1a, $81
	.byte $41, $10
	.word @song4ref159
	.byte $41, $0c
	.word @song4ref159
	.byte $00, $85
	.byte $41, $28
	.word @song4ref5
	.byte $41, $10
	.word @song4ref22
	.byte $41, $1e
	.word @song4ref15
	.byte $41, $13
	.word @song4ref51
	.byte $41, $0c
	.word @song4ref54
	.byte $1c, $81, $00, $81
	.byte $41, $10
	.word @song4ref54
	.byte $41, $0c
	.word @song4ref54
	.byte $41, $13
	.word @song4ref83
	.byte $41, $0d
	.word @song4ref86
	.byte $1f
	.byte $41, $12
	.word @song4ref84
	.byte $41, $0d
	.word @song4ref86
	.byte $26, $81, $00, $81, $28, $83, $00, $97, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $8e
@song4ref241:
	.byte $04, $81, $1c, $81, $1c, $81, $20, $81, $20, $81
@song4ref251:
	.byte $1f, $81, $1f, $81, $1c, $81, $1c
@song4ref258:
	.byte $81, $00, $91, $08, $83, $00, $04, $81, $1c, $81, $1c, $81, $20, $81, $20, $81, $22, $81, $22, $81, $1f, $81, $1f
	.byte $41, $10
	.word @song4ref258
	.byte $41, $1e
	.word @song4ref251
@song4ref287:
	.byte $81, $00, $99
@song4ref290:
	.byte $90, $04, $45, $8e, $1c, $81, $1c, $81, $90, $04, $45, $8e, $1c, $81, $1c, $81, $90, $04, $45, $8e, $1c, $81
	.byte $41, $0c
	.word @song4ref290
	.byte $19, $81, $00, $81
	.byte $41, $10
	.word @song4ref290
	.byte $41, $0c
	.word @song4ref290
@song4ref325:
	.byte $20
@song4ref326:
	.byte $81, $00
@song4ref328:
	.byte $81, $90, $07, $45, $8e, $1f, $81, $1f, $81, $90, $07, $45, $8e, $1f, $81, $1f, $81, $90, $07, $45, $8e, $1f
	.byte $41, $0d
	.word @song4ref328
	.byte $1c
	.byte $41, $12
	.word @song4ref326
	.byte $41, $0d
	.word @song4ref328
	.byte $23, $81, $00, $81
	.byte $41, $28
	.word @song4ref241
	.byte $41, $10
	.word @song4ref258
	.byte $41, $1e
	.word @song4ref251
	.byte $81, $00, $99
@song4ref376:
	.byte $78, $90
@song4ref378:
	.byte $04, $45, $7f, $8e, $14, $81, $00, $81, $14, $81, $78, $90, $08, $45, $7f, $8e, $14, $81, $78, $90, $0a, $45, $0b, $45
	.byte $41, $0c
	.word @song4ref378
	.byte $78, $90, $0b, $45, $7f, $8e, $14, $81
	.byte $41, $10
	.word @song4ref376
	.byte $41, $0c
	.word @song4ref378
	.byte $00, $85
@song4ref421:
	.byte $78, $90
@song4ref423:
	.byte $07, $45, $7f, $8e, $17, $81, $00, $81, $17, $81, $78, $90, $0b, $45, $7f, $8e, $17, $81, $78, $90, $0d, $45, $0e, $45
	.byte $41, $0c
	.word @song4ref423
	.byte $78, $90, $0e, $45, $7f, $8e, $17, $81
	.byte $41, $10
	.word @song4ref421
	.byte $41, $0c
	.word @song4ref423
	.byte $00, $85
	.byte $41, $28
	.word @song4ref241
	.byte $41, $10
	.word @song4ref258
	.byte $41, $1e
	.word @song4ref251
	.byte $41, $13
	.word @song4ref287
	.byte $41, $0c
	.word @song4ref290
	.byte $19, $81, $00, $81
	.byte $41, $10
	.word @song4ref290
	.byte $41, $0c
	.word @song4ref290
	.byte $41, $13
	.word @song4ref325
	.byte $41, $0d
	.word @song4ref328
	.byte $1c
	.byte $41, $12
	.word @song4ref326
	.byte $41, $0d
	.word @song4ref328
	.byte $23, $81, $00, $81, $23, $83, $00, $97, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $92
@song4ref517:
	.byte $3c, $00, $83, $36, $00, $83, $3c, $00, $83, $36, $00, $83
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $3c, $00, $83, $36, $00, $93
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $3c, $00, $83, $36, $00, $83, $3c, $00, $8b
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $3c, $00, $83, $36, $00, $83, $3c, $00, $8b
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $41, $0c
	.word @song4ref517
	.byte $3c, $00, $83, $36, $00, $93
@song4ref616:
	.byte $a0, $08, $81, $8c, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $00, $81, $50, $6a, $33, $1e, $00, $a0, $08, $81, $8c, $50
	.byte $6a, $33, $1e, $00, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $00
	.byte $41, $0d
	.word @song4ref616
	.byte $00, $83
	.byte $41, $10
	.word @song4ref616
@song4ref665:
	.byte $a0, $08, $81, $8c, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $00, $81, $50, $6a, $33, $1e, $00, $a0, $08, $8c, $50, $6a
	.byte $33, $1e, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $50, $6a, $33, $1e, $00, $83
	.byte $41, $10
	.word @song4ref616
	.byte $41, $0d
	.word @song4ref616
	.byte $00, $83
	.byte $41, $10
	.word @song4ref616
	.byte $41, $0f
	.word @song4ref665
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song4ref727:
	.byte $88, $1c, $8c, $1c, $88, $1f, $8c, $1f, $88, $20, $8c, $20, $88, $1c, $8c, $1c, $88, $1f, $8c, $1f, $88, $20, $8c, $20
	.byte $88, $1c, $8c, $1c, $88, $1f, $8c, $1f
	.byte $41, $0e
	.word @song4ref727
	.byte $00, $81
	.byte $41, $10
	.word @song4ref727
	.byte $41, $0c
	.word @song4ref727
	.byte $88, $23, $8c, $23
@song4ref774:
	.byte $00, $81
@song4ref776:
	.byte $88, $1f, $8c, $1f, $88, $22, $8c, $22, $88, $23, $8c, $23, $88, $1f, $8c, $1f, $88, $22, $8c, $22, $88, $23, $8c, $23
	.byte $88, $1f, $8c, $1f, $88, $22, $8c, $22
	.byte $41, $0e
	.word @song4ref776
	.byte $41, $12
	.word @song4ref774
	.byte $41, $0c
	.word @song4ref776
	.byte $88, $26, $8c, $26, $00, $81, $88, $1c, $83, $00, $97, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
@song4ref832:
	.byte $80
@song4ref833:
	.byte $21, $00, $83, $1f, $00, $83, $21, $00, $83, $1f, $00, $83
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $21, $00, $83, $1f, $00, $83, $a4, $23, $87, $00, $83
@song4ref874:
	.byte $7f
@song4ref875:
	.byte $80, $1f, $78, $8a, $22, $22, $22, $94, $22, $8a, $22, $22, $22, $7f, $80, $1f, $78, $8a, $22, $22, $22, $94, $22, $8a
	.byte $22, $22, $22
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $a4, $17, $85, $7f, $00, $85
	.byte $41, $0c
	.word @song4ref832
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $41, $0c
	.word @song4ref833
	.byte $a4, $23, $87, $00, $83
	.byte $41, $10
	.word @song4ref875
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $41, $10
	.word @song4ref874
	.byte $a4, $17, $85, $7f, $00, $95, $9f, $9f, $9f, $97, $72, $51, $02, $90, $b6, $29, $85, $89, $81, $45, $81, $74, $83, $00
	.byte $89, $9f, $85, $71, $51, $02, $50, $ba, $33, $33, $33, $33, $33, $78, $51, $fe, $20, $33, $33, $33, $33, $33, $33, $00
	.byte $81, $78
@song4ref1029:
	.byte $a4, $23, $81
@song4ref1032:
	.byte $94, $22, $8a, $22, $22, $22, $94, $22, $8a, $22, $22, $22, $94, $22, $8a, $22, $22, $22
	.byte $41, $0c
	.word @song4ref1032
	.byte $22, $22, $22, $22, $22, $22, $22, $22
	.byte $41, $0c
	.word @song4ref1032
	.byte $41, $0c
	.word @song4ref1032
	.byte $22, $22, $22, $22, $22, $22
	.byte $41, $0e
	.word @song4ref1029
	.byte $41, $0c
	.word @song4ref1032
	.byte $22, $22, $22, $22, $22, $22, $22, $22
	.byte $41, $0c
	.word @song4ref1032
	.byte $41, $0c
	.word @song4ref1032
	.byte $22, $22, $22, $22, $22, $22, $a4, $17, $85, $7f, $00, $95, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $52, $ff
@song4ref1111:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
	.byte $41, $0c
	.word @song4ref1111
	.byte $52, $95
	.byte $41, $0c
	.word @song4ref1111
	.byte $9f, $9f, $9f, $9f, $52, $c3, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $42
	.word @song4ch4loop
@song4ch19:
@song4ch18:
@song4ch17:
@song4ch16:
@song4ch15:
@song4ch14:
@song4ch13:
@song4ch12:
@song4ch11:
@song4ch10:
@song4ch9:
@song4ch8:
@song4ch7:
@song4ch6:
@song4ch5:
@song4ch5loop:
	.byte $41, $0c
	.word @song4ref1111
	.byte $41, $0c
	.word @song4ref1111
	.byte $41, $0c
	.word @song4ref1111
	.byte $41, $0c
	.word @song4ref1111
	.byte $9f, $42
	.word @song4ch5loop
@song5ch0:
	.byte $46, $01
@song5ch0loop:
	.byte $97, $97, $42
	.word @song5ch0loop
@song5ch19:
@song5ch18:
@song5ch17:
@song5ch16:
@song5ch15:
@song5ch14:
@song5ch13:
@song5ch12:
@song5ch11:
@song5ch10:
@song5ch9:
@song5ch8:
@song5ch7:
@song5ch6:
@song5ch5:
@song5ch3:
@song5ch2:
@song5ch1:
@song5ch1loop:
	.byte $97, $97, $42
	.word @song5ch1loop
@song5ch4:
@song5ch4loop:
	.byte $19, $14, $13, $0f, $0a, $05, $03, $1a, $15, $1c, $16, $01, $02, $1b, $1d, $18, $00, $17, $00, $89, $42
	.word @song5ch4loop
